// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package billingmock

import (
	context "context"
	billing "xata/services/auth/billing"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CountPendingInvoices provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CountPendingInvoices(ctx context.Context, externalCustomerID string) (int, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CountPendingInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPendingInvoices'
type Client_CountPendingInvoices_Call struct {
	*mock.Call
}

// CountPendingInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CountPendingInvoices(ctx interface{}, externalCustomerID interface{}) *Client_CountPendingInvoices_Call {
	return &Client_CountPendingInvoices_Call{Call: _e.mock.On("CountPendingInvoices", ctx, externalCustomerID)}
}

func (_c *Client_CountPendingInvoices_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CountPendingInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CountPendingInvoices_Call) Return(_a0 int, _a1 error) *Client_CountPendingInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateCustomer provides a mock function with given fields: ctx, name, email, externalCustomerID, organizationsCount, metadata
func (_m *Client) CreateCustomer(ctx context.Context, name string, email string, externalCustomerID string, organizationsCount int, metadata billing.OrbCustomerMetadata) error {
	ret := _m.Called(ctx, name, email, externalCustomerID, organizationsCount, metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, billing.OrbCustomerMetadata) error); ok {
		r0 = rf(ctx, name, email, externalCustomerID, organizationsCount, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_CreateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomer'
type Client_CreateCustomer_Call struct {
	*mock.Call
}

// CreateCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - externalCustomerID string
//   - organizationsCount int
//   - metadata billing.OrbCustomerMetadata
func (_e *Client_Expecter) CreateCustomer(ctx interface{}, name interface{}, email interface{}, externalCustomerID interface{}, organizationsCount interface{}, metadata interface{}) *Client_CreateCustomer_Call {
	return &Client_CreateCustomer_Call{Call: _e.mock.On("CreateCustomer", ctx, name, email, externalCustomerID, organizationsCount, metadata)}
}

func (_c *Client_CreateCustomer_Call) Run(run func(ctx context.Context, name string, email string, externalCustomerID string, organizationsCount int, metadata billing.OrbCustomerMetadata)) *Client_CreateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(billing.OrbCustomerMetadata))
	})
	return _c
}

func (_c *Client_CreateCustomer_Call) Return(_a0 error) *Client_CreateCustomer_Call {
	_c.Call.Return(_a0)
	return _c
}

// CustomerExists provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) CustomerExists(ctx context.Context, externalCustomerID string) (bool, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CustomerExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomerExists'
type Client_CustomerExists_Call struct {
	*mock.Call
}

// CustomerExists is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) CustomerExists(ctx interface{}, externalCustomerID interface{}) *Client_CustomerExists_Call {
	return &Client_CustomerExists_Call{Call: _e.mock.On("CustomerExists", ctx, externalCustomerID)}
}

func (_c *Client_CustomerExists_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_CustomerExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_CustomerExists_Call) Return(_a0 bool, _a1 error) *Client_CustomerExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// EnsureDefaultPaymentMethod provides a mock function with given fields: ctx, stripeCustomerID, paymentMethodID
func (_m *Client) EnsureDefaultPaymentMethod(ctx context.Context, stripeCustomerID string, paymentMethodID string) error {
	ret := _m.Called(ctx, stripeCustomerID, paymentMethodID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, stripeCustomerID, paymentMethodID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_EnsureDefaultPaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDefaultPaymentMethod'
type Client_EnsureDefaultPaymentMethod_Call struct {
	*mock.Call
}

// EnsureDefaultPaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
//   - paymentMethodID string
func (_e *Client_Expecter) EnsureDefaultPaymentMethod(ctx interface{}, stripeCustomerID interface{}, paymentMethodID interface{}) *Client_EnsureDefaultPaymentMethod_Call {
	return &Client_EnsureDefaultPaymentMethod_Call{Call: _e.mock.On("EnsureDefaultPaymentMethod", ctx, stripeCustomerID, paymentMethodID)}
}

func (_c *Client_EnsureDefaultPaymentMethod_Call) Run(run func(ctx context.Context, stripeCustomerID string, paymentMethodID string)) *Client_EnsureDefaultPaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Client_EnsureDefaultPaymentMethod_Call) Return(_a0 error) *Client_EnsureDefaultPaymentMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

// FetchCustomer provides a mock function with given fields: ctx, customerID
func (_m *Client) FetchCustomer(ctx context.Context, customerID string) (*billing.Customer, error) {
	ret := _m.Called(ctx, customerID)

	var r0 *billing.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Customer); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchCustomer'
type Client_FetchCustomer_Call struct {
	*mock.Call
}

// FetchCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *Client_Expecter) FetchCustomer(ctx interface{}, customerID interface{}) *Client_FetchCustomer_Call {
	return &Client_FetchCustomer_Call{Call: _e.mock.On("FetchCustomer", ctx, customerID)}
}

func (_c *Client_FetchCustomer_Call) Run(run func(ctx context.Context, customerID string)) *Client_FetchCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchCustomer_Call) Return(_a0 *billing.Customer, _a1 error) *Client_FetchCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *Client) FetchInvoice(ctx context.Context, invoiceID string) (*billing.Invoice, error) {
	ret := _m.Called(ctx, invoiceID)

	var r0 *billing.Invoice
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Invoice); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Invoice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInvoice'
type Client_FetchInvoice_Call struct {
	*mock.Call
}

// FetchInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *Client_Expecter) FetchInvoice(ctx interface{}, invoiceID interface{}) *Client_FetchInvoice_Call {
	return &Client_FetchInvoice_Call{Call: _e.mock.On("FetchInvoice", ctx, invoiceID)}
}

func (_c *Client_FetchInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *Client_FetchInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchInvoice_Call) Return(_a0 *billing.Invoice, _a1 error) *Client_FetchInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FetchStripeCustomer provides a mock function with given fields: ctx, stripeCustomerID
func (_m *Client) FetchStripeCustomer(ctx context.Context, stripeCustomerID string) (*billing.StripeCustomer, error) {
	ret := _m.Called(ctx, stripeCustomerID)

	var r0 *billing.StripeCustomer
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.StripeCustomer); ok {
		r0 = rf(ctx, stripeCustomerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.StripeCustomer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_FetchStripeCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchStripeCustomer'
type Client_FetchStripeCustomer_Call struct {
	*mock.Call
}

// FetchStripeCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
func (_e *Client_Expecter) FetchStripeCustomer(ctx interface{}, stripeCustomerID interface{}) *Client_FetchStripeCustomer_Call {
	return &Client_FetchStripeCustomer_Call{Call: _e.mock.On("FetchStripeCustomer", ctx, stripeCustomerID)}
}

func (_c *Client_FetchStripeCustomer_Call) Run(run func(ctx context.Context, stripeCustomerID string)) *Client_FetchStripeCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_FetchStripeCustomer_Call) Return(_a0 *billing.StripeCustomer, _a1 error) *Client_FetchStripeCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// HasOutstandingInvoices provides a mock function with given fields: ctx, externalCustomerID
func (_m *Client) HasOutstandingInvoices(ctx context.Context, externalCustomerID string) (bool, error) {
	ret := _m.Called(ctx, externalCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, externalCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_HasOutstandingInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasOutstandingInvoices'
type Client_HasOutstandingInvoices_Call struct {
	*mock.Call
}

// HasOutstandingInvoices is a helper method to define mock.On call
//   - ctx context.Context
//   - externalCustomerID string
func (_e *Client_Expecter) HasOutstandingInvoices(ctx interface{}, externalCustomerID interface{}) *Client_HasOutstandingInvoices_Call {
	return &Client_HasOutstandingInvoices_Call{Call: _e.mock.On("HasOutstandingInvoices", ctx, externalCustomerID)}
}

func (_c *Client_HasOutstandingInvoices_Call) Run(run func(ctx context.Context, externalCustomerID string)) *Client_HasOutstandingInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_HasOutstandingInvoices_Call) Return(_a0 bool, _a1 error) *Client_HasOutstandingInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// HasValidDefaultPaymentMethod provides a mock function with given fields: ctx, stripeCustomerID
func (_m *Client) HasValidDefaultPaymentMethod(ctx context.Context, stripeCustomerID string) (bool, error) {
	ret := _m.Called(ctx, stripeCustomerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, stripeCustomerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeCustomerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_HasValidDefaultPaymentMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasValidDefaultPaymentMethod'
type Client_HasValidDefaultPaymentMethod_Call struct {
	*mock.Call
}

// HasValidDefaultPaymentMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeCustomerID string
func (_e *Client_Expecter) HasValidDefaultPaymentMethod(ctx interface{}, stripeCustomerID interface{}) *Client_HasValidDefaultPaymentMethod_Call {
	return &Client_HasValidDefaultPaymentMethod_Call{Call: _e.mock.On("HasValidDefaultPaymentMethod", ctx, stripeCustomerID)}
}

func (_c *Client_HasValidDefaultPaymentMethod_Call) Run(run func(ctx context.Context, stripeCustomerID string)) *Client_HasValidDefaultPaymentMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_HasValidDefaultPaymentMethod_Call) Return(_a0 bool, _a1 error) *Client_HasValidDefaultPaymentMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// VoidInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *Client) VoidInvoice(ctx context.Context, invoiceID string) error {
	ret := _m.Called(ctx, invoiceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_VoidInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoidInvoice'
type Client_VoidInvoice_Call struct {
	*mock.Call
}

// VoidInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *Client_Expecter) VoidInvoice(ctx interface{}, invoiceID interface{}) *Client_VoidInvoice_Call {
	return &Client_VoidInvoice_Call{Call: _e.mock.On("VoidInvoice", ctx, invoiceID)}
}

func (_c *Client_VoidInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *Client_VoidInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_VoidInvoice_Call) Return(_a0 error) *Client_VoidInvoice_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
