apiVersion: v1
kind: ServiceAccount
metadata:
  name: arm-backups
  namespace: xata-clusters

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arm-backups
  namespace: xata-clusters
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - scheduledbackups
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - barmancloud.cnpg.io
    resources:
      - objectstores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - backups
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arm-backups
  namespace: xata-clusters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arm-backups
subjects:
  - kind: ServiceAccount
    name: arm-backups
    namespace: xata-clusters
