apiVersion: v1
kind: Service
metadata:
  name: clusters
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
  selector:
    app: clusters
