// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	XataScopes = "xata.Scopes"
)

// Defines values for BranchCreationDetailsMode.
const (
	BranchCreationDetailsModeCustom  BranchCreationDetailsMode = "custom"
	BranchCreationDetailsModeInherit BranchCreationDetailsMode = "inherit"
)

// Defines values for BranchFromConfigurationMode.
const (
	BranchFromConfigurationModeCustom BranchFromConfigurationMode = "custom"
)

// Defines values for BranchFromParentMode.
const (
	Inherit BranchFromParentMode = "inherit"
)

// Defines values for BranchMetricsRequestAggregations.
const (
	BranchMetricsRequestAggregationsAvg BranchMetricsRequestAggregations = "avg"
	BranchMetricsRequestAggregationsMax BranchMetricsRequestAggregations = "max"
	BranchMetricsRequestAggregationsMin BranchMetricsRequestAggregations = "min"
)

// Defines values for BranchMetricsRequestMetric.
const (
	ConnectionsActive  BranchMetricsRequestMetric = "connections_active"
	ConnectionsIdle    BranchMetricsRequestMetric = "connections_idle"
	Cpu                BranchMetricsRequestMetric = "cpu"
	Disk               BranchMetricsRequestMetric = "disk"
	IopsRead           BranchMetricsRequestMetric = "iops_read"
	IopsWrite          BranchMetricsRequestMetric = "iops_write"
	LatencyRead        BranchMetricsRequestMetric = "latency_read"
	LatencyWrite       BranchMetricsRequestMetric = "latency_write"
	Memory             BranchMetricsRequestMetric = "memory"
	NetworkEgress      BranchMetricsRequestMetric = "network_egress"
	NetworkIngress     BranchMetricsRequestMetric = "network_ingress"
	ReplicationLagTime BranchMetricsRequestMetric = "replication_lag_time"
	ThroughputRead     BranchMetricsRequestMetric = "throughput_read"
	ThroughputWrite    BranchMetricsRequestMetric = "throughput_write"
	WalSyncTime        BranchMetricsRequestMetric = "wal_sync_time"
)

// Defines values for ExtensionType.
const (
	ExtensionTypeExtension ExtensionType = "extension"
	ExtensionTypeModule    ExtensionType = "module"
	ExtensionTypePlugin    ExtensionType = "plugin"
)

// Defines values for MetricSeriesAggregation.
const (
	MetricSeriesAggregationAvg MetricSeriesAggregation = "avg"
	MetricSeriesAggregationMax MetricSeriesAggregation = "max"
	MetricSeriesAggregationMin MetricSeriesAggregation = "min"
)

// Defines values for PostgresConfigParameterDefaultValueSource.
const (
	InstanceType PostgresConfigParameterDefaultValueSource = "instance_type"
	Postgres     PostgresConfigParameterDefaultValueSource = "postgres"
)

// Defines values for PostgresConfigParameterType.
const (
	Boolean  PostgresConfigParameterType = "boolean"
	Bytes    PostgresConfigParameterType = "bytes"
	Duration PostgresConfigParameterType = "duration"
	Enum     PostgresConfigParameterType = "enum"
	Float    PostgresConfigParameterType = "float"
	Int      PostgresConfigParameterType = "int"
	String   PostgresConfigParameterType = "string"
)

// BackupConfiguration Details about the branch continuous backup configuration
type BackupConfiguration struct {
	// BackupTime time of day/week when we are taking a full backup
	BackupTime *string `json:"backupTime,omitempty"`

	// RetentionPeriod how long are we keeping the backups around for
	RetentionPeriod *int32 `json:"retentionPeriod,omitempty"`
}

// BackupMetadata metadata about a continuous backup
type BackupMetadata struct {
	// BranchID the branchID the branch associated with the backup
	BranchID string `json:"branchID"`

	// Description description of the backup
	Description string `json:"description"`

	// EarliestRestore the earlies point in time available for restoring the branch
	EarliestRestore *time.Time `json:"earliestRestore,omitempty"`

	// Id unique identifier for the backup
	Id string `json:"id"`

	// LatestRestore the latest point in time available for restoring the branch
	LatestRestore *time.Time `json:"latestRestore,omitempty"`
}

// BranchCreationDetails Details required when creating a new branch
type BranchCreationDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description Optional description for the branch purpose or contents (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Mode The mode used to discriminate between types of branches.
	Mode BranchCreationDetailsMode `json:"mode"`

	// Name Human-readable name for the new branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
	union       json.RawMessage
}

// BranchCreationDetailsMode The mode used to discriminate between types of branches.
type BranchCreationDetailsMode string

// BranchCredentials Credentials for accessing a branch, username and password
type BranchCredentials struct {
	// Password Password for accessing the branch database
	Password string `json:"password"`

	// Username Username for accessing the branch database
	Username string `json:"username"`
}

// BranchFromConfiguration defines model for BranchFromConfiguration.
type BranchFromConfiguration struct {
	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration        `json:"configuration"`
	Mode          BranchFromConfigurationMode `json:"mode"`
}

// BranchFromConfigurationMode defines model for BranchFromConfiguration.Mode.
type BranchFromConfigurationMode string

// BranchFromParent defines model for BranchFromParent.
type BranchFromParent struct {
	Mode BranchFromParentMode `json:"mode"`

	// ParentID If present, the branch will inherit the parent branch configuration and data
	ParentID string `json:"parentID"`
}

// BranchFromParentMode defines model for BranchFromParent.Mode.
type BranchFromParentMode string

// BranchListMetadata Metadata about a branch used when listing branches in a project
type BranchListMetadata struct {
	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetadata Detailed metadata about a branch, including its status and configuration
type BranchMetadata struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration `json:"configuration"`

	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero ScaleToZeroConfiguration `json:"scaleToZero"`

	// Status Detailed status information about a branch and its underlying database cluster
	Status BranchStatus `json:"status"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetrics A collection of metrics (cpu, memory, disk,...) for each of the instances of a branch
type BranchMetrics struct {
	End    time.Time      `json:"end"`
	Metric string         `json:"metric"`
	Series []MetricSeries `json:"series"`
	Start  time.Time      `json:"start"`

	// Unit The unit of the metric (percentage, bytes, ms, etc.)
	Unit string `json:"unit"`
}

// BranchMetricsRequest defines model for BranchMetricsRequest.
type BranchMetricsRequest struct {
	// Aggregations List of aggregations to get, this is how the data-points within the interval are aggregated. Each one will generate a separate time-series in the response.
	Aggregations []BranchMetricsRequestAggregations `json:"aggregations"`

	// End End time
	End time.Time `json:"end"`

	// Instances List of instance IDs to query
	Instances []string `json:"instances"`

	// Metric Metric name to query
	Metric BranchMetricsRequestMetric `json:"metric"`

	// Start Start time
	Start time.Time `json:"start"`
}

// BranchMetricsRequestAggregations defines model for BranchMetricsRequest.Aggregations.
type BranchMetricsRequestAggregations string

// BranchMetricsRequestMetric Metric name to query
type BranchMetricsRequestMetric string

// BranchShortMetadata Basic metadata about a branch, used in response to create/update operations
type BranchShortMetadata struct {
	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchStatus Detailed status information about a branch and its underlying database cluster
type BranchStatus struct {
	// InstanceCount Total number of database instances in the cluster
	InstanceCount int `json:"instanceCount"`

	// InstanceReadyCount Number of database instances that are ready and operational
	InstanceReadyCount int `json:"instanceReadyCount"`

	// Instances Details about each individual database instance in the cluster
	Instances []InstanceStatus `json:"instances"`

	// Lifecycle Information about the current lifecycle state of a database cluster
	// Deprecated:
	Lifecycle *ClusterLifecycle `json:"lifecycle,omitempty"`

	// Message Human-readable message explaining the current status
	// Deprecated:
	Message *string `json:"message,omitempty"`

	// Status Status indicator for the branch according to CNPG
	Status string `json:"status"`

	// StatusType Type of status of the branch
	StatusType interface{} `json:"statusType"`
}

// BranchUpdateDetails Details that can be updated for an existing branch
type BranchUpdateDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description New description for the branch (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Hibernate Enabled when the branch should be hibernated, disabled if it needs to be reactivated.
	Hibernate *bool `json:"hibernate,omitempty"`

	// Image PostgreSQL image to use for the database instances
	Image *string `json:"image,omitempty"`

	// InstanceType New instance type for the branch
	InstanceType *string `json:"instanceType,omitempty"`

	// Name New name for the branch
	Name *string `json:"name,omitempty"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Replicas Number of database replicas to scale to
	Replicas *int32 `json:"replicas,omitempty"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// CidrEntry defines model for CidrEntry.
type CidrEntry struct {
	// Cidr CIDR block (e.g., "192.168.0.0/24")
	Cidr string `json:"cidr"`

	// Description Optional label for the CIDR entry
	Description *string `json:"description,omitempty"`
}

// ClusterConfiguration Configuration details for a database cluster backing a branch
type ClusterConfiguration struct {
	// Image PostgreSQL image to use for the database instances
	Image string `json:"image"`

	// InstanceType The instance type according to the xata instance types available
	InstanceType string `json:"instanceType"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Region Geographic region where the cluster will be deployed
	Region string `json:"region"`

	// Replicas Number of replicas in the branch. Every child branch is created with no replicas. This can be updated.
	Replicas int32 `json:"replicas"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// ClusterLifecycle Information about the current lifecycle state of a database cluster
type ClusterLifecycle struct {
	// Phase Current phase within the lifecycle process
	Phase string `json:"phase"`

	// Reason Reason for the current lifecycle state, especially useful for non-ready states
	Reason *string `json:"reason,omitempty"`

	// State Current operational state of the cluster (ready, creating, updating, etc.)
	State interface{} `json:"state"`
}

// CreateGithubAppInstallationRequest defines model for CreateGithubAppInstallationRequest.
type CreateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// CreateGithubRepositoryRequest defines model for CreateGithubRepositoryRequest.
type CreateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// Extension Details of a postgres extension
type Extension struct {
	// Description Extension description
	Description string `json:"description"`

	// Docs Documentation URL
	Docs string `json:"docs"`

	// Name Extension name
	Name string `json:"name"`

	// PreloadRequired is preload required for the extension or not
	PreloadRequired bool `json:"preloadRequired"`

	// Type type of installation
	Type ExtensionType `json:"type"`

	// Version Extension version
	Version string `json:"version"`
}

// ExtensionType type of installation
type ExtensionType string

// GithubInstallation A GitHub App installation associated with an organization
type GithubInstallation struct {
	// CreatedAt Timestamp when the installation was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier of the installation record
	Id string `json:"id"`

	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`

	// Organization Organization ID this installation belongs to
	Organization string `json:"organization"`

	// UpdatedAt Timestamp when the installation was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GithubRepository A mapping between a GitHub repository and a Xata project
type GithubRepository struct {
	// CreatedAt Timestamp when the mapping was created
	CreatedAt time.Time `json:"createdAt"`

	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`

	// Id Unique identifier of the mapping record
	Id string `json:"id"`

	// Project Project ID this mapping is associated with
	Project string `json:"project"`

	// RootBranchId ID of the root Xata branch mapped to this repository
	RootBranchId string `json:"rootBranchId"`

	// UpdatedAt Timestamp when the mapping was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// IPFilteringConfiguration Configuration for IP filtering on project branches
type IPFilteringConfiguration struct {
	Cidr []CidrEntry `json:"cidr"`

	// Enabled Whether IP filtering is enabled
	Enabled bool `json:"enabled"`
}

// Image Details of a postgres image
type Image struct {
	// FullVersion full postgres version
	FullVersion string `json:"fullVersion"`

	// MajorVersion major postgres version
	MajorVersion string `json:"majorVersion"`

	// Name Image name
	Name string `json:"name"`

	// Region region where this instance type is available
	Region *[]string `json:"region,omitempty"`
}

// InstanceStatus Status information about an individual database instance within a cluster
type InstanceStatus struct {
	// Id Unique identifier for the database instance
	Id string `json:"id"`

	// Primary Indicates if this instance is currently the primary (write) instance
	Primary bool `json:"primary"`

	// Status Current operational status of the instance
	Status string `json:"status"`

	// TargetPrimary Indicates if this instance is the target primary during a failover operation
	TargetPrimary bool `json:"targetPrimary"`
}

// MetricSeries The metric series
type MetricSeries struct {
	// Aggregation The aggregation used to generate this time-series
	Aggregation MetricSeriesAggregation `json:"aggregation"`

	// InstanceID ID of the instance
	InstanceID string `json:"instanceID"`
	Values     []struct {
		Timestamp time.Time `json:"timestamp"`
		Value     float32   `json:"value"`
	} `json:"values"`
}

// MetricSeriesAggregation The aggregation used to generate this time-series
type MetricSeriesAggregation string

// OrganizationID defines model for OrganizationID.
type OrganizationID = string

// PostgresConfigDetails Detailed information about PostgreSQL configuration parameters for a branch
type PostgresConfigDetails struct {
	// Parameters Array of PostgreSQL configuration parameters with detailed information
	Parameters []PostgresConfigParameter `json:"parameters"`
}

// PostgresConfigParameter Detailed information about a single PostgreSQL configuration parameter
type PostgresConfigParameter struct {
	// AcceptableRange Information about the acceptable range of values for this parameter
	AcceptableRange *struct {
		// EnumValues List of allowed enum values (if applicable)
		EnumValues *[]string `json:"enumValues,omitempty"`

		// MaxValue Maximum allowed value (if applicable)
		MaxValue *string `json:"maxValue,omitempty"`

		// MinValue Minimum allowed value (if applicable)
		MinValue *string `json:"minValue,omitempty"`
	} `json:"acceptableRange,omitempty"`

	// CurrentValue The current value of this parameter in the branch
	CurrentValue string `json:"currentValue"`

	// DefaultValue The default value for this parameter
	DefaultValue string `json:"defaultValue"`

	// DefaultValueSource The source of the default value
	DefaultValueSource PostgresConfigParameterDefaultValueSource `json:"defaultValueSource"`

	// Description Human-readable description of what the parameter controls
	Description string `json:"description"`

	// DocumentationLink Link to PostgreSQL documentation for this parameter
	DocumentationLink string `json:"documentationLink"`

	// Name The name of the PostgreSQL parameter
	Name string `json:"name"`

	// Recommendation Optional recommendation for this parameter (currently empty)
	Recommendation string `json:"recommendation"`

	// RestartRequired Whether a database restart is required for this parameter change to take effect
	RestartRequired *bool `json:"restartRequired,omitempty"`

	// Section The section/category this parameter belongs to
	Section string `json:"section"`

	// Type The data type of the parameter
	Type PostgresConfigParameterType `json:"type"`
}

// PostgresConfigParameterDefaultValueSource The source of the default value
type PostgresConfigParameterDefaultValueSource string

// PostgresConfigParameterType The data type of the parameter
type PostgresConfigParameterType string

// Project Details of a project including its ID, name, and creation/update timestamps
type Project struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration ProjectConfiguration `json:"configuration"`

	// CreatedAt Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the project
	Id string `json:"id"`

	// Name Human-readable name of the project
	Name string `json:"name"`

	// UpdatedAt Timestamp when the project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectConfiguration Configuration details for a project, including its scale to zero settings
type ProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero ProjectScaleToZeroConfiguration `json:"scaleToZero"`
}

// ProjectLimits Resource limits and constraints for projects within an organization
type ProjectLimits struct {
	// Images List of PostgreSQL image identifiers that can be used for branches
	Images []string `json:"images"`

	// MaxBranches Maximum number of branches allowed per project
	MaxBranches int `json:"maxBranches"`

	// MaxDescriptionLength Maximum character length allowed for project descriptions
	MaxDescriptionLength int `json:"maxDescriptionLength"`

	// MaxInstances Maximum number of database instances allowed per branch
	MaxInstances int `json:"maxInstances"`

	// MinInstances Minimum number of database instances required per branch
	MinInstances int `json:"minInstances"`

	// Regions List of region identifiers where branches can be deployed
	Regions []string `json:"regions"`
}

// ProjectScaleToZeroConfiguration Whether the project branches are configured to scale down to zero when not in use
type ProjectScaleToZeroConfiguration struct {
	// BaseBranches Configuration for scaling branches to zero when not in use
	BaseBranches ScaleToZeroConfiguration `json:"baseBranches"`

	// ChildBranches Configuration for scaling branches to zero when not in use
	ChildBranches ScaleToZeroConfiguration `json:"childBranches"`
}

// RestoreDetails Metadata about a backup, used in request to create a restore. If configuration is not provided, the branch will inherit the source branch configuration.
type RestoreDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration *ClusterConfiguration `json:"configuration,omitempty"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// RotateCredentialsRequest Request to rotate credentials for a branch database user
type RotateCredentialsRequest struct {
	// Username Database username to rotate credentials for
	Username string `json:"username"`
}

// ScaleToZeroConfiguration Configuration for scaling branches to zero when not in use
type ScaleToZeroConfiguration struct {
	// Enabled Whether scale to zero is enabled
	Enabled bool `json:"enabled"`

	// InactivityPeriodMinutes Duration in minutes after which branches will be hibernated if not accessed
	InactivityPeriodMinutes int `json:"inactivityPeriodMinutes"`
}

// UpdateGithubAppInstallationRequest defines model for UpdateGithubAppInstallationRequest.
type UpdateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// UpdateGithubRepositoryRequest defines model for UpdateGithubRepositoryRequest.
type UpdateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// UpdateProjectConfiguration Partial configuration update for a project
type UpdateProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero *ProjectScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// AuthorizationError defines model for AuthorizationError.
type AuthorizationError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the authentication or authorization issue
	Message string `json:"message"`
}

// GenericError defines model for GenericError.
type GenericError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// PreconditionFailedError defines model for PreconditionFailedError.
type PreconditionFailedError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the precondition failure
	Message string `json:"message"`
}

// ListExtensionsParams defines parameters for ListExtensions.
type ListExtensionsParams struct {
	// Image Image for which we list extensions
	Image string `form:"image" json:"image"`

	// Region Region to list extensions for image in
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Region Region to check image availability for organization
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListInstanceTypesParams defines parameters for ListInstanceTypes.
type ListInstanceTypesParams struct {
	// Region Region to check instance type availability for
	Region string `form:"region" json:"region"`
}

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration *ProjectConfiguration `json:"configuration,omitempty"`

	// Name Human-readable name for the new project
	Name string `json:"name"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	// Configuration Partial configuration update for a project
	Configuration *UpdateProjectConfiguration `json:"configuration,omitempty"`

	// Name New name for the project
	Name *string `json:"name,omitempty"`
}

// GetBranchCredentialsParams defines parameters for GetBranchCredentials.
type GetBranchCredentialsParams struct {
	// Username Username that the credentials requested for
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// CreateGithubAppInstallationJSONRequestBody defines body for CreateGithubAppInstallation for application/json ContentType.
type CreateGithubAppInstallationJSONRequestBody = CreateGithubAppInstallationRequest

// UpdateGithubAppInstallationJSONRequestBody defines body for UpdateGithubAppInstallation for application/json ContentType.
type UpdateGithubAppInstallationJSONRequestBody = UpdateGithubAppInstallationRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = BranchCreationDetails

// UpdateBranchJSONRequestBody defines body for UpdateBranch for application/json ContentType.
type UpdateBranchJSONRequestBody = BranchUpdateDetails

// RotateBranchCredentialsJSONRequestBody defines body for RotateBranchCredentials for application/json ContentType.
type RotateBranchCredentialsJSONRequestBody = RotateCredentialsRequest

// CreateGithubRepositoryJSONRequestBody defines body for CreateGithubRepository for application/json ContentType.
type CreateGithubRepositoryJSONRequestBody = CreateGithubRepositoryRequest

// UpdateGithubRepositoryJSONRequestBody defines body for UpdateGithubRepository for application/json ContentType.
type UpdateGithubRepositoryJSONRequestBody = UpdateGithubRepositoryRequest

// BranchMetricsJSONRequestBody defines body for BranchMetrics for application/json ContentType.
type BranchMetricsJSONRequestBody = BranchMetricsRequest

// RestoreFromBackupJSONRequestBody defines body for RestoreFromBackup for application/json ContentType.
type RestoreFromBackupJSONRequestBody = RestoreDetails

// AsBranchFromParent returns the union data inside the BranchCreationDetails as a BranchFromParent
func (t BranchCreationDetails) AsBranchFromParent() (BranchFromParent, error) {
	var body BranchFromParent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromParent overwrites any union data inside the BranchCreationDetails as the provided BranchFromParent
func (t *BranchCreationDetails) FromBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromParent performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromParent
func (t *BranchCreationDetails) MergeBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBranchFromConfiguration returns the union data inside the BranchCreationDetails as a BranchFromConfiguration
func (t BranchCreationDetails) AsBranchFromConfiguration() (BranchFromConfiguration, error) {
	var body BranchFromConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromConfiguration overwrites any union data inside the BranchCreationDetails as the provided BranchFromConfiguration
func (t *BranchCreationDetails) FromBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromConfiguration performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromConfiguration
func (t *BranchCreationDetails) MergeBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BranchCreationDetails) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BranchCreationDetails) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "custom":
		return t.AsBranchFromConfiguration()
	case "inherit":
		return t.AsBranchFromParent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BranchCreationDetails) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.BackupConfiguration != nil {
		object["backupConfiguration"], err = json.Marshal(t.BackupConfiguration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backupConfiguration': %w", err)
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	object["mode"], err = json.Marshal(t.Mode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mode': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.ScaleToZero != nil {
		object["scaleToZero"], err = json.Marshal(t.ScaleToZero)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scaleToZero': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *BranchCreationDetails) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backupConfiguration"]; found {
		err = json.Unmarshal(raw, &t.BackupConfiguration)
		if err != nil {
			return fmt.Errorf("error reading 'backupConfiguration': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &t.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["scaleToZero"]; found {
		err = json.Unmarshal(raw, &t.ScaleToZero)
		if err != nil {
			return fmt.Errorf("error reading 'scaleToZero': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get available extensions for image
	// (GET /organizations/{organizationID}/extensions)
	ListExtensions(ctx echo.Context, organizationID OrganizationID, params ListExtensionsParams) error
	// List GitHub App installations for organization
	// (GET /organizations/{organizationID}/githubapp/installations)
	ListGithubAppInstallations(ctx echo.Context, organizationID OrganizationID) error
	// Create GitHub App installation
	// (POST /organizations/{organizationID}/githubapp/installations)
	CreateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID) error
	// Update GitHub App installation
	// (PUT /organizations/{organizationID}/githubapp/installations/{githubInstallationID})
	UpdateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID, githubInstallationID string) error
	// Get available images
	// (GET /organizations/{organizationID}/images)
	ListImages(ctx echo.Context, organizationID OrganizationID, params ListImagesParams) error
	// Get available instance types
	// (GET /organizations/{organizationID}/instanceTypes)
	ListInstanceTypes(ctx echo.Context, organizationID OrganizationID, params ListInstanceTypesParams) error
	// List all projects
	// (GET /organizations/{organizationID}/projects)
	ListProjects(ctx echo.Context, organizationID OrganizationID) error
	// Create a new project
	// (POST /organizations/{organizationID}/projects)
	CreateProject(ctx echo.Context, organizationID OrganizationID) error
	// Get project resource limits
	// (GET /organizations/{organizationID}/projects/limits)
	GetDefaultProjectLimits(ctx echo.Context, organizationID OrganizationID) error
	// Delete a project
	// (DELETE /organizations/{organizationID}/projects/{projectID})
	DeleteProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project details
	// (GET /organizations/{organizationID}/projects/{projectID})
	GetProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Update project details
	// (PATCH /organizations/{organizationID}/projects/{projectID})
	UpdateProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// List project backups
	// (GET /organizations/{organizationID}/projects/{projectID}/backups)
	ListBackups(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project backup by ID
	// (GET /organizations/{organizationID}/projects/{projectID}/backups/{backupID})
	GetBackup(ctx echo.Context, organizationID OrganizationID, projectID string, backupID string) error
	// List all branches
	// (GET /organizations/{organizationID}/projects/{projectID}/branches)
	ListBranches(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Create a new branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches)
	CreateBranch(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Delete a branch
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DeleteBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get branch details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DescribeBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update branch details
	// (PATCH /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	UpdateBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch credentials
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/credentials)
	GetBranchCredentials(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string, params GetBranchCredentialsParams) error
	// Rotate branch credentials
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/credentials/rotate)
	RotateBranchCredentials(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Delete GitHub repository mapping
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	DeleteGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get GitHub repository for branch
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	GetGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create GitHub repository mapping
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	CreateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update GitHub repository mapping
	// (PUT /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	UpdateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch metrics
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/metrics)
	BranchMetrics(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get PostgreSQL configuration details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/postgres-config)
	GetBranchPostgresConfig(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create a new branch from a backup of another branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/restore)
	RestoreFromBackup(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get available regions
	// (GET /organizations/{organizationID}/regions)
	ListRegions(ctx echo.Context, organizationID OrganizationID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListExtensions converts echo context to params.
func (w *ServerInterfaceWrapper) ListExtensions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExtensionsParams
	// ------------- Required query parameter "image" -------------

	err = runtime.BindQueryParameter("form", true, true, "image", ctx.QueryParams(), &params.Image)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter image: %s", err))
	}

	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListExtensions(ctx, organizationID, params)
	return err
}

// ListGithubAppInstallations converts echo context to params.
func (w *ServerInterfaceWrapper) ListGithubAppInstallations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGithubAppInstallations(ctx, organizationID)
	return err
}

// CreateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubAppInstallation(ctx, organizationID)
	return err
}

// UpdateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "githubInstallationID" -------------
	var githubInstallationID string

	err = runtime.BindStyledParameterWithOptions("simple", "githubInstallationID", ctx.Param("githubInstallationID"), &githubInstallationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter githubInstallationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubAppInstallation(ctx, organizationID, githubInstallationID)
	return err
}

// ListImages converts echo context to params.
func (w *ServerInterfaceWrapper) ListImages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListImagesParams
	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListImages(ctx, organizationID, params)
	return err
}

// ListInstanceTypes converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceTypes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstanceTypesParams
	// ------------- Required query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, true, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceTypes(ctx, organizationID, params)
	return err
}

// ListProjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjects(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjects(ctx, organizationID)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProject(ctx, organizationID)
	return err
}

// GetDefaultProjectLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetDefaultProjectLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDefaultProjectLimits(ctx, organizationID)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProject(ctx, organizationID, projectID)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, organizationID, projectID)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProject(ctx, organizationID, projectID)
	return err
}

// ListBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackups(ctx, organizationID, projectID)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "backupID" -------------
	var backupID string

	err = runtime.BindStyledParameterWithOptions("simple", "backupID", ctx.Param("backupID"), &backupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, organizationID, projectID, backupID)
	return err
}

// ListBranches converts echo context to params.
func (w *ServerInterfaceWrapper) ListBranches(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBranches(ctx, organizationID, projectID)
	return err
}

// CreateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBranch(ctx, organizationID, projectID)
	return err
}

// DeleteBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBranch(ctx, organizationID, projectID, branchID)
	return err
}

// DescribeBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DescribeBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DescribeBranch(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBranch(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"credentials:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBranchCredentialsParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchCredentials(ctx, organizationID, projectID, branchID, params)
	return err
}

// RotateBranchCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) RotateBranchCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"credentials:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RotateBranchCredentials(ctx, organizationID, projectID, branchID)
	return err
}

// DeleteGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// GetGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) GetGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// CreateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// BranchMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) BranchMetrics(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"metrics:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BranchMetrics(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchPostgresConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchPostgresConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchPostgresConfig(ctx, organizationID, projectID, branchID)
	return err
}

// RestoreFromBackup converts echo context to params.
func (w *ServerInterfaceWrapper) RestoreFromBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestoreFromBackup(ctx, organizationID, projectID, branchID)
	return err
}

// ListRegions converts echo context to params.
func (w *ServerInterfaceWrapper) ListRegions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRegions(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/organizations/:organizationID/extensions", wrapper.ListExtensions)
	router.GET(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.ListGithubAppInstallations)
	router.POST(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.CreateGithubAppInstallation)
	router.PUT(baseURL+"/organizations/:organizationID/githubapp/installations/:githubInstallationID", wrapper.UpdateGithubAppInstallation)
	router.GET(baseURL+"/organizations/:organizationID/images", wrapper.ListImages)
	router.GET(baseURL+"/organizations/:organizationID/instanceTypes", wrapper.ListInstanceTypes)
	router.GET(baseURL+"/organizations/:organizationID/projects", wrapper.ListProjects)
	router.POST(baseURL+"/organizations/:organizationID/projects", wrapper.CreateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/limits", wrapper.GetDefaultProjectLimits)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.DeleteProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.GetProject)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.UpdateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups", wrapper.ListBackups)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups/:backupID", wrapper.GetBackup)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.ListBranches)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.CreateBranch)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DeleteBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DescribeBranch)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.UpdateBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials", wrapper.GetBranchCredentials)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials/rotate", wrapper.RotateBranchCredentials)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.DeleteGithubRepository)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.GetGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.CreateGithubRepository)
	router.PUT(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.UpdateGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/metrics", wrapper.BranchMetrics)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/postgres-config", wrapper.GetBranchPostgresConfig)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/restore", wrapper.RestoreFromBackup)
	router.GET(baseURL+"/organizations/:organizationID/regions", wrapper.ListRegions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PbuNX/V8Hw3xdJS1+SzXb+9TsndrKeyWZd22m3zfrJQCQkoaEAFgDtqKmfz/4M",
	"rgRJgKRk+bbRm12HIoED4Jwfzg0H35KMLkpKEBE8OfiWMMRLSjhS/zisxJwy/B8oMCXHjFEmn2aUCESE",
	"/BOWZYEz9fPevzgl8hnP5mgB5V8loyViAuvGcC7/myOeMVzKL5KDRLUJcI6IwFOMGJhSBgSD2RdMZgCS",
	"HORoUs1mmMySNBHLEiUHCRdM/vsmTRaIczhD3XZ/qhaQ7DAEczgpEECqG/M2QF/LAmIiexBzBGAl5rJ/",
	"PQxAmXrihg0w5xXq9n6TJgz9u8IM5cnBJ0fKpXuRTv6FMpHcyDdDo7YzDa7niAxSMYW44HLM7xBBDGe/",
	"19XY/GybCTPdulmXY1tQLszzjJIcyy/UJJ8y5B68hbhA+e91vktvpIrJKnYPzN7qVg57joDsAnEBMAeE",
	"CrBAQvWsp1TN4muYfanKN5RM8axiUHfRHv4RElJYAJzQSqiGJwySbC7XWGBS0YqDiWpIPvFaSltrpl+6",
	"wIvAHAu8QIBOQQ6Xe9cIfdEDu0YAMgQE1CsIplVRmL5k61AIxOTX//Pst9/++N9P+zt/vnx+8Gz/0/7O",
	"Xy7/+0L/7+Wn/Z0f5ONP+zs/Xqpnz/8QWn+GJCNiSk4Rw9Tw1xRWhUgOXraXYU6vQUElUQxJMr8gVFoe",
	"0ARyABmtSC6XI0mTKWULKJKDBBPxw8skTRbwK15Ui+Tghx/TZIGJ/sdLRxgmAs0QU0vW5Io0+bqDvmZF",
	"lUv2EaxC8ol8nxFY6Cc3qVncn5GAORSwO+UL84tZWNhdz+4KqoU/OQqsn2OLkyOfRyDnNMNQoBxcYzH3",
	"5ie0BI022114/5Kc0t8SgqzAiIszxAVlKEyweQmUFBMBMAGKC+EVxIWS9KmWNEGZW1o1Kn85cyjQjvwu",
	"REUIpSqC/12hDkz1jqaAYmgs+pW7GkoLsHCepDUzNNetC2Jp8lq9+oYhBQwGUOJIY7vSIJCpz5T8E3Rd",
	"051j+e0CEyj0VrKApZRBtatUXNBFcpD8v71aH9szyLenyXnL6OJNC7AwmSOGxfCHp5DJXevGScjyA5S4",
	"lixojuRjStAv0+Tg07fkDwxNV2hw7AdN0m8uw2jbwfbexgOfDEnlL+oPWABfPB1HaxAoK1ZSjoDWCyTK",
	"cvBsAb+CH/dBNocMZgIx/lyD4ntEZmKeHPy430D4T3DnP4c7/5Tw/af67x1w+ccgmKtl6BB7MUdA/gIq",
	"jnIgKPB4CIEJEtcIESAb4xJiNPmI7yZpgoiE50+OQ1LLY5eB3glcDOsR8iU3Uw3O7rTHM1igC/pPxOjQ",
	"Gp7Xr7YWsiXDikYzUb0yq4AKhuTV+1ENBGYZ4lyLqh5MKmeaqZFK/auEnF9Tlnc2FvdDp49T80urA4+7",
	"5B42gTwIwLb3brsfLV1rtNuaSddJWo/jMrRpd7foiDR31N1sFTF+U1RcINaRYysTlpWjDNxWT+V3aYuG",
	"OMt4aNYZR5sEK00hISpVGyFl42QqFV6OiEj9BbvGRQFMi1oZVy146mpNvzYHpF40cvSOmvjA32Mu4urW",
	"z211y5CloEhtdAXmap+zsCO3canaU8NAIXznx0SCSUBw/j5HYo4aOIxNkwzN5BSIORSAV2VJmbAqH6/n",
	"Y0JpgaDiHLUFo/xQBCAVLxAXcFHqMfjLATkwH45WmFbfaqwmGN1pxuplH+N6WRSXx+N8g8xkNW6vKTKt",
	"NPkay4dyaTmAIEcMX6HcwS+RFhOVjHCNFZTJB5Isazh0CakmBc4OFSKO4ipYFPSaA/2dgVKl7Cs2b/hh",
	"gsylubHb1TtEZwyWc5xZhr2eI2kNNhg6R2VBl4rFuuhf5uuxbQG5AObrW2jIZlOopccnyQ28NeVpW7Lj",
	"gBMHG61JoxwswqiTAkykASnhBgsOuICi4goUx9jwm9Aq7xW/NrF9ZpQQlMl/nes178660RhA/SrQ/NHR",
	"MjCvsWBQJLfwu4XfJwi/G7Fa0kRj0yDKKJLO9btPCPvN6ALw0oatoX2iOeG9uwbDWYC5DkFGi8LgFp3K",
	"vUO+CJ5lZZWCBVpQtkylyfwl3d3dfa4EFMFsbuUCEy4gybTtDGtha+4giCjpHwdImgT5fpe7ELOxAIEW",
	"g/yhR32uP6pdqpAxuDRcxsR4wiqCRdi/IH+xM6LJB89KxDJEBJyhFEyWAvEULHgKkMh2nw+yk6YsVRPn",
	"ZsSN35AyuNxnOhjQNcngbMbQDOpYTWdE0qZRy+m9BQQFM6RsL417c3qthisVjR3lgdQIhInhC4HYFSyU",
	"r9w2hPJdcKyYhyBtuc0QQQwKBCDgqITqTzn9O3qkwLRmQx+7SVqvvLUn4dVMe5ES5VMP2pXtlTcM2Qqz",
	"kByYtR/p6rXMH59D+wo4OVJz+O8KsaU/ikFSa3Ho2JaSz9RW5zXsDP2yUpwjBVg7Tr80AId/hpnAV6j1",
	"EOeF2rKQuKbsy2dMZkwDj32C7ANMS/5Z7rj272uGhfy2gAKRbGl/s/+0P4s5o9VsXlbCvuE9sS9dw+Iz",
	"X5Lss5l6hlyY8HMBZ/pxaKGdSDcn61w+XmVxx8ljzQBpU6bionk+p6zHY/AacpzFNXjlOMCkjgUKahS+",
	"Pb3TACnmhoi061DaKrNbZXarzP6ufQk90OOU6ojjwHgEMNEEK5dp03EJSa58BxXJESuWEgpyhxnahu7A",
	"jgXJN7QioZmkAhaAVIuJZlDXXq1aGi2g7sDF0f0w+os0EVhIzkw+uNZ6GmnH3Gs4P0MwX0bI/dBHqPJO",
	"SI1HCu9SzZbDY1jECN/vJ1y3tQL5fCifQynwmOT4CueVxMP2SLq9jdK3T8zntUVmx9VWh+LL4fSeAk9R",
	"tswKNNJ38969387rKRnKlCQayOpF20iOT1YxhZnOdLMjO68WC8iWFlrNeLz3AhpKUArPrfDlEuxoe/uQ",
	"wEiZct4JCt58OH3nEfGmQV2LljgRF+pxRyCXpdpvmo25nccqmOcXhxcfzz9f/OP0+PPHD+enx29O3p4c",
	"HyVp45efjg/fX/z0j9bTi7PDD+cnxx8uWs/fHn58337208nr47MPhxfHR8llQC3Ts+yNJ20BTlCsfWGJ",
	"A+ZHBbaDqQtK6jNIwARZ0NfqEgHoayO+kzxQwP4Duu6L1Ufj8garbhWVn+MJYgQKFDK4lBejs4XyOa2K",
	"XE6n+zhXTgj9Op4CLABBKFcm1UTBrTRmlIUZ1BHwIpjld0q5mDF0/tf3QL0hm6t4HaHvQnyfGRgWJzn3",
	"Dlflt2vrhbKlRgJBjzaoB8YbbHIKGVwgubzKB5Dr1EFYnDZYsl+nTg7ZBAsmEc+bvGaYtXT9OEo7UFSL",
	"WslQQWH+Hk8YtN6dsC3tdYi+CkS4ckzITbawH8sFNA2uZGQb+5KP2u/ty7Iz5X4DgvZm+71qbfadnXtj",
	"XlPKgnz+2siV/l3uve/wa/BshmdQuaae95L/8sf9ERmKN2nyBufsmAi2DCQz4JwFkklOjs7ApKDZF/AM",
	"7c52U/Bb8uIvL3df/Pn/7+7v7u+9fPVb8nx9O6+AE1Q4HlSdIUXekPatqA3tC8E4UXdYDXHIzTahtoSO",
	"uqxiWH76TFd/fjjsuvA8vBq7GlqI7OYrFLD5Dq9TELfQtAloWt28tbylfKwT1GvkjoE+h3jY36d3wfEV",
	"YkuQzXGReya1sVd18i+h7utdcDGXPzc0pd1bIuf9Ql7DRFdy6ZnhDVnyJrYHSN77Rs6QpXLSsct9y8TZ",
	"S0pxRzoeM2icl3PIA7NnDQr1s+/Xr3spGTUxqQBLQR5i2TP1vJa8MOUpQLxEGYZFsZSINq00hhOqzbSl",
	"fi1qXPUMxzPG61nyBeaZ6iB1+cepZlP1l43cWANIvWrdMzp4Z19Wf84YzM3f5Auh1zoyEbDY2uZ2PSEh",
	"P7Tyj+tlCzKWEr53WMyryWFZKpO8KNSgo+Eg7L10EnBtvsPip2oCDssS+K8ClQfuC9GfXyXDYtPsbGgM",
	"Z6ikHAvKllHyZ60XQ05QMwTmXlqP+EBXoQEc2z0gbjQq8bR7Yb1pdAS0V9Nx/fjWXVBfoqHg7xHNqgUi",
	"Qq/mx7P3422RumfjpOzu83qvO3Oz124Cc7sf1sn/FhrcfAAl+CJo1ImgziKM+8LnM09qGzNdVDNMdEJ0",
	"VYQDSleI8YG5t68MaZVmpppLVX+s1qg7b6bVyzVPBGkp8mEglAQQk/D2UR4oF2QGiTlS2Q0xrRToaXS1",
	"TrhnXBzGT1WwvTGU6Zz0sEZ8Z2CYJo3569ou3q9AHatSCXBePxNUUDLj2ua8ZciiswAbCly05rA16FhE",
	"I4Sk7U0gxLzmDJA7ywFBF+2lKg7Br9JYiSVXr8a7ttN12PYuN6wVhcIOIy4Pdrq6Bqj+wXGpbQrzNmwE",
	"dURKhdbRQ0J2cmQJlO/pdTMGhuxGH+RRvdYTdHtx8Nd0Q5IQWOp6SluzsIpcnJy+xYVAsuOVnBFygz05",
	"BVP7MZBGsVlIewahKxnGeTMqCFQ7gYJ5NwOZvw3aMAfIJbq19//WbNcvRp03J2FHSlgjs9ZdcyamVVH8",
	"LaYRqJPKroGoViDNzH9RFm1G/TqqnbBqpoYZVcti7oSWD8HuOs7xg5tuHccKC0xO9N8vBvOuIqfR/NlI",
	"G1McXMVmkDEeR+sEsUl/zNNYuTAeyF4p66PTgRevs2MA5mCwQoUA8uIFDG15JzpGKLl02lorzK1ZXSxN",
	"cQLVCHimUqueh6jxczL8hrzPg/p3LJIZs7brYGKAiHAI03+xw1uQzZA4XW+SZOO6ATdDecVMxQGIC3ol",
	"90g7gMhkWXsdc8CvscjmtuaEzafp9jIMZGrbcIFN77PGcD1XwrmbMcXhsQh+R5Aa2bHhY7M6xdBlnUaT",
	"SMOfey+4w7cu4VNNkZfq6ZloYxI67TiDCU9HY9jnChZVK5e4OT5hFYTxGcKqTc+rq7NaOktct2w/CQFd",
	"L3Z642+kHiZuYKEmfetCz1wd161DuZ93/vfg8k8ez7c+aw9c2p0UlngnozmaIbKDvgoGdwScqXm8ggXO",
	"lVsuqWFSDei0EQoYiLOrxMc2po919EeDK2Uj8NCOJzC4bHn3o70o8zgPUDo2eaY5GS4gMsgJ3ghCSx5r",
	"dpVZhoBjMivQiInookSWoVJIreEMkpD6FfZq158BJr+Ty6AZ22ywmPd0KpHkb06+I9ntRUGvUQ7ku7bp",
	"Z3gKTEWiSYGer5anDb/+zYp/K1NbRxVcj6qzQF9dPRGTWJM6KLJqk6GgrVEXIh1deH563Qmdtma/GRQK",
	"R2tVSZ2eLswbpovgCve2ek4rlkXa5uo3uyU0evI2Hatve3Gczy3H28jwcyuhrJVsfD2H7qC6mb+MEsFo",
	"wSOO29pF+x6TLyGGJl/k1uoJZ+OrkdMZNibkBPoJyF4nva0xlNHFApEcDsTomy8GaAXPaoUWLUqxfB7u",
	"T6Xox73NVm+Dfh6H+gZg3nZAN/rP5gqABAUCfkEATafadg8oxDplPsKG+sc9qZPOKFu2u+n364lofF6d",
	"E7BO7wZjedztdmqskt+mBYXy/yoSal9Lk7w+dmZHdTnSqS10zLPp227IfVBgW/AT4vcOL9XzHNzvYu6q",
	"pplvXB7NE9EnR6li9lQfijali+zJCqe1BU9WjE/gMxR2zxqv5H+0I7g7t7k1ZGtv1e3PL/S0tZqrzh/+",
	"/WTbD5dCCS7sSslBZlSdk/omyQz8BzEKOBICk1mXC3HpfIKDmdox9+FqyWhmxKPrDw0dVjXtvccLLHgo",
	"f8Ds5YV6wZYu4IJBdf5QTqKZQncYcShipfx84zJ7dJpVLSGtzF9utg/PjdqjPRrT6tAocO1ueDsjPjVF",
	"5IyzzUT3FvDra9tdVO+sz1a4KjNWbywR82XSENXzYeuDTvBhAb8e1UTYul4xylzCMSjUm44ubyV9BYon",
	"ftnEH7sUm2YaGB8MjTdJPomfnOjOReDchz+dTg0OHUzpttY4EQE7SrRPJyZ9dBqLoJdOp+YME9ppbjyh",
	"2pXcI1PG1+xLkvY7OzYzMuXlrQ2L0pnutlGttNkMwCQZsKYt7S22aM1+hM/TxMmuL5g9SBdFzt6Dc+2A",
	"jTpyZPcn7WfTW0ZOr4nbN9TeSaiqFFlxFDiLwJEPJutmIat0wNs31FqYBnXtTkIzbCpnRr1K3dpc6mCF",
	"f8ZWl9J1R2xVFRrV6C44mbY8IKbgbsnoFc5R3l+kzGxjoSJlu3d4RmQjJXHu6YjtBo/G3lklxXVzcs6o",
	"gAJ5lRS91La2xuN4kKmPJCs26y+2Sxeq6osdJooXRTzyv7PVBMKdja+KGBLI8VjXDVnLJWyUyRsLaoMB",
	"56Zu3RtxltazOmeExVLXi/4Zk0rY3diUjf5hv523e+QwgoCF/gLAqcrPnuNsXg/KpmvXp54AnqrR6VPR",
	"PlWxDMWa/BixobXRJ92edtaoP4YnmTWqBzDOijyFTIplaxMynoqGMflEzMRAEXxMplQH4rSCd2pNu8PT",
	"Ey9z8iB5sbu/u69y60pEYImTg+QH9UidW5yrUe/5ViDf+0YbMa2bvfrYRrAwjKlwo0tqC4bRlYr1ulrb",
	"3qkPqSsrNbA2CV05a0/UQ9ap3PxnKLgPqD4lcKiSoSaA4Xdr3TUqd36KJXYszMkH+djvRhnORgmf4Ssk",
	"tWIX65airDT143pG0kac7NPo7LJGp1KPmqPsS/tEkZ5DXGCxNJsMlo3KlbNemYOEtkOQtXzpbba+NKKP",
	"E1uRzJubNJw9IydTg/M10hOO/NlQBNqKO4bC+jhIjLDO3tld5ZmZqFaXih67nJH+6+pi0Q4v0+bdNC/3",
	"929xHUefxLjQaS0hRibsjQBYGfi2uZEx0jqvfigq6hE35oYNa5n6h7cadfRVNkFMniQ1r/Rchqh3c77X",
	"uHhGffRi+KPADUI3afLjr7+GnLjoa4kyqTi4F51iMvyyDmFUDIulkvKvqkTRJyl8B6pW06VkIa4rHqgj",
	"aCIMgY5dVd7KTGKGQ2+5HqO05LqfGonAL3V5o5t0ENT1xgvLcs/XH4JeHiLXNqKycHucfyxWV4wop1C8",
	"wdAdGTVyt/vpgnNQVdsMUN8vAG8WkwaW2cFSbF3GAlHgVMWojB3XzyqgFCX2dw47RoENQo+am15xbbG0",
	"haH6m+TSnEYOXnKgMgf17SMxQ8ami3c1r3757Tmi91QFWNlYr2m+XEl2e91Pw+cYb5oiZraNFpq82BhF",
	"IZnvCq3/uzsJzStlv0+rolg+hNS+2v/L6v3dt4ahaz+25FyzQUwE43LtKSn1p421qTUJ8MyXjR2e0RLl",
	"z2+hX+x9m3V45eToJqp2QAsdWWygyitchaZYWfy8UWtoAK+6gNTj/XmCgJSOptFMVPhgYIDi0KquZPHd",
	"EVaO8N6Nwsr9h8RKWznr4bHy1Tr9PVWA1bxzxwA7UY7TEYAay8YY4YEz/oU7dbd5fcQVPs+7FjTdTmyM",
	"eKM+NeWb8H1pDwy6tS8rRmBIS38Ujq0YE96RU0sfSxw0HzVRq9iNhriuI2vru2r7ruqcq463qoF1WnZX",
	"9EL5dYHWxLZmfa27xbhuX7fAusbQv6MwQgf+RhEbQ74VNczNutPinBsCxCb3DAJjs785rVixPAvWcCoZ",
	"zpBKXJNv1Yn6rZn1+bHOBKZVoxqdPZcXPULdaDN6lBouQjcsLyhb6npjPdlxtz6AHSh9pSqd/UyJmA/P",
	"4UK+ZgLF717rcr+6Upqb2FWm8SorQyeB6+zBqzenH/lwpNxMtW5Oz3Dqc0XjEp3OeNc+Ran5e6W9NVLx",
	"cLvHxvfYxpSN2Gvt+2p1VtxzbRr40HZr79+sD3yQ2VAO+cpbaru9nv1U2ONh3sUHKFe5WWAOub0eQdBw",
	"WMhN5aa2WjUMR/+U0cVTDg/FucJtZTa3VkNAYwezt7KMPtFrEnAGT/B6kdFBADp0nBXiqu8JdQbDQ77o",
	"xeBmTPzHnTUakt5d4FKUTEa2gJjYM+guQbNO21bKik4G5rE40WmdxrUZ5Vl71P08cvx0QkZ3cO5uvYvb",
	"oyfZRiUK33PoyiFRF09sFS/f7eoOFH4nCNIXeYLt1e5XWhwA6NDOQi7dCurKXhE5+ma1lraPwD/SzlrH",
	"40YchxuhyozuoRca/SONpspyfaIotcaHPnhrT1OZszhdYHyHxJGmqHlgcFMQqev1aLmoR/q0FJ8RcGBm",
	"LQAKRyusd1PlWGezfudNd6vH0QIH7GBWkLVv5i8Xmi1QyGg+RWwBiS5AoN/hfsTWHcZamjPklof9HC+3",
	"y3ti0FADrHJgi6RDffleBgmhQh0vJTklqCsLR4qijSoJRm+x8FJj36MM4tr5F9SsTphQt9a3dKe9ihfC",
	"bGyhmpb8yUQwH82+qxm6cX4hCAHjnOh+AXclZ7J1XeYtJMEnRyN2xLy3UlIcF4bth9BOtxVtdSDNzP7d",
	"Cvf+fWrctvSDHdoTTX14LCa/r0WYqY0a/VBk83guldZ4vWoxcZlO5ZrNAeS6SpAt2CHZMpZmtZVndVOR",
	"mouNS/O9OxV6zuyNv8etz5ewht9g/8H8BrYIzxa7VlR6TBbWSPzqWj/rBUd8C2hPlxkYDJgsIIEzL0hi",
	"yibwlYIi5ptAcoFpNRzdeG1I3KpCckL9WXxMalGoekWArdq84GnH3lqMibNotnB36g+FWyxFq0Vbesjc",
	"ot0awZkWfGzmoKABiA3C4d43/Ucwfb+JjDNdl601slG4qF/VBugqoPgOGUzcQuKdQuJ4osxKdjW7AC2W",
	"sx6N0doG0i4eXtRDXHh4u4W/NQ1VX/A3CYEbQcBoYcERKTSdrFQfxFZKnmm3FIRGP7zUTNZITRjJhJZ0",
	"+owtoRlRM717cL5jUFWL4GY/nvrzKLTMKK+6xB5TJmsDeT2aPySnjNc545Xq4jmGIc7f6pxx0NXz1Z8P",
	"5BVntWBbVxEcmQ/kqvrF8WgXvG6VsrRHgaUcAZ4xKCQzMpAjhq/sc/8UZwlV0X1z1XIkOei1u9XiOwYq",
	"L6PJXkJNHolncRhG3pgq47ZO5T1nBmkizueUiT69z96m/UiShNY7o/ni5fBHpwxllOjr59+qKN9DQtlw",
	"YlJd9TKEZp5aqBdwzaykkFq4903/dbvsCSOwvckTkinXS4vYwmOLascuD2Ea66UeyNOwTLX5NI0Qhm2z",
	"NNbDIJek0Y8/m8vRqHFigykabfDxrUh9A18qBYjo60aAZrfUXjvQrNnchh9J12QLQI8TgJy/0Lt+407h",
	"aH/DCtsIXW2bXrJJA/IdEq7Qdic427Qgh5NLmkV7mykmXUyKZpikfpX1FChMNdmzsChoFsEmTckWmR4l",
	"MvXlxayPRXdlvGpWWsl03X8Mpus2T2U9tc+kqYwDwo7xucGYhGd87nmXFKi67loz7AZKrbvFvdzBvvuF",
	"q03izKbQogtZ7lIIezDZvxPCIIuuch4pYuHuhHhYjclf+ABKvGldq+Gh8laBGo0dHm8EtagzF6c3N980",
	"pDGAIneEE3v6fhMVRwo6/C8Yns0Q4wB6NOpbUepbSlHw6pVdcGGOiPqSYqIANS9dYdgRJ2QP+enbQVx3",
	"cp2V56yrzOmrZLbY9nCaUPQyn1Hq0KtgsKnDcJhggZ9uecSHwqCgEqMX7EEgqK4XW18p0+c8PzIOc69Y",
	"qXcXTbz+dCxoqNtrX5Hzu67x2muM3o9dd9+O7rMuixg/9xY9NnE0MSqJ8WqpfbdNeO0ICn6Fwl3pZprl",
	"g1dNbAof3iGxBYffETjcJqXK8vSoSs8ev7RTn2w7YzKf4jxsfQ3fcU2jd0gEhLy+cXojl1wMglH/dRZb",
	"3HiquHG3N3h072N8kMs7GjDVQZ+A3rS9wGODpZTW0JtWvfNiDfgKXxu6ha/vHb76r5N9kPs0VoavJ32n",
	"xmM7nL0GfAUvyfDW6Y4iYgskGM64795uYp5LIlGvbX3F9xs1N/P+QFDSXPsAjpifGrfLb0EjABpGzEZF",
	"uhZO1jou5tTO+IadzVL0ZwzxHZ1u5MXG18iaVKGqiqkjKae64fO/vm9lMtUw0mAeP63SvaKrgDdSmHiq",
	"zueVQlVcZZDM9Au6FuEVLCr5b5V9aSjRz8LnolXXhlSuK7Nss50eax5mlKWeTmJmk9UaOVGtExGxsW4z",
	"NjedsTk01Xcf8WOIC8rQYEFf+Zby1atjgF7tiFEHEs0p8hHnErsJBJrAt4wutqUkWlSbZNqHxMoGCc0i",
	"E4/fhDa8tT3a+L3khwaOJjYRTSW7EyrmiPUdHVq56oXhNN2ZEY8RMG4qjK91J5v5Vl/tgMqCLu/i6hjb",
	"i74Wqp7W+mC57lunYK5UW/Y95uLMTMBmb2YzV1k97JVsm42GRjklcAeaW7PVLj8ztYuOiWwk7/b09znS",
	"cmNqHEGGANIve1FAyRgmaKGUAP8iLwP7E0oLBFWBSpyHoKC92Jaz2g3Vl481FjHQ5i+dO47otcpbcOSl",
	"AE8BR8LrCGAOKCmW3tQKqr9pedlJVeh70QzLdOgrq0mBs0MF8fGZlVsEKAtI1G1r+pudKcyUPkAVZRqD",
	"kBie3PZVY3nSIiNtr3hnGle+z8xy6SpVRiy3ft9XmA0F3jvSPVyb01wB6ft4b9xHHQGpL0v2b/dMxxyT",
	"Hdhzaqh1hHYV0Fb/rspn99Ii04nt1HfuZKaWRdq0tnxyfXLcfj+enIGr7XnduOeJv7m8+b8AAAD//xU5",
	"pUij8QAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
