// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing checkout session
	// (POST /organizations/{organizationID}/billing/checkout-session)
	CreateBillingCheckoutSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get billing customer details
	// (GET /organizations/{organizationID}/billing/customer)
	GetBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update billing customer details
	// (PATCH /organizations/{organizationID}/billing/customer)
	UpdateBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// List billing invoices
	// (GET /organizations/{organizationID}/billing/invoices)
	GetBillingInvoices(ctx echo.Context, organizationID OrganizationIDParam, params GetBillingInvoicesParams) error
	// Get upcoming billing invoice
	// (GET /organizations/{organizationID}/billing/invoices/upcoming)
	GetBillingUpcomingInvoice(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing payment method session
	// (POST /organizations/{organizationID}/billing/payment-method-session)
	CreateBillingPaymentMethodSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// CreateBillingCheckoutSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingCheckoutSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingCheckoutSession(ctx, organizationID)
	return err
}

// GetBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingCustomer(ctx, organizationID)
	return err
}

// UpdateBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBillingCustomer(ctx, organizationID)
	return err
}

// GetBillingInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingInvoices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBillingInvoicesParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingInvoices(ctx, organizationID, params)
	return err
}

// GetBillingUpcomingInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingUpcomingInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingUpcomingInvoice(ctx, organizationID)
	return err
}

// CreateBillingPaymentMethodSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingPaymentMethodSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingPaymentMethodSession(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "last_name", ctx.QueryParams(), &params.LastName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", ctx.QueryParams(), &params.First)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameter("form", true, false, "max", ctx.QueryParams(), &params.Max)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/api-keys", wrapper.DeleteUserAPIKeys)
	router.GET(baseURL+"/api-keys", wrapper.ListUserAPIKeys)
	router.POST(baseURL+"/api-keys", wrapper.CreateUserAPIKey)
	router.POST(baseURL+"/marketplace/register", wrapper.RegisterMarketplace)
	router.GET(baseURL+"/organizations", wrapper.GetOrganizationsList)
	router.POST(baseURL+"/organizations", wrapper.CreateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID", wrapper.DeleteOrganization)
	router.GET(baseURL+"/organizations/:organizationID", wrapper.GetOrganization)
	router.PUT(baseURL+"/organizations/:organizationID", wrapper.UpdateOrganization)
	router.DELETE(baseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys)
	router.GET(baseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys)
	router.POST(baseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey)
	router.POST(baseURL+"/organizations/:organizationID/billing/checkout-session", wrapper.CreateBillingCheckoutSession)
	router.GET(baseURL+"/organizations/:organizationID/billing/customer", wrapper.GetBillingCustomer)
	router.PATCH(baseURL+"/organizations/:organizationID/billing/customer", wrapper.UpdateBillingCustomer)
	router.GET(baseURL+"/organizations/:organizationID/billing/invoices", wrapper.GetBillingInvoices)
	router.GET(baseURL+"/organizations/:organizationID/billing/invoices/upcoming", wrapper.GetBillingUpcomingInvoice)
	router.POST(baseURL+"/organizations/:organizationID/billing/payment-method-session", wrapper.CreateBillingPaymentMethodSession)
	router.POST(baseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion)
	router.GET(baseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations)
	router.POST(baseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation)
	router.DELETE(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation)
	router.POST(baseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation)
	router.GET(baseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers)
	router.DELETE(baseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember)
	router.GET(baseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w97W4cN5Kvwus7IAmuR5K9yY8IWOBsa+MT1o4FK0aCc4RZTnfNDKNuskOyJc0aOtxD",
	"3BPekxz41c3uZn/MaGRLiX5ZnuFHVbGqWKyv+RQlLC8YBSpFdPwpKjDHOUjg+n+n9IpILAmjpydn6hv1",
	"YQoi4aRQn0bH0QdKfi8BkRSoJEsCHC0ZR5giUs2N4oiooQWW6yiOKM4hOo6It3YURxx+LwmHNDqWvIQ4",
	"Eskacqz2k5tCjReSE7qKbm/j6B1fYUr+uRNgSBSQkCVJEPNWCYPIGvsMAvlvHJbRcfSvhzU5D8234rAJ",
	"rsbggwC+O+SlAI5wkrCSyjDkpV5/Z4gNeNGtApWDKBgVoBniRSnXf+OccfWfhFEJVKo/cVFkJNEYHv4m",
	"FBafvK3gBudFBurPHITAK3v+OCMpenF2ii5hE93GUcFZAVwSsxdJu6TRe7cpIzlOLgldIUxTlMKiXK0U",
	"p8Rtzonr3dvr/meZYzrjgFO8yACB3saORnBTZJhQtYNcAyJClNBd/dYn9sdqq4tqIFv8Bok0RA1hxUGW",
	"nEKKrtdAES7lWmFpiIoUA5RyzbjlI7TEJBMKp5c4fQ+/lyDk9gfzRPCa4GonbgiJiEA5zpaM55Aq0iuC",
	"YkIFckzrqcnbODonir2fyD+V/K+BAieJ3dYpGL2k1UBa15yd/h02ZxyuCFx3ybXgmCZr83dz+Zf2GyTX",
	"RDj9gtZYKJ0JQiDJlNaUkIvA/VLBjznHWi0lHLCEdI71kSquUH9FKZYwkySHEOXdnMWmC9/pCWJLTVqt",
	"yOUaS2THN0BW6rzMMnVCTn0P7DNXMwb2cnS403ZwUxAe2OYES6jFyG2lR4NAX6t1EVkiysxnm2+iOEzI",
	"UQiMlHQ+zrCQ81JAQIZ+IjkIifPCUUKNRWo//T8F6DUW6ixSD1K4Ar47lOYaDsBZ1Owc+I4piQlw9Jn9",
	"Zl8cLRJWWKUzcU5L2knqbI0apYagVKziH021sYdrXAtyV3XE0UuSZYSuXq0huWSlPAchCKPvncroaIWS",
	"Z13ynUtOCkCJXQQJswr68P6Nf8IlJ6NqTq0/BCeHlMiAssIZpklAEb+H3KraRE9FduRBg/VYqZit2paW",
	"+QK4lsflEhJJrmCu2HNMLt0WkLAcFMcrHj7oY/Ie4d9mJ6sAYnWHaslS15f5ThhFlDJEmRt4sG+tkOMb",
	"kpf5nFAiCc7mvcdwaga0DgEtYMk4IEw3ilirqaciJJalPnegZa7YButDUnwPNCV0NS/wJlc2wsUYw2lJ",
	"c3B3Drx5KP0IVzCN8u4JSG1ZdljYoDC3p9cl4St7rNdErpEZjMymMcKIA07WkKIKfqQgjlHBBNH/tZDG",
	"2qihDBVKSRvkDnzdNvRsaQphQO+leCPmJZUkm2ut1MBp3n+5bQTSs+rrwyLo8/mmZnMnB1xZTwqbZSlL",
	"xUiBWQf9/E2ohJVhqTbk9tgVsfu5OgS4I/jM8fiWKAzPn4bMIO13UwAeUfaySIeyu60omcTZvCs6E5SI",
	"mZqRJajNtprcUiE9KzWJNoB93Jb9oRPswXmi7E1j9CElVgrJcuD9FsLCDJyrizdrkNN8EjayFYxprRon",
	"ayGnTqtVmlbX3bQZLHGZSXeXzHOQa6YvQpxl75bR8cdJG5yZ6W/N7NuL9mvtpzUga0HZHVGCuXoD63nI",
	"bBsbjcGo1hcJo0uyKjmkWp9zkJzAlTM3mmJzG0drLAJYtMDgpW9g2HM2RjAyr/JxKA/q410wlgGmxkzg",
	"lyCLDBtRn0Y936v3tl7gjLMrkiop7BDSG4UKO8w86JVV7zsb0ddwsDpAv0b4WvwafROrF4niW/1i46xc",
	"rRFGPtQdmrZUQJPpmxgHyd/LXTUfd+RiQCxP6RUjSUAacc5KKudpGbq+ICE5zpAZg9Jyqv2VlJwDTTZB",
	"m7DHVCQGwsq6nWYSu1l276GFi3Spvh+9MrrGY8rxUvt5hSj1K6rA2iq8YvofsaEJpBMtyRbAsX8AHuFa",
	"9KigaqIzfuCiXw+nWOJtdaFjo4AyLPCKUC08ilOxW31o0bNqyls3o00z/WF48QHkmxq1g7nSSxMRbqz0",
	"Ss1rQ6gXmwrLK7tz15MWFgp7+eaMyrU3wDPl7IgNYB4eoC7xb8NhnIaC0jC44a2dm9tMRfZOvoLmtXGP",
	"HoMPRcLymrX7ob0fTbmLa3NIu66ZUOs5LWFJ3CLYuA4sF9qK7MfUjZiIp8R8BXJL5T4CwvT92yLru8n6",
	"9K8PsUcQB1WQ0iE2e6U3M750Gyfaxpf+huRE1l5GZXsJQNX4Iadjjm9OzZffHXX1dd9j+2/qc2MEKdyt",
	"fVT5lOPaj1Q5k+/DS9vniQ3Tw/Nm7kqP2iXb3PCd/kNxvB6AsBBkRZUhyHy67Lxzizc1Sfr5qBHKrgL4",
	"vXxVvbFaZ6w+RjhNuaJiIxbCTN4A+Gfa8y5rQW5GTQPdA7jtjjUBwAJvMoZT56/EUofbEIXrdtpAE2HH",
	"Uc1Vf8R5zciBNYYR6z2SH8osM4L9FB17io49Rce+XHRM3cqXQAPUXWunb4mzmsP0yEmPtR0CbG71rQNt",
	"nnPiPayIkMBHtaRkiNux1u2PkoyVacs10bJjrwNH+OLn81mV3uTNRs630FnFZD/NQ0kTL34+d9lRSCdB",
	"BUxY4z3qne67aipXU3itgrO0TOSkpezY4EptI9EDsbFJ7OMeOkn1msR0Mw/fRa/Mt4j6d5JPcXOivOdu",
	"2tFZ1uEus/6As0xJToeZKrdZN/2kwXENEsSa5SbxfAuqDvGCHjylZAp1XSx1Mku9jnobVAHABgiWmnF0",
	"M1MDZleYK1CFGjkC1Iufz6OLVg5kwGr0nYlWhhChSVamypI5PTFhNqdfumlI2+Qz/iEdqHGPLdfKnNJi",
	"ZG/OYavO9+xNJcu5mTF0OQzEdVvnpLN7pQSu0PiIZ/98Mfuvo9n389l/H1/8u4KXSIV9e1qIaRkuyCxh",
	"KayAzuBGcjyTeKVR0554/cyO6rS1btZunRzcdY81DMo+a6Uyp+o8Ym2o2NnTkxq2eKKYp0mqDdMJDxR7",
	"RYPYARU7czIaS8KF7FH5P6jvGpzaQmSiWTklS7mJRo/LnEiYZ4ReBhZ9/wapb5RpYfTqhBW1/RNG/Q2+",
	"I+a+TM93UY210LfuYe3qkTZFogGeQ9TdHTZnxJl8k339bdjjilG7dqRh0snqJKSvJ96WQrCE6OeVMRlp",
	"Q2/udmeOgBa6M99CvgAu1qTQLp3ACdUjUKaHuMqGQQ9Ajm+0cgs9vd+a7Bxk/ILqzO3ReucuEM4ydg0p",
	"whIxE37PCVXzouNntZaetFYUyr7I8Y1FbQqEuRlaQUVo6K6bBmHjhrYLB0DsmHYVvLFP3jEePa8kr/V0",
	"SHNC5xywCFlO7/XnlS5LrJjqSaiKgnX0hAuwbrmsnTZh4T49ckpTkmCp/TnQ0iYNei85yxGudiyAqweX",
	"TUtzIsculVJk3aCvczOzK+DGV13SS8quqY4UZ6B1jE2fDyqoeNt7vQH8Ljd7SnR+o/b+6OMbIh4JUGyN",
	"BVoAUORWQouNkn+zWCiRwLzEi1TDOdHVYoY7d64PwFei5otpKI8zyfUa5Bp4F1kibHZajIj8SiB1uZVK",
	"S2OB/vEvHVqiFz+eoCZvor/+FX3FLr/6h8dPQPW0qD6NIGvo5Mq5JKFb5IOuSVDfhdj6AMlnCnb1ucv7",
	"0MGBlpdVxEg+10g6/7mpskGunqMR7lOvCYqWxKSrOGTkM0Xz5+O3b3VqXRbsCHQD+RYHhTRcIGjd0XBr",
	"LOY5476PzWNSCjdynpRcmGqVEROohVq1dHOdEKQfNBadvKy+ENS2aVmDGS5BeESYvYAjQs1uWhCqV7Je",
	"KkbLMsu0DWlyUwvOFGMgkuNV9/U86TnRtoEqZ3dd0zf+thgINXj+82nRhTgaJpt5PU6rUmwhMunJ+cGV",
	"K+7pqanW+5nItYF7mjtCs8dt3I1HSqCpfTEgQxYTJTCMYi/e0lBDD/KA2d65UpVedgz67uFc6Noqxbyu",
	"7Awnsg5DRaIsCsblf9xgiQ8I035qS/EXzfLCF2enURxdARcG62cHR/r1UwDFBYmOo78cHB0cmeNca0wO",
	"1blcwsbeNhkEiwL05ygvM0mKrAp9CGVFYiQIXWVV0Z3StIpU5u2UVrMVQUyUS9h6VhDyJUs3dyq1C/mg",
	"OccbJTvOU396okO8Bjn0tc2tR98dGRwK4A72b/YVflWAhSvomoW87brc50ffBhA6O0WKbBaDFIlSx0OU",
	"QtNBi2+PjvrYsVr9sF1fquc9G59XlwrrGd+Oz/DLKG/j6LtffglpHbhRZiukyA5UZg8kJSdyo2X8Rl+J",
	"HyN1RsfXnEiILm4v4kiUeY75JjqOXpbZpTvVikbOMvfqbms3gdE4HyuK6tfkCoKhEZ3pCgijjAjpsdPQ",
	"Fl3ef0OEbHN+47yP7sD+tdgO8X8NsKXCpEy9ZtXmWB2ZhmRKyeibNjFtSvEX5ep9cCgHnLYZVCN7B84s",
	"WChqZ9IgbBaD03Hb8KRZoObKO6jjIQ4KZSxNUoHP7iYSY3B56RYBNp7ExfaUqgSDx826QeVacZk2rC3C",
	"YUa9jaNDLwZz6GLJ+nSCLPyG0EvRw6/aZRwIGYpyUS1xgN7RbKOLFPpCnvqNaH1d6oYPi4ILkb9thJDu",
	"QxoG4vKThOJo2C/bQL1mx89tHXy/vXVw9PwO4u41RthfW4NeutaxSkwySPvFymPKsHS9n5Bu4STN580L",
	"7Ta/0Q+WtC4ROWy4SELpK0QgoGnBCJXIOHOElxBHU23lqL8bK2nwCEW/qIcHetf4CnOTWSRZMcvgCjKk",
	"5Fi61CvXacPlrcRVsql5fkvAufMdK7kctsK0l82aDjjLWlD2KJIFZIyulO0fe94AuQbC9ZvAhc7FAWoS",
	"SOsNnSvF9ctBmUDhbTdojZWR6PKTuhrmNcgG3ZRNsF8rcOTsncXVJZkmUm961d2zCR594H3Q5G2SfYpe",
	"eff3P/xjjfFV0BJ+DbKS3ybhaj33rknQEftXBNJ4ay9cQBtggYgUzlnBrmm/afyuyYf3ZxyHcplvu926",
	"tjWJp0pHkEl9evp2bRW3+TPw8LBJHEr97mXien7z/nyLKV6Bbh7RucEPPzVb1t0OOec+/sgk0hRQi0GK",
	"NiAv0BnwHCtCZRvnI2mH6M2thxN91AmmlEm0AFTSlFHoc+N1ZGPMe9XPUNad9bkZ6i+PmAVPgic5yH9D",
	"lqA1aAWqTloMdVeMjWWkrChXCZ7FJvBJ6Cq2fcxMEFlbak0w0WKjVXDZjjiM238m9VGnLdQRHrxgpeyD",
	"1W12ejJqk93VHNubunUJng/BJ/Zo5KTP3GAByg5bG17L1J4YUz3kMNS7VAFRlAE+NiHUBvPaHCS4Cby7",
	"YnXua2exKDu1y8NmyT1ZKvdl6/8I180E9ZGCqaDtc/QAbB8XyX8SwclXleX5rcUwbC+hd9UNNcFc+mxB",
	"TR/EOsSzH03yxUKkT0HQfUvZHmOb/abf3YOaPaZUOKp5v6z/xWKk7W7iT7HSR3gpbRGRnShPW4ZiA9nw",
	"Y46mKhb7ZW+Pp4huy9DrjlOHrCsJqm6YjFcdxXlFl51DrrQRaRmPvY7YQjaj8tC1zZ3ZJjj94dnaw9rX",
	"cVeXkevaHkmuFNC6R5vLSd9CAsJ9gR/GRTKlqV9PP+MAh9kZXVp+Ib/qXz5vpsG4V3XRQyCP8S0Np4VB",
	"ByTBJjErfAYNJVED5YrHnY/G2QvWYtJKYIjdX4NspVA/HiZv9+Ic4u4Wnf6kzqc+tpnIyzo/N1n3OZL2",
	"yJbB5P4HbYQMliNMT6X54gLy5FLa1aV0R+Ha4qKw1XJii4vCTbnDBeF6bu5HDDuVEHXlETJVP66kUPen",
	"YaWof8nF/ibV7yXoBjW2HMHWCg3+tlfHE1wVj1YEkgwtQWm58C7awm5sYuvCouPnR1WH/Oj42dFRq261",
	"XYb6Ga7ITpvUAQ1QMdWT5E+9UvWzvS1h9yfuh6Vt5jlB7nUilR3eBnFEB3wlqt9XaOa2dvLsKvpJZhPO",
	"JMqZkDoDNrTGgHZpNSp9NFZoX4PVgKR96DmPP6kx2see+xcgW347M+W3OzgaBMiymOUsHfI5pNrhYuut",
	"2zkG3T7xA26HUJ/hRyMQg02SB+6fnpbIT26IphsiTKb9yYxLlJlxr5Q6KCU/ZHglAo0gGK+ybQ7QT82f",
	"PeTwm6FHqCGCkCTLbOavvjtckvbBr1St418l+lcgME1AN90ieQ4pwRKyjc72wXSDWCmFxFXPEmPcqVsr",
	"YVlmgMClZDmWJMGZmriUwBFGK647ygAnLDVZ48oCVYePciKEWi+FDG90BideKfwKxjWUJy7LSDFMBlqH",
	"iA1N1pxRVgpdG5KAztlugGRa72vQBUiZQXrwKw1UhWg6+oLtNrwv7fC8Jz6tcKzacaD/+5//DfTUUIe5",
	"UNTJ2ZUyMRzmvQdjUX/4Buj3D+bp6VplttIZKqboy2eYoAj8Pj9j9qbj6KrJUMDVbrKgmes3vSSZBK6v",
	"/031Q162JYKrgBiP8J42mhHdx7P0Bw1nA7kK4J4nYvWl9xPFW/XamgYD+E0fekBx7R22eBKHN1tWTd56",
	"dvI6xO1huwwP71b3ZNtqs3PAPFmHCcn40IZCz9xut1Oawo0rIjEE5CDKzHa2lSWn6Ouj2QIrC5ItlwJM",
	"c5n650C+GSJ22Anhex2OQs2vxntyGSBFDWUPFDm+CcNgfB+fzxPSSi1qKq5JqRI9zSNHf6fU22qb1Amf",
	"AZ+yJyZegqa3Yr8jZuT+2aGk5xy0LdlonKl1ha4FdlXBvzFCd8msOPWbMT707IrhX2aYnm3R1pAVYYXu",
	"VvkHl4AvYDpaqQlajwH+7uHnvZmSh5/q/4wUEIVLhTxYOSSMp1NyYPctavHotFMPy97X1beDEvEQMkof",
	"z7UwUpfUbPHbew/so9zH49DpxT4PlEPvp8jBt7C6RlJDBJ4qj/ZlI70GWdGTLcMMe19qXuEL5kcAw5bW",
	"e/09woEuw64XxZKDWJvG5faqIiEPgVnp0St/TTD5xO67637HUnRv/J3Xba3tPTHsnKrbSj+48gMPlUnv",
	"Y6/j5dib2C09tfXETkF31za8W827lyM+/FTqPpkt+7StaXJ2Bd0D/1xaxrTy3Ea/GPicR34nd7OaibCl",
	"v83QuYcDWJNillWN8yfkOuTBbvr9SQ51v82qAz1NfRfCN6MmW6fF/4OP0A5CH+o41UvUxoE/nhDrpKLs",
	"DisNcfRt9V33lzUbvQtcV6vYGbP671CTgna3q9rh2ty968ptbZljildqOb9nsvC7THtrK22yzZqu+svv",
	"YWVwZDR2bbuavRfqzapKkdH9MkIvuyhINtKJz0PM71MW8tFL4BRnrSYNNthe95+o13Px9duL2/8PAAD/",
	"/6IResTelAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
