// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing checkout session
	// (POST /organizations/{organizationID}/billing/checkout-session)
	CreateBillingCheckoutSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get billing customer details
	// (GET /organizations/{organizationID}/billing/customer)
	GetBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update billing customer details
	// (PATCH /organizations/{organizationID}/billing/customer)
	UpdateBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// List billing invoices
	// (GET /organizations/{organizationID}/billing/invoices)
	GetBillingInvoices(ctx echo.Context, organizationID OrganizationIDParam, params GetBillingInvoicesParams) error
	// Get upcoming billing invoice
	// (GET /organizations/{organizationID}/billing/invoices/upcoming)
	GetBillingUpcomingInvoice(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing payment method session
	// (POST /organizations/{organizationID}/billing/payment-method-session)
	CreateBillingPaymentMethodSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List groups of an organization
	// (GET /organizations/{organizationID}/groups)
	ListOrganizationGroups(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a group in an organization
	// (POST /organizations/{organizationID}/groups)
	CreateOrganizationGroup(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an organization group
	// (DELETE /organizations/{organizationID}/groups/{groupID})
	DeleteOrganizationGroup(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam) error
	// Get details of an organization group
	// (GET /organizations/{organizationID}/groups/{groupID})
	GetOrganizationGroup(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam) error
	// Update an organization group
	// (PUT /organizations/{organizationID}/groups/{groupID})
	UpdateOrganizationGroup(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam) error
	// List members of an organization group
	// (GET /organizations/{organizationID}/groups/{groupID}/members)
	ListOrganizationGroupMembers(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam) error
	// Remove a member from an organization group
	// (DELETE /organizations/{organizationID}/groups/{groupID}/members/{userID})
	RemoveOrganizationGroupMember(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam, userID UserIDParam) error
	// Add a member to an organization group
	// (PUT /organizations/{organizationID}/groups/{groupID}/members/{userID})
	AddOrganizationGroupMember(ctx echo.Context, organizationID OrganizationIDParam, groupID GroupIDParam, userID UserIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// CreateBillingCheckoutSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingCheckoutSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingCheckoutSession(ctx, organizationID)
	return err
}

// GetBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingCustomer(ctx, organizationID)
	return err
}

// UpdateBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBillingCustomer(ctx, organizationID)
	return err
}

// GetBillingInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingInvoices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBillingInvoicesParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingInvoices(ctx, organizationID, params)
	return err
}

// GetBillingUpcomingInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingUpcomingInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingUpcomingInvoice(ctx, organizationID)
	return err
}

// CreateBillingPaymentMethodSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingPaymentMethodSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingPaymentMethodSession(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationGroups converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationGroups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationGroups(ctx, organizationID)
	return err
}

// CreateOrganizationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationGroup(ctx, organizationID)
	return err
}

// DeleteOrganizationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationGroup(ctx, organizationID, groupID)
	return err
}

// GetOrganizationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationGroup(ctx, organizationID, groupID)
	return err
}

// UpdateOrganizationGroup converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganizationGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganizationGroup(ctx, organizationID, groupID)
	return err
}

// ListOrganizationGroupMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationGroupMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationGroupMembers(ctx, organizationID, groupID)
	return err
}

// RemoveOrganizationGroupMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationGroupMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationGroupMember(ctx, organizationID, groupID, userID)
	return err
}

// AddOrganizationGroupMember converts echo context to params.
func (w *ServerInterfaceWrapper) AddOrganizationGroupMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "groupID" -------------
	var groupID GroupIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", ctx.Param("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"group:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddOrganizationGroupMember(ctx, organizationID, groupID, userID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "email", ctx.QueryParams(), &params.Email, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last_name", ctx.QueryParams(), &params.LastName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "first", ctx.QueryParams(), &params.First, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max", ctx.QueryParams(), &params.Max, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/api-keys", wrapper.DeleteUserAPIKeys, options.OperationMiddlewares["deleteUserAPIKeys"]...)
	router.GET(options.BaseURL+"/api-keys", wrapper.ListUserAPIKeys, options.OperationMiddlewares["listUserAPIKeys"]...)
	router.POST(options.BaseURL+"/api-keys", wrapper.CreateUserAPIKey, options.OperationMiddlewares["createUserAPIKey"]...)
	router.POST(options.BaseURL+"/marketplace/register", wrapper.RegisterMarketplace, options.OperationMiddlewares["registerMarketplace"]...)
	router.GET(options.BaseURL+"/organizations", wrapper.GetOrganizationsList, options.OperationMiddlewares["getOrganizationsList"]...)
	router.POST(options.BaseURL+"/organizations", wrapper.CreateOrganization, options.OperationMiddlewares["createOrganization"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID", wrapper.DeleteOrganization, options.OperationMiddlewares["deleteOrganization"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID", wrapper.GetOrganization, options.OperationMiddlewares["getOrganization"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID", wrapper.UpdateOrganization, options.OperationMiddlewares["updateOrganization"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys, options.OperationMiddlewares["deleteOrganizationAPIKeys"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys, options.OperationMiddlewares["listOrganizationAPIKeys"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey, options.OperationMiddlewares["createOrganizationAPIKey"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/billing/checkout-session", wrapper.CreateBillingCheckoutSession, options.OperationMiddlewares["createBillingCheckoutSession"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/customer", wrapper.GetBillingCustomer, options.OperationMiddlewares["getBillingCustomer"]...)
	router.PATCH(options.BaseURL+"/organizations/:organizationID/billing/customer", wrapper.UpdateBillingCustomer, options.OperationMiddlewares["updateBillingCustomer"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/invoices", wrapper.GetBillingInvoices, options.OperationMiddlewares["getBillingInvoices"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/invoices/upcoming", wrapper.GetBillingUpcomingInvoice, options.OperationMiddlewares["getBillingUpcomingInvoice"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/billing/payment-method-session", wrapper.CreateBillingPaymentMethodSession, options.OperationMiddlewares["createBillingPaymentMethodSession"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion, options.OperationMiddlewares["requestOrganizationDeletion"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/groups", wrapper.ListOrganizationGroups, options.OperationMiddlewares["listOrganizationGroups"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/groups", wrapper.CreateOrganizationGroup, options.OperationMiddlewares["createOrganizationGroup"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/groups/:groupID", wrapper.DeleteOrganizationGroup, options.OperationMiddlewares["deleteOrganizationGroup"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/groups/:groupID", wrapper.GetOrganizationGroup, options.OperationMiddlewares["getOrganizationGroup"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID/groups/:groupID", wrapper.UpdateOrganizationGroup, options.OperationMiddlewares["updateOrganizationGroup"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/groups/:groupID/members", wrapper.ListOrganizationGroupMembers, options.OperationMiddlewares["listOrganizationGroupMembers"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/groups/:groupID/members/:userID", wrapper.RemoveOrganizationGroupMember, options.OperationMiddlewares["removeOrganizationGroupMember"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID/groups/:groupID/members/:userID", wrapper.AddOrganizationGroupMember, options.OperationMiddlewares["addOrganizationGroupMember"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations, options.OperationMiddlewares["listOrganizationInvitations"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation, options.OperationMiddlewares["createOrganizationInvitation"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation, options.OperationMiddlewares["deleteOrganizationInvitation"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation, options.OperationMiddlewares["getOrganizationInvitation"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation, options.OperationMiddlewares["resendOrganizationInvitation"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers, options.OperationMiddlewares["listOrganizationMembers"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember, options.OperationMiddlewares["removeOrganizationMember"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits, options.OperationMiddlewares["getOrganizationMembershipLimits"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D1rb9y2ln+Fq12gLVZ+JG0/1MAFNo8212jSBEmDFpsEc2npzAxriVRJyvbcwIv9EfsL95dc8CVREvWa",
	"GdtJ6k9xbIo8PDzn8Lz5MUpYXjAKVIro5GNUYI5zkMD1/55xVhanT1+pX6r/pyASTgpJGI1OoreU/FkC",
	"IilQSZYEOFoyjjBFjK8wJf/EahxaqTmiOCLqkwLLdRRHFOcQnUQrM30URxz+LAmHNDqRvIQ4EskacqyW",
	"lJtCDRWSE7qKrq/j6JReEKnnng8Zqb4NQ0S8uWeC9dLb9FzAkCggIUuSNFAXBpE11hkE8j84LKOT6N+P",
	"6jM+Mn8VR01w9Q7eCuDbQ14K4AgnCSupDENe6vm3htiAF10rUDmIglEBmkoflXL9I+eMq/8kjEqgUv2I",
	"iyIjid7h0R9C7eKjtxRc4bzIQP2YgxB4Zc8fZyRFj16donPYRNdxVHBWAJfErEXSLmr02m3MSI6Tc0JX",
	"CNMUpXBWrlaKUuI25cT16u15/17mmB5wwCk+ywCBXsaORnBVZJhQtYJcAyJClNCd/dpH9rtqqQ/VQHb2",
	"ByTSIDW0Kw6y5BRSdLkGinAp12qXBqlIEUAp14w7Xl9ikgm1p8c4fQ1/liDk/IO5R3iNcLUSN4hERKAc",
	"Z0vGc0gV6hVCMaECOaL1ZPd1HL0hirzv0T8V/c+AAieJXdYJGD2llUBa1rw6/Rk2rzhcELjsouuMY5qs",
	"zc/N6R/bvyC5JsLJF7TGQslMEAJJpqSmhFwE7pcKfsw51mIp4YAlpAusj1RRhfopSrGEA0lyCGHefXO2",
	"6cJ3+hSxpUatFuRyjSWy4xsgK3FeZpk6ISe+B9ZZqC8G1nJ42Gk5uCoIDyzzFEuo2cgtpUeDQF+reRFZ",
	"IsrM7zbfRHEYkaMQGC7p/DrDQi5KAQEe+pXkICTOC4cJNRap9fT/FKCXWKizSD1I4QL49lCaazgAZ1GT",
	"c+BvTHFMgKJf2b/si6JFwgordCZ+0+J2kjpdo95Sg1EqUvGPplrY22tcM3JXdMTRY5JlhK6erCE5Z6V8",
	"A0IQRl87kdGRCiXPuuh7IzkpACV2EiTMLOjt6+f+CZecjIo5Nf8QnCzLIFHLvgC5ZgFq/Du7RGdmMCrw",
	"Jgeqr5vEfAipkfBraKinhwqftMw1BPScskulsQq9rYWdZZGbFeMox/wcZJHhRB3PGabnC8kxFUvgHux2",
	"g3F0daCmPrjAXB2oUGv07OZttXTPAIPoVwagFw6ensEvGmD2DHqM6fmvFfAeojmkRAZuBZxhmgRuvNeQ",
	"2zst0Z8iO/KwweOsVFxd4YiW+RlwLfiWSwXWBSyUHBgTgG4JSFgOSrQoYXHYJ016pOyclaykjZWyokWY",
	"oiLzN2EkfsoQZW7g4b7Fb46vSF7mC0KJJDhb9B7DqRnQOgR0BkvGAWG6UchaTT0VIbEs9bk77sD6kJSA",
	"AZoSunLc0SX8oEhzcHcOvHko/RuuYBoSEnrvT0FqFb5DwmYLC3t6XRQ+scd6SeQamcHILBojjDjgZA0p",
	"quBHCuIYFUwQ/V8Laay1R8pQoW5Ds7lD/xIZsg+bTBi4YFK8EYuSSpIttPhv7GnRr0VsBNJf1fe03aBP",
	"55uazB0fcKWmqt0sS1kqQgp8ddhP34RKWBmSakNuj10hu5+qQ4A7hB84Gp+5heHvp21mEPfbCQAPKXuZ",
	"pIPZ7WaUTOJs0WWdCULEfJqRJajFZn3cEiE9MzWRNrD7uM37QyfYs+eJvDeN0IeEWCkky4H3q2JWy1mo",
	"izdroNP8JmTNYLqwmlAluOvr5oyxDDDVAys1wak9SnBm2ctldPJumuxqa2rXH+KOyoDTA0azDaqXQ2Y5",
	"lDC6JKuS9ypsxjZTGE9rQT9ZprrLoZqlqazvJpthictMtvXGuQhsanld7P26BmQVb7siSjBPK6XXLBsb",
	"+ccoGC24wqq6nThITuDCKU9NIXAdR2ssArtogcFLX12yVGtsJ2ScOeNQHtbE6hGhr2dPxp7vDPY04Fec",
	"XZBUyZQOIr1RqLDDLNER0QwAfA2Hq0P0PsKX4n30TawMWcWF2tDnrFytEUZN66CF05ZAa7Jw27LoMmGY",
	"g4MH1UuHNcV3OGhAHJ3SC0aSgBTCOSupXKRl6NqGhOQ4Q2YMSsupemdScg402QR14R4VmRgIK61+ming",
	"vrJrD01cpEv199Grsqs0pxwvdSBBiFKb6QXW2vAF0/+IDU0gnahBtwCO/QPwENfCRwVVczvjBy76758U",
	"SzxXajoyCojNAq8IxY7asZt9aNJX1Scv3BdtnOlfhicf2HxT9nZ2riTYxA03ZnqivmtDqCebCssTu3LX",
	"VRtmCqt05IzKtTfAU2HtiA1gHh6glJfvwnHChijTMLjhrZWby0zd7E7OqOYFc4MuqbdFwvKatPuhvRlJ",
	"uY3vfEi6rplQ8zkpYVHcQti4DCzPtPbcv1M3YuI+JeYrkDOF+wgI09dvs6zvh+2Tvz7EHkIcVEFMh8js",
	"iV7MBGtsIHJOsOY5yYms3dhKSxOAqvFDXu0cX52aP35/3JXXfU6GH9Xvjbqk9l6p79arHtf+sypacRNh",
	"gD5Xfxgfnrt8W3zUPv/mgi/1D4ri9QCEhSArqlRG5uNl65VbtKlR0k9HvnqsU2I8kmpbZyZWW+BNxnDq",
	"PJ5YmshoODOmSZXueJoT/4LzmiooXFYfD4vhGRur02p6GaYymlvEq36NcJpyRR6NKCIzGTfgE2uPod2C",
	"3IyaBvqWx6Hx2Eq42eosWnNseSQ/lVlmJNZ9XPk+rnwfV767uLJSN86BBrC71l78Emc1hemRk6zQLULT",
	"bvbZIWrPP/MaVkRI4KNSUjLE7Vgbx0FJxsq05Z1pKeiXgSN89Nubgyox0PsaOadJZxaTN7gIpRs9+u2N",
	"yytEOn0woJsbB1rv5763qvK2hecqOEvLRE6ayo4NztTWfj0QG4vE/t5DJ6nMZEw3i/Bd9MT8FVH/TvIx",
	"bk6U99xNW/oLO9Rl5h/wFyrO6RBT5TnsJm61fHoeCmJNcpNovgVVB3lBJ6YSMoXLefCx5+c7NEEYyloY",
	"AerRb290BoGvzgTUYV9ttDyECE2yMlWazOlTEzd18qWbwDcnE/iL9CHHPbpcK+dQs5G9OYe1Ot9lORUt",
	"b8wXQ5fDQKC+Y4UEBJQxC7T0JrRtcERTkpnDed4KHz0WRxwRsWCXNMRgv61BrsEeKBF6moJDCkuijLn3",
	"0Uv13fvIzB2jyzVJ1ijBlDKJzgBBSqRJdk0hA2kjMHkpJMLZJd4IxBUzUIQlykBpOowCysF6ebvRkdlE",
	"0LtpndrenYkAxzxZkwRnSA1pzOPOZZy6BiikwvYkGnlT5jk2Sux8NjZUdh23rRGD4IVJ9e+aR9r/ozbe",
	"YGHzkRJbIcRWvtNOBq+3VHfHHZkyzAFIspWhSK3fECksWMgs0CnjMCUxUgJXk7/DB/98dPDfxwc/LA7+",
	"5+TDfyrwiVQypv1Z6GpguCAHCUthBfQAriTHBxKvNEJ1yE976aKa8bpVJXXxSte73jDb+myCymip61y0",
	"OWC/np4LNsMRYBwAqTb/JrgBrCIMYout2C8nb2NJuJA9itVP6m8NUdDayETjbap0bVQmhS2+MKDP8Y5w",
	"+gyy2EZdqC/Clm6q/brS5oE1wHMbdfqUTYxzZtDkwF4b9rgiq65tZUhq8hUb0mEmapBCsIRol4Mxo2hv",
	"3ux0PXIEtJAe+cJI3DUptP82cEL1CJTpIaEKvo7akOMrLYpC7qgXJgUR0eoSsEfrnbtAOMvYpbrN1YWt",
	"1bWcUPVddPKglqmT5opCKWY5vrJbmwKhu5kcVOEbehqEoStvwi1Xwxv76B2j0TcV57XM6TQndMEBi5A1",
	"8Vr/vpI8iWVT/RGqQt4dOeHyLmZO6/LKxyfukyOnNCUJlmD0x6Y0aeB7yVmOcJ3JDlwU4HJvHcuxcyUU",
	"WTfDw8WU2AVwE5iqs9q1+qlkjC3GCgqoeO4t3AB+m3s4JTqJW3tE9fENIY8EMLbGAp0BUORmQmcbxf9m",
	"spAGbbxTRarhnOh+NMNd7MYH4CtR08W0LY8TyWVldLQ2S4RNwY0RkV8JpC63UhsVAv3j3zq4RI9+eYqa",
	"tIn+9jf0FTv/6h8ePQHVn0X1aQRJQ2eQLyQJ3SJvdYWb+luIrA+RfOCMJ5cOpiOBrciDiJF8qDfpgmWm",
	"ZhO56sBGbF9Z2BQticlic5uRDxTOH47fvtWpdUmww9CNzbcoKCThAhkqHQm3xmKRMw7hTEwKV3KRlFyY",
	"2scRFai1tWrq5jwhSN/qXXSST/vizXNzTwcT3/rh2S1cqU9m53AlXDZdkjuGK9+KMN8AR4QaNGoOr1xi",
	"GkcxWpZZpgExlQUFZ4riEcnxqusqm2TVtJW7KrJVl76PmzgDcUUvWDYNXfFAqNSWzE8u5m9tZJLl+9ZV",
	"9e/J4lXz/Ubk2sA9zWmhyeM67mZVSKCpNYWQQYsJCRpCsRpFabChB3nAzPekVh0KOpZKwHOhS5AV8brq",
	"bJzImqEiURYF4/K/rrDEh4TpoJTF+KNmFf6jV6dRHF0AF2bXDw6PtVlXAMUFiU6ibw+PD4/Nca71To7U",
	"uZzDxl6jGQRLuvTvUV5mkhRZFefUDhyMBKGrrKpNV1eIQpUxCtPqa4UQE9IWtu0DCPmYpZudKtJDASfO",
	"8UbxjgvLnT7ViSpmc+hrWxmFvj82eyiAO9i/2VcSiQIsXGje7HfRbl/x8Pi7wIZenSKFtsrxKUod/FQC",
	"TUcovzs+7iPHavajdhsG/d2D8e/qjhr6i+/Gv/C7DVzH0fe//x6SOnBVmHpSO1Dpc5CUnMiN5vErfde/",
	"i9QZnVxyIiH6cP0hjoTzYkaPy+zcnWqFI3fJeO0pav+HkTjvKoyqM7o6qKj14JxQRbApCMlLYyxcx9EK",
	"gtelTv0HhFFGhPTobQiGLnM8J0K2WaNBEMc78EfN10MMUgNs0TQpIbnZ/WCsHvvcYnu09cLzNjJtjcWd",
	"kv0+SJgDTtsUrDe7V9LVq1zHUcFCOp5Jl7LZTk48zqFWM0FNrztI8iHaCqVsTpKeD3ZjljG4vLSsAIFP",
	"om97flUi0udN1EG5XFGZ1snthqeTsJlTrXvkhXGPXDqKPrggdT8n9Fz0kLJSAAIpLEiUZ9UUh+glzTYm",
	"bNiTNaFNausaVHpDmEtclk2zgcBNMMpAas8kfjkedmM3tl5T6m3rHD/M1zmOH+4gCbyuRPvrKdSL1zrd",
	"AZMM0n6O84gyzHivJ2RsOSb0aVPzIVxpM6hqxDbMmQ1nUyg5jggENC0YoRIZt5jws59TrTWpnxszuVjt",
	"78rSQS8bf8Lc5C1KVhxkcAEZUiwuXWKn64DlsuLiKkff2PsScO688Iplh7U67a+0qgjOshaUPTLmDDJG",
	"V8rYiD33g1wD4doIcYk54hA1EaRFis7E5NpUUSpVeNkNWmOldLrsx67weQaygTelY+xXqxw5e6fBdVGm",
	"kdSbvLl7rtJnn9YzqEI30T5F5Lz8+Yu3DhlfBTXrZyAr/m0irhaBL9sI3VKfFoHygdohGJATWOh0E+s3",
	"0Rk8far2yyaF3pyyHaqhuO7215yrYk/lmyD5+vj09eQqNvZXoO5hFTtUcjKDvO2N7k/dvHRfYIpXoKvk",
	"O9f+0cdm/9nrIRfiu1+YRBo5ajJI0QbkB/QKeI4VDrON8+S0MyTMVYlNc4s6HbCkKaPQ52zssM2Yj62f",
	"1qzT7bZp7dvPmDqfBk9yJmm2nHBD+qXVoAWqJhFDvZRjo28p3cw18MjiKtYV266lJsiv9b9W8Otso8V3",
	"2Q6cjGuVJl1bp5XUgSp8xkrZB6tb7PTpqKa3q5K3N1HtktI/Bc/dZ8NIfUoMC2B2Wx3G6+feE0SrhxyF",
	"epgr8IoyQOEm2Nwga5s9BlcBOy9WFLF2epDSi7vU3Y1f7zFstC/bohPbHknlDmpUx5+ARuVyMO6Zc/It",
	"Z2l+Dww6ooWhl9W1NkEJu7WArg/iJxDYvQ/d7pt19hiR7VcFbyEU26NahWOxfVR9ZzHZ9isg97HZz/AS",
	"mREB3ppV9qzmzQsgB+oaxtxZ9xHkvUSQPW7rjlPHo6s5qrbLjFdvhPAKL1uHeGkjRrNTrHdEq7EJr0eu",
	"R/6BbUjWfqjqZiheIIz6mvTr/hmSmXxyhRXdn9MVHsxgjvBTAjdp1o88XhAgPvtFFwt35JL99naTHsYd",
	"smc9CPJ4wuJw57DrAJPY9HO11UGVSdTwulYYznvj9A+rO2nRMUTDz0C2kt9vg3LbTZ6HSLa1w7+oQ6nv",
	"wHcg0D1rHlgm6z4X0x4JNliwcUPqyGBxyPRMnTtnnXs30bZuohtgu/n3gi1rFDPuBffJDveB64QcdSRE",
	"q9lXVeuFTJ2VK+LUXbJYKeqX2Oybkn+WoNtk2ToJW501+DZnf4eKaqeSoSUoGRReRevTjUVsJV508vC4",
	"englOnlwfNyqFG4X/n64eS7vdKEe4PKKOu65e+qFqs33Nqt8IjfpFnLhqLS9mCcICJ3QZYe3UTAiLL4S",
	"1bNAzfTbTr5fdT6S2cQ3iXJme/uE5hgQQ60+07egnfZ1tg7w4NseTP5FldQ+wvr8WMuWWh+YUus781oI",
	"kGVxkLN0yIGRaveQrdBvZz10HxwZ8GGE2tDfAsMNdr8fuPl6et3f+zSaPo0wmm5Fg3X5OAfcq6i/QQb6",
	"KcMrEegq4trP2cy0xovMHP4wCA911xCSZJlNftbXlstTP3xP1Tz+LaZfGsI0Ad3VkOQ5pARLyDY6NQnT",
	"DWKlFBJXDXCM3qouzPqZTlxKlmNJEpypD5cSOMJoxXV7IuCEpSZxXinXClcoJ0Ko+VLI8EanquKV2l/B",
	"uIbyqUuJUvjNQIsXsaHJmjPKSqErZxLQaesNkMyjLRp0AVJmkB6+p4GaGY1H/5Tcgl3B8bAnoq2gq7qy",
	"oP//3/8LtFZRx3Cm9pWzC6WXOJh7UWqB/vS14h8+GZvX9ZJo5UZUx7l1HuAESaG7S4xbuPrMzVhbt6Fr",
	"NVg3//RHnKybO2GXSj1VbMoyndVt+gyubcPHjV/9gQeaXBoGXLEL4FSgFNMVcGXmemmMLk/KiWDFRUGs",
	"jkeznxnE7DWYXSN7Uly6tyXlWIjarjMnSN3tV/Ile3z1BvtNVEvo3WTWYWbsXuGESuAUZ7fnDR6PQw91",
	"+XSXtACupL3O1au50EsnF5BOCVo/s71rbqcQo9Gx5wbC1zObv3aZTf/hE6hlvh0evYMr1vD1sHpu6D/Y",
	"43nfvD1dYTcS5+ij/nekNiRcL2D2ZRh44A6tedjm2E3JV6zZeCyDz1D4p5C+99ncQjNqQupeYHsm1HDe",
	"4GD9RA9NHN+FRP3yQ9T9CsszkFVMN1B9c1MUs0e1JR797JmRiiNVFa9B6yu7ykXTOX9KhcVNajcj/Qhv",
	"OQg+gxdtzPteu7nV++Jt2At9U9y/vWJzlNfdpYPXTNAOr1s879Ea9yCZZI577RXHDHA39RwL3Mgh9+Vf",
	"1vZ2LcX/InfZDix09LHUXTMHjYXX2nGLsHutw+aITLsUpz0XE+ropBbt4eJJdoQZWrmdNdR1M9z76+SG",
	"r5Mw1dyNMXIHXDk+3vSrHVFIH6Vpb02vw6xutOZxo+54YvlOyaWNUkmrcwj1OO9w36M03QPr4TStHw3+",
	"Ytnu5lhIH75/yp+cauY/BTIp/uO/QxIo1DBNfJh7f3pJMglcZ6Vs7FMFsWsu7lp7jYdhThvvlQwmRP6k",
	"F2xAWa3ck5xY/bHWEee9qzMNBvD7oPeA4jqez0jGDC+2rJ5f6lnJe7tpD8tleHi1+v2lWYu9AcyTdRiR",
	"jA8tKPSX81Y7pSlcOelqEMhBlJl92VWWnKKvjw/OsIAUseVSgHlIoqhycL8ZQnY4/dXPdz0OPXQz/v6O",
	"AVLUUPZAkeOrMAwm6/b2cnBbdetNCTQ7KOo96zZmkflLzbHKfAK8r9+deC2ad9T6bbyRi+RuG7YEI6hv",
	"QKcSNZ7M07JI62+uZe4fLBBSnRAmPfUfdrudWGm95PyAaVt2VigR+s26e8ffDfFTUM8MUGYPJW7XZmWe",
	"Inn0sf7PiGci3MzO2waHhPFJ8ckW/4xZOB7F3kcqdybAp4Gz26153T66wnl0NL0n3BAd3UwwxddgukpI",
	"g1Dvu8TtSwdph0xDVHN3Osi48+nUE7Ez/Mj9YlodAtB0T1ni222gT/N6rUFDOPCCqWvcvuQg1uYJY3sB",
	"kpBrwcy0n3tDI0ze8+D214Y71x2ujekaytyg45ccb3z585aFm/2RuTs02KYffk+4bCxytXXQarI82Nm+",
	"2KLgYDy8s5sKdyvXSDMIM50S1qQ4yKp3vScU7ubBx777K3brV/OqB7Jp6ns9vhlVRTsvkN+SQtpZN/Q2",
	"Sy86GgT0+dTzTeom3CGCu5R619Xandbszabe7hGZ2FkO+udQ9+724zK197i5u65furVkjinW5UH+m6jC",
	"f0XWm1vx8Jw5XTNFv2jI7JHR2L2S02xKXi9WtVcbXS8j9Ly7BclG3sTyNua/GBQKOJhAXqt7uS1bqiua",
	"6vlcsej1h+t/BQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
