// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk delete API Keys for the authenticated user
	// (DELETE /api-keys)
	DeleteUserAPIKeys(ctx echo.Context) error
	// List API Keys for the authenticated user
	// (GET /api-keys)
	ListUserAPIKeys(ctx echo.Context) error
	// Create a User API Key
	// (POST /api-keys)
	CreateUserAPIKey(ctx echo.Context) error
	// Register with a cloud marketplace
	// (POST /marketplace/register)
	RegisterMarketplace(ctx echo.Context) error
	// Get list of organizations
	// (GET /organizations)
	GetOrganizationsList(ctx echo.Context) error
	// Create a new organization
	// (POST /organizations)
	CreateOrganization(ctx echo.Context) error
	// Delete an organization
	// (DELETE /organizations/{organizationID})
	DeleteOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get organization details
	// (GET /organizations/{organizationID})
	GetOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update organization details
	// (PUT /organizations/{organizationID})
	UpdateOrganization(ctx echo.Context, organizationID OrganizationIDParam) error
	// Bulk delete API Keys for an organization
	// (DELETE /organizations/{organizationID}/api-keys)
	DeleteOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// List API Keys for an organization
	// (GET /organizations/{organizationID}/api-keys)
	ListOrganizationAPIKeys(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create an Organization API Key
	// (POST /organizations/{organizationID}/api-keys)
	CreateOrganizationAPIKey(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing checkout session
	// (POST /organizations/{organizationID}/billing/checkout-session)
	CreateBillingCheckoutSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get billing customer details
	// (GET /organizations/{organizationID}/billing/customer)
	GetBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// Update billing customer details
	// (PATCH /organizations/{organizationID}/billing/customer)
	UpdateBillingCustomer(ctx echo.Context, organizationID OrganizationIDParam) error
	// List billing invoices
	// (GET /organizations/{organizationID}/billing/invoices)
	GetBillingInvoices(ctx echo.Context, organizationID OrganizationIDParam, params GetBillingInvoicesParams) error
	// Get upcoming billing invoice
	// (GET /organizations/{organizationID}/billing/invoices/upcoming)
	GetBillingUpcomingInvoice(ctx echo.Context, organizationID OrganizationIDParam) error
	// Create a billing payment method session
	// (POST /organizations/{organizationID}/billing/payment-method-session)
	CreateBillingPaymentMethodSession(ctx echo.Context, organizationID OrganizationIDParam) error
	// Request organization deletion
	// (POST /organizations/{organizationID}/deletion-request)
	RequestOrganizationDeletion(ctx echo.Context, organizationID OrganizationIDParam) error
	// List invitations for an organization
	// (GET /organizations/{organizationID}/invitations)
	ListOrganizationInvitations(ctx echo.Context, organizationID OrganizationIDParam, params ListOrganizationInvitationsParams) error
	// Send an invitation to join an organization
	// (POST /organizations/{organizationID}/invitations)
	CreateOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam) error
	// Delete an invitation
	// (DELETE /organizations/{organizationID}/invitations/{invitationID})
	DeleteOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Get details of a specific invitation
	// (GET /organizations/{organizationID}/invitations/{invitationID})
	GetOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// Resend an invitation
	// (POST /organizations/{organizationID}/invitations/{invitationID}/resend)
	ResendOrganizationInvitation(ctx echo.Context, organizationID OrganizationIDParam, invitationID InvitationIDParam) error
	// List members of an organization
	// (GET /organizations/{organizationID}/members)
	ListOrganizationMembers(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove a member from an organization
	// (DELETE /organizations/{organizationID}/members/{userID})
	RemoveOrganizationMember(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Set the role of an organization member
	// (PUT /organizations/{organizationID}/members/{userID}/role)
	SetOrganizationMemberRole(ctx echo.Context, organizationID OrganizationIDParam, userID UserIDParam) error
	// Get organization membership limits
	// (GET /organizations/{organizationID}/membership-limits)
	GetOrganizationMembershipLimits(ctx echo.Context, organizationID OrganizationIDParam) error
	// List the roles assignable in an organization
	// (GET /organizations/{organizationID}/roles)
	ListOrganizationRoles(ctx echo.Context, organizationID OrganizationIDParam) error
	// Get the organization's SSO configuration
	// (GET /organizations/{organizationID}/sso)
	GetOrganizationSSO(ctx echo.Context, organizationID OrganizationIDParam) error
	// Claim an email domain for SSO
	// (POST /organizations/{organizationID}/sso/domains)
	ClaimOrganizationSSODomain(ctx echo.Context, organizationID OrganizationIDParam) error
	// Release a claimed or verified domain
	// (DELETE /organizations/{organizationID}/sso/domains/{domain})
	DeleteOrganizationSSODomain(ctx echo.Context, organizationID OrganizationIDParam, domain SSODomainParam) error
	// Check the DNS record for a claimed domain
	// (POST /organizations/{organizationID}/sso/domains/{domain}/verify)
	VerifyOrganizationSSODomain(ctx echo.Context, organizationID OrganizationIDParam, domain SSODomainParam) error
	// Register an identity provider for a verified domain
	// (POST /organizations/{organizationID}/sso/providers)
	CreateOrganizationSSOProvider(ctx echo.Context, organizationID OrganizationIDParam) error
	// Remove an identity provider
	// (DELETE /organizations/{organizationID}/sso/providers/{providerAlias})
	DeleteOrganizationSSOProvider(ctx echo.Context, organizationID OrganizationIDParam, providerAlias SSOProviderAliasParam) error
	// Update an identity provider's credentials
	// (PUT /organizations/{organizationID}/sso/providers/{providerAlias})
	UpdateOrganizationSSOProvider(ctx echo.Context, organizationID OrganizationIDParam, providerAlias SSOProviderAliasParam) error
	// Require members on this provider's domain to sign in through it
	// (PUT /organizations/{organizationID}/sso/providers/{providerAlias}/enforcement)
	SetOrganizationSSOProviderEnforcement(ctx echo.Context, organizationID OrganizationIDParam, providerAlias SSOProviderAliasParam) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAPIKeys(ctx)
	return err
}

// ListUserAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListUserAPIKeys(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUserAPIKeys(ctx)
	return err
}

// CreateUserAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUserAPIKey(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUserAPIKey(ctx)
	return err
}

// RegisterMarketplace converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterMarketplace(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"marketplace:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterMarketplace(ctx)
	return err
}

// GetOrganizationsList converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationsList(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationsList(ctx)
	return err
}

// CreateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganization(ctx echo.Context) error {
	var err error

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganization(ctx)
	return err
}

// DeleteOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganization(ctx, organizationID)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganization(ctx, organizationID)
	return err
}

// UpdateOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganization(ctx, organizationID)
	return err
}

// DeleteOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationAPIKeys(ctx, organizationID)
	return err
}

// ListOrganizationAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationAPIKeys(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationAPIKeys(ctx, organizationID)
	return err
}

// CreateOrganizationAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"keys:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationAPIKey(ctx, organizationID)
	return err
}

// CreateBillingCheckoutSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingCheckoutSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingCheckoutSession(ctx, organizationID)
	return err
}

// GetBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingCustomer(ctx, organizationID)
	return err
}

// UpdateBillingCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBillingCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBillingCustomer(ctx, organizationID)
	return err
}

// GetBillingInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingInvoices(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBillingInvoicesParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingInvoices(ctx, organizationID, params)
	return err
}

// GetBillingUpcomingInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) GetBillingUpcomingInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBillingUpcomingInvoice(ctx, organizationID)
	return err
}

// CreateBillingPaymentMethodSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBillingPaymentMethodSession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBillingPaymentMethodSession(ctx, organizationID)
	return err
}

// RequestOrganizationDeletion converts echo context to params.
func (w *ServerInterfaceWrapper) RequestOrganizationDeletion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestOrganizationDeletion(ctx, organizationID)
	return err
}

// ListOrganizationInvitations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationInvitations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrganizationInvitationsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "email", ctx.QueryParams(), &params.Email, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// ------------- Optional query parameter "first_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "first_name", ctx.QueryParams(), &params.FirstName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first_name: %s", err))
	}

	// ------------- Optional query parameter "last_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last_name", ctx.QueryParams(), &params.LastName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter last_name: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "first", ctx.QueryParams(), &params.First, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter first: %s", err))
	}

	// ------------- Optional query parameter "max" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max", ctx.QueryParams(), &params.Max, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter max: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationInvitations(ctx, organizationID, params)
	return err
}

// CreateOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationInvitation(ctx, organizationID)
	return err
}

// DeleteOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// GetOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ResendOrganizationInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) ResendOrganizationInvitation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "invitationID" -------------
	var invitationID InvitationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "invitationID", ctx.Param("invitationID"), &invitationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"invite:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendOrganizationInvitation(ctx, organizationID, invitationID)
	return err
}

// ListOrganizationMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationMembers(ctx, organizationID)
	return err
}

// RemoveOrganizationMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveOrganizationMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveOrganizationMember(ctx, organizationID, userID)
	return err
}

// SetOrganizationMemberRole converts echo context to params.
func (w *ServerInterfaceWrapper) SetOrganizationMemberRole(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "userID" -------------
	var userID UserIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "userID", ctx.Param("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"role:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetOrganizationMemberRole(ctx, organizationID, userID)
	return err
}

// GetOrganizationMembershipLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationMembershipLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationMembershipLimits(ctx, organizationID)
	return err
}

// ListOrganizationRoles converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizationRoles(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"role:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOrganizationRoles(ctx, organizationID)
	return err
}

// GetOrganizationSSO converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganizationSSO(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganizationSSO(ctx, organizationID)
	return err
}

// ClaimOrganizationSSODomain converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimOrganizationSSODomain(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimOrganizationSSODomain(ctx, organizationID)
	return err
}

// DeleteOrganizationSSODomain converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationSSODomain(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "domain" -------------
	var domain SSODomainParam

	err = runtime.BindStyledParameterWithOptions("simple", "domain", ctx.Param("domain"), &domain, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter domain: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationSSODomain(ctx, organizationID, domain)
	return err
}

// VerifyOrganizationSSODomain converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyOrganizationSSODomain(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "domain" -------------
	var domain SSODomainParam

	err = runtime.BindStyledParameterWithOptions("simple", "domain", ctx.Param("domain"), &domain, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter domain: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyOrganizationSSODomain(ctx, organizationID, domain)
	return err
}

// CreateOrganizationSSOProvider converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrganizationSSOProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrganizationSSOProvider(ctx, organizationID)
	return err
}

// DeleteOrganizationSSOProvider converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteOrganizationSSOProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "providerAlias" -------------
	var providerAlias SSOProviderAliasParam

	err = runtime.BindStyledParameterWithOptions("simple", "providerAlias", ctx.Param("providerAlias"), &providerAlias, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter providerAlias: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteOrganizationSSOProvider(ctx, organizationID, providerAlias)
	return err
}

// UpdateOrganizationSSOProvider converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateOrganizationSSOProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "providerAlias" -------------
	var providerAlias SSOProviderAliasParam

	err = runtime.BindStyledParameterWithOptions("simple", "providerAlias", ctx.Param("providerAlias"), &providerAlias, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter providerAlias: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateOrganizationSSOProvider(ctx, organizationID, providerAlias)
	return err
}

// SetOrganizationSSOProviderEnforcement converts echo context to params.
func (w *ServerInterfaceWrapper) SetOrganizationSSOProviderEnforcement(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParam

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "providerAlias" -------------
	var providerAlias SSOProviderAliasParam

	err = runtime.BindStyledParameterWithOptions("simple", "providerAlias", ctx.Param("providerAlias"), &providerAlias, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter providerAlias: %s", err))
	}

	ctx.Set(string(XataScopes), []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetOrganizationSSOProviderEnforcement(ctx, organizationID, providerAlias)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/api-keys", wrapper.DeleteUserAPIKeys, options.OperationMiddlewares["deleteUserAPIKeys"]...)
	router.GET(options.BaseURL+"/api-keys", wrapper.ListUserAPIKeys, options.OperationMiddlewares["listUserAPIKeys"]...)
	router.POST(options.BaseURL+"/api-keys", wrapper.CreateUserAPIKey, options.OperationMiddlewares["createUserAPIKey"]...)
	router.POST(options.BaseURL+"/marketplace/register", wrapper.RegisterMarketplace, options.OperationMiddlewares["registerMarketplace"]...)
	router.GET(options.BaseURL+"/organizations", wrapper.GetOrganizationsList, options.OperationMiddlewares["getOrganizationsList"]...)
	router.POST(options.BaseURL+"/organizations", wrapper.CreateOrganization, options.OperationMiddlewares["createOrganization"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID", wrapper.DeleteOrganization, options.OperationMiddlewares["deleteOrganization"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID", wrapper.GetOrganization, options.OperationMiddlewares["getOrganization"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID", wrapper.UpdateOrganization, options.OperationMiddlewares["updateOrganization"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.DeleteOrganizationAPIKeys, options.OperationMiddlewares["deleteOrganizationAPIKeys"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.ListOrganizationAPIKeys, options.OperationMiddlewares["listOrganizationAPIKeys"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/api-keys", wrapper.CreateOrganizationAPIKey, options.OperationMiddlewares["createOrganizationAPIKey"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/billing/checkout-session", wrapper.CreateBillingCheckoutSession, options.OperationMiddlewares["createBillingCheckoutSession"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/customer", wrapper.GetBillingCustomer, options.OperationMiddlewares["getBillingCustomer"]...)
	router.PATCH(options.BaseURL+"/organizations/:organizationID/billing/customer", wrapper.UpdateBillingCustomer, options.OperationMiddlewares["updateBillingCustomer"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/invoices", wrapper.GetBillingInvoices, options.OperationMiddlewares["getBillingInvoices"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/billing/invoices/upcoming", wrapper.GetBillingUpcomingInvoice, options.OperationMiddlewares["getBillingUpcomingInvoice"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/billing/payment-method-session", wrapper.CreateBillingPaymentMethodSession, options.OperationMiddlewares["createBillingPaymentMethodSession"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/deletion-request", wrapper.RequestOrganizationDeletion, options.OperationMiddlewares["requestOrganizationDeletion"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/invitations", wrapper.ListOrganizationInvitations, options.OperationMiddlewares["listOrganizationInvitations"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/invitations", wrapper.CreateOrganizationInvitation, options.OperationMiddlewares["createOrganizationInvitation"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.DeleteOrganizationInvitation, options.OperationMiddlewares["deleteOrganizationInvitation"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID", wrapper.GetOrganizationInvitation, options.OperationMiddlewares["getOrganizationInvitation"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/invitations/:invitationID/resend", wrapper.ResendOrganizationInvitation, options.OperationMiddlewares["resendOrganizationInvitation"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/members", wrapper.ListOrganizationMembers, options.OperationMiddlewares["listOrganizationMembers"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/members/:userID", wrapper.RemoveOrganizationMember, options.OperationMiddlewares["removeOrganizationMember"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID/members/:userID/role", wrapper.SetOrganizationMemberRole, options.OperationMiddlewares["setOrganizationMemberRole"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/membership-limits", wrapper.GetOrganizationMembershipLimits, options.OperationMiddlewares["getOrganizationMembershipLimits"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/roles", wrapper.ListOrganizationRoles, options.OperationMiddlewares["listOrganizationRoles"]...)
	router.GET(options.BaseURL+"/organizations/:organizationID/sso", wrapper.GetOrganizationSSO, options.OperationMiddlewares["getOrganizationSSO"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/sso/domains", wrapper.ClaimOrganizationSSODomain, options.OperationMiddlewares["claimOrganizationSSODomain"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/sso/domains/:domain", wrapper.DeleteOrganizationSSODomain, options.OperationMiddlewares["deleteOrganizationSSODomain"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/sso/domains/:domain/verify", wrapper.VerifyOrganizationSSODomain, options.OperationMiddlewares["verifyOrganizationSSODomain"]...)
	router.POST(options.BaseURL+"/organizations/:organizationID/sso/providers", wrapper.CreateOrganizationSSOProvider, options.OperationMiddlewares["createOrganizationSSOProvider"]...)
	router.DELETE(options.BaseURL+"/organizations/:organizationID/sso/providers/:providerAlias", wrapper.DeleteOrganizationSSOProvider, options.OperationMiddlewares["deleteOrganizationSSOProvider"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID/sso/providers/:providerAlias", wrapper.UpdateOrganizationSSOProvider, options.OperationMiddlewares["updateOrganizationSSOProvider"]...)
	router.PUT(options.BaseURL+"/organizations/:organizationID/sso/providers/:providerAlias/enforcement", wrapper.SetOrganizationSSOProviderEnforcement, options.OperationMiddlewares["setOrganizationSSOProviderEnforcement"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L19c9w20iD+VfDj76q8qaNGSjb7xzr1VJ1iZfOoNoldlr1OXZySIbJnBisSYABQ0jwpXd2HuE94n+Sq",
	"8UKCJMjhjF5sJ/rL8pAEGo3uRqNff08yUVaCA9cqef57UlFJS9Agzf9O+RXTVDPBT09e4RP8MQeVSVbh",
	"r8nz5C1nv9VAWA5csyUDSZZCEsoJa75N0oThqxXV6yRNOC0heZ6wYOwkTST8VjMJefJcyxrSRGVrKCnO",
	"pzcVvq+0ZHyV3N6myUu5opz9116AEVVBxpYsIyIYJQ6i6MwzCeR/k7BMnif//2GLzkP7VB12wTUrODt7",
	"eSJKyvgI8N+VlBUkN6+QrKCshNzAf3b2Mg6rfXdHRJ6dvXwlxRXLQR4XjKoRaMwzj8kN4ysiOBCxJHoN",
	"HTQ+Uwige1NvSOUGV3GYq3DuHUF/q0Duv/e1Akloloma6zhstRl/7z234CW3CKoEVQmuwLDUca3X30kp",
	"JP4nE1wD1/gnraqCZQaLh/9WuIrfg6nghpZVAfhnCUrRleMgWrCcHL86JZewSW5TxGgFUjM7F8sjlIVz",
	"9zGjJc0ucV8pz0kOF/VqhXhO+3hP29n74/5nXVJ+IIHm9KIAAmYa9zaBm6qgjOMMSDJMqRqGo9+GyP6l",
	"merX5kVx8W/ItEVqbFUSdC055OR6DZzQWq9xlRapBAmg1mshHa2SJWWFwjV9S/PX8FsNSu++MU8IbxGO",
	"M0mLSMIUKWmxFBIFl5AEEUoZV8QTbXDQoCBiSN5P6J+L/u+Bg2SZm9YLGDOkk0BG1rw6/SdsXkm4YnA9",
	"RNeFpDxb27+7w3/rnhC9ZsrLF7KmCmUmKEW0SNKEaShVRDo38FMpqRFLmQSqIT+nZkuRKvCvJKcaDjQr",
	"IYZ5/83FZgjf6Yk/fYwg12uqiXu/A3KSJrwuCtwhL74n5jm/hMm5PB7uNB3cVExGpjmhGlo28lOZt0GR",
	"v+C4hC0JF/a3zRdJGkfkVggslwx+LqjS57WCCA+9YSUoTcvKYwLfJTif+R8Cek0V7kUeQApXIPeH0h7D",
	"ETirlpwjzwRyTISiX7kn90XRKhOVEzozv+lxO8u9rtEuqcMoDamEW9NMHKw1bRl5KDrS5FtWFIyvXqwh",
	"uxS1PgOlmOCvvcgYSIVaFkP0nWnJKiCZG4QoOwp5+/qHcIdrybaKORx/Ck5RFJDhtD+CXosINf6nuCYX",
	"9mVS0U0J3Bw3mf3Q6cl9zXSB+OR1aSDgl1xcc0SmWda5G+W8tDOmSUnlJeiqoBluzwXll+daUq6WIAPY",
	"3QLT5OYAhz64ohI3VOEcI6t520w98oJF9CsL0I8enpGXf+yAOfLSt5RfvmmADxAtIWc6cirQgvIscuK9",
	"htKdaZn5lLg3Fx0eFzVydYMjXpcXII3gWy4RrCs4RzmwTQD6KSATJaBoQWGxGJMmI1J2l5mcpE1RWTEi",
	"DKnIPlNW4ueCcOFfXNy3+C3pDSvr8pxxphktzke34dS+0NsEcgFLIYFQvkFkrebuitJU12bfPXdQs0lJ",
	"mlTAc8ZXnjuSX7dxthFpHu7Bhnc3ZXzBDUxTQsKs/QS0UeEHJGyXcO52b4jCF25br5leE/sysZOmhBIJ",
	"NFtDThr4CUKckkooZv7rIE2N9sgFqfA0tItbhIfI1P2wy4SRAyanG3Vec82KcyP+O2s6H9ciNoqYr9pz",
	"2i0wpPNNS+aeDySqqbiaZa1rCdGvFuP0zbiGFcgY5G7bEdnjVB0D3CP8wNP4jkuY/n7eYiZxv58ACJBy",
	"L4MMMLvfiFpoWpwPWWeGELGfFmwJONlOH/dEyMhIXaRNrD7t8/7UDo6seSbvzSP0KSFWKy1KkOOqmNNy",
	"zvHgLTrotL/EbjOUnztNqBHc7XFzIUQBlJsXGzXBqz0oOIvi5TJ5/ss82dXX1G5/TQcqA80PBC82pJ2O",
	"2OlIJviSrWo5qrDZuxliPG8F/WyZ6g+HZpSusn432QxLWhe6rzfuisCuljfE3ps1EKd4uxlJRmXeKL12",
	"2tTKP8HBasENVvF0kqAlgyuvPHWFwG2arKmKrKIHhqxDdclRrb07EWvM2Q7lIkkjRBjq2bOxF5rTAw3Y",
	"G7IjiAzeakzSjuiY6lAd+QssVgvyPqHX6n3yRYoXWeRCc9GXol6tCSXd20EPpz2B1mXh/s1iyIRxDo5u",
	"1CgdthQ/4KAJcXTKrwTLIlKIlqLm+jyvY8c2ZKykBbHvkLyeq3dmtZTAs01UFx5RkZmFsNHq510F/Fdu",
	"7qmBq3yJz7celUOlOZd0idtkLH24AxU12vCVMP+oDc8gn6lB9wBOww0IENfDRwNVdznbN1yNnz851XRX",
	"qelGjYnNiq4Yp57aqR99atBXzSc/+i/6ODM/xgefWHxX9g5WjhJs5oI7I73A7/oQmsHmwvKCygg8aOGJ",
	"M4VTOkrB9Tp4IVBh3RsboDL+AiovX8e9bB1RZmDwr/dm7k4zd7F3MkZ1D5gHNEm9rTJRtqQ9Du3DSMp9",
	"bOdT0nUtFI7npYRDcQ9h22VgfWG05/GV+jdmrlNTuQK9o3DfAsL8+fssG9phx+RvCHGAEA9VFNMxMnuB",
	"/v1Qq2miA5xbMmaLMw+QBwpBrQZtwgSsU4tAGD/Qxg30xLt5HPH+UAndEbSwo6dmLOeMJjQrYZGJckHe",
	"sSJHKaeM0lnVFwXL3AhNCADBUSX829hoF1t50gEXxZfZHOvcCjA017n1AyuZbs3+qNUqIM37U16Akt6c",
	"2od/Oxqeb2NGme/wd6teIq001x3nhUhbe2Pj3XkIt8mYaySOj6p1L+yLj9ZH0p3wpfkDJYR5gVCl2IpD",
	"7iYPvGn7zdyjJIOScTrqROc0MUmjdNXcxWMBOzTPJWKx45wUNhQKwj0dvb9LUcA2xSOE+LUo4CdcYH/V",
	"doZ5y95NzODnRswQDtf9KKousjw1dkdFeBsmiIwxLRh22M4gvGmnJUpYMaVBOmE6CGdy0URXINmSQU6a",
	"2KueElkwvJXFohJeYhgQsS+Q05OB9aMBAXJrpcYX/PTRE9/OpSCToLfMZ19akHeSaTDmmeeEGR+a0gJn",
	"ZJz8EzZZIeilEehMWW9uG+9xsWkcqYsYOGNHC5o0GrR1jxgcrkHwNSsKokBeQXR4c82SkWWenryw0RYS",
	"9cAFee0Ix+zYB8Hy7IM125v/lyyTQoml/kCurflYE+PBM+j+jmtJiQZOuf6GsBUXzUArIVYFfFiQH2uF",
	"Tiqy1rpSduQSfzKgE0oOF9dQFAfG6XcoKuAsP/AmGnciiKw2aiyn5vBmWkGxJFS1kSNysVWh9T/MFxwB",
	"b7zBTweWWPwxbcMKW2LuE1uMF/9RF4U9oJ/CTp7CTp7CTj5e2EmaaHEJI6KYZrqmRUth5s1ZRqo9Ilf8",
	"6DtHsATm29fuWNx6nGvRHKHOzUuyQtR5z3jbu79fR7bw+N3ZQRM3HHxNvE11MIoNK46e+8fvznzYMTHR",
	"xZGru7Wvj34eGrP9yyNjVVLkdaZnDeXejY7UvxwHIHYmScO1x3YSzyTKN+dxvfCFfWqO4EY/DDFud1SO",
	"6Il7uhMG1GXHn3AnIOcMiKnVzgZxnT2Tf4CC1JDcLJrvQTVAXtTHgUKm8iFRIfbCcKguCFNBTVuAOn53",
	"ZgKMQjUjoqMFTz0PEcazos5R/zk9sWEVXr4M43t3SbX4Q7qY0pF7VS8k2bBRJEkjmfRozNYf7RdTh8NE",
	"HE9vn0zikdYgcRm/0IP/Oj74n0cHfz8/+F/Pf/3vCC/TuPr+ZzGiFbRiB5nIYQX8AG60pAearszSjK/S",
	"mBeTNh58mFDU5i0N3QIdhXJMW2nUqTbFySgq7uv5QWw7mBrMVJAbxXSWocGpeHssxX05exlLJpUeEfn/",
	"wGcdSu0tZKZaOSf9p7uMZCyoJg7oD/SOcIYceL6PINvfMhSyd+/ENcZs7YLfOkvzSPKnhIsG9MrdbG9m",
	"f91pQ5JDjdGSY+DJNGveJj9iAnrm8aiUyJi5T1kdkY/GDM8/JLeAFjskfwTvmp53PGFy2Tum14Yw+jLq",
	"3iyII8gfHH3HpDTwI/n0MGiOciQpHAv/2JC1KIyBiQ330Yyi1qwyFukIubZvkMK84nNNJ42QaCo2zBob",
	"0QahEl77FTg6D5hAEVoU4hpyQjURNsqsZBy/S55/2R5Os8ZKYkGGJb1xS5sDocV2CxXjsSN+HoSdzXID",
	"R0AcaLQNvGmI3m2c+tqRZp9+HHVQTTLKjTkNCmNjpOOkNfRmhYP2/pu8w8EbQjSYU8noabKPiN1ZJTPs",
	"tctdOxx5DqZ/ikL0xk2tppBr9gE5NZSAeWkMgZAzLSJpED0I0OE43GreTxdWjK8KIOgAOhCcKNB1laL1",
	"U3B/gIeG9wpk3H68GPFuquncatVJrh7o6mk7mXFsWn6eHeQd9elGI2OaPOmhHbCPAxX6BkagppqUQmmD",
	"xA7KWmTts4D2/rPF5Rbmfft92EayLYJiZAOxhHiUED3C3dXXbe/ydrhwjhFzilnVOTX56tGxzKO400g4",
	"J4dbhHFxXABZsSvgC3ICkl3hjkpRDt1B/hy136ZECeexMZ4Fn/wROokI3DClFUaHsmyNr16jDCxAK2ML",
	"s56gtbg2X0nImYRMk7evT4e2s864dYUwch11zFhCy5rr0+7X7YYM/hUOFTfCnPx0RiRkQub29EAYwcTA",
	"aikKL2gdzZPjCwXcnuDB74gZzx7REFn/MHaogF6DjM9njLwXANxCxZvL/clPZ5FY2BEGcqQW+GEacGbz",
	"0796exLH45uf38RwOTgY7FqRhka8nnaQ8wnXrxbuKuxIz0xqFP+hO9wO5p1bPd9FsP3WWzX2/RUtYjFZ",
	"/8KfQyCM786de9MHc7jKLpi9SWds03d8KWQGPlY/TmRe60Nh0DDjs0aaGMjxFCWsJTWmh8ci2MlimfLc",
	"6ChaEAU8J+hH2bRmBh7SthZdf+2CnDDlvy5AN9B6iNbiGsezV4BM1EXuZNZiOy80EM9A5fgF8DgmktFN",
	"O13OpHdyqgWxJ0bgSDeytXGlxx3mw30YOUPOtEHjwHQRIDu1Hi9zh1IExT/wvBKMa7WYCA249zCE6GQ5",
	"U1VBN1Ps39AGwHBx1uKEZGMvTg8SXYDbDnFkjbNHhBHD45xKIOZ86fMGobUWJdUso0WxSUkB1NAcF0SY",
	"Aa/pBhdKXodRJ+3nuQBlEk8VaDPyN+7oB8OvOVFQUUk1FBt7tlGrTXfkgDmNroW8hJFMjJkRFakhA1Hb",
	"y1QY3UBUvVyym48RquDPSB+yEJJgcHI2WxuyxA4y5U30EHpn1auBaDE0wNSiCRYhFV43jBtbrKwMpeR7",
	"84y8E/JSVcap6KiJ553wFPOyuyuFcSkp0fQSeKs12q36xsW6IJngr0taFBc0u3T2ko1eI5FBody1W1VA",
	"LxV5WQE/PSEvBOeQ6dD8ZddgzAoOpiRNcIrt98DG9NiTf3idPJdAVUwreW1+b8y2mbNTmo9IYx4cTOyz",
	"bXYc1n02Y+AxQ+opz1lGtYsc6ppTu/cT3CjazFiBRN+yy7j22BaXSZpwMczr8ZHE4gqkDUduaxnkUIAx",
	"sroSPFELbbqrC6MD/D5OjNwqBibQxWzfFPJYBGONHu1Hctc+b48YyjIbdFDlBs6ZUSX2dR+B2jdSeLqY",
	"t+TtRHLtzpLBYplyidcpYfoZXmXKqtaQo0Xkw/83wCU5/umEdGmT/Md/kGfi8tmHgJ7cSZG0uxElDVM3",
	"4Fyz2DnwFp8RfBYj6wXRX3pZ45MAkcn6wZ0qJforwoKQX0NoPo2wl9HBzCG7ZDZ30S9Gf4k4/2q7+6HZ",
	"tSEJDhi6s/geBcWOiEhe0kDCYcpeKSTE82853OjzrJbKVrza4j/qLa0ZujtODNIz0EMjO5oHd4qIVaC1",
	"r2ZlTKgRm6FVjIb3wQf2R6TJW7NRg6zqscSAXZOqJzM6x+G5n0Bk9B2NhSE/M9LY/EojcUh/4vDjTyU+",
	"eNdEtN2CbN+q2BrxV8K4ndecKU1sjSHZlCwxVBLXYZdaSYEylrCSroYxN7OCEPqO1CZEti2xuT0iYeLK",
	"GETdzssPSCfyH1xpztlFQ3sLmRWo4ua4twCVwOO7k5fY+If72UgaeO4iF4hFi70FWEJx1F1bbJiXAmB2",
	"D8lqKqEOPFsR37IpdYjE66tA0ky3iSSJqqtKSP0/bqimCyaS2xbjx91qn8evTq2xVNlVf7k4wrdFBZxW",
	"LHme/HVxtDiy27k2KznEfbmEjVPcCoiWjjK/k7IuNMMUOBc5q1BmNRc0p4Aj9yOqbAxH3nyNCLGx8b7m",
	"LSj9rcg3d6p8GYtclZJukHcclOT0xCR42cWRv7gKTORvR3YNlRGxBpwv7iv5CgGLF7Ts1tXtl8n96ujr",
	"yIJeneLJoNwKcqJqE0WNAs340b4+Ohojx2b0w365V/Pdl9u/ayv3mi++3v5FWNX0Nk3+9vPPMakDN5Wt",
	"W+dexBsEZLVkemN4/MZol78kuEfPjaEx+RX9IaouSyo3mDdRF5d+Vxsc+UtuUAa3DVeyEueXBqO4RzcH",
	"DbUeXDKOBJuD0rK219PbNFlBVG8xJUaAUFIwpQN6m4JhyBw/MKX7rNEhiKM78EfL11MM0gLs0DTLSdqt",
	"srrNNXrpsL21xOsPfWS6Wi4flezvg4Ql0LxPwWax90q6ZhZ02oqYsm1zBV0KoxePu1CrHaCl1ztI8ina",
	"iqU6z5KeX96NWbbBFeR3RQh8Fn27/Wsymj5voo7K5YbKjE7uFjyfhO2YOO9hEA9+6O9mZuOi1P0D45dq",
	"hJStKXmYvqDqi2aIBXnJjTdhPP3CGHFcABrqDXEu8S6NbqHSh2CUiRyhWfxyNB0y2ll6S6mPrXP8fXed",
	"4+irO0iCoPr5/dUuH8VrmzdBWQH5OMcFRBlnvNczUr88E4a0afgQbsw1qGn4MM2ZHfNmzCXJVOOfdS47",
	"FeTQ89xoTfh3ZyQDOePkZ7zpkJedR9SF+mhRHRRwBQVxhiEbQukr7fv0urSpbWHv+xpo6b2Yi2SbVocT",
	"eb2OFkUPyhEZcwGF4Cu8bKSB+UGvgUlzCfEZPsadHiLIRmaaQfBrgipVfFrMokSl06dRDoXP913Lp0Id",
	"4361yi177zW4IcoMkkazQO+e9PTZ5wdNqtBdtM8ROS//+Ye/HQq5imrW34Nu+LeLuFYEvuwjdE99WkVq",
	"grQGwYicoMrEsDi7ibjm46r2yy6FPpyyHSuMcnt7e1cVey7fRMk3xGeoJzfe2D8DdU+r2LE6MjuQtzvR",
	"w6E7n5EfKacrG6M3OPYPf+92CrudMiH+8pPQxCAHB4OcbED/Sl6BLCnisNh4S04/G8kelTTzAfpcmNIj",
	"Nc8FhzFj44BtttnYxmnNgvXotPbXz5g6T6I7uSNp9oxwU/ql06AVaQZRU13vUqtvoW7mCwUXqQ2FYHyV",
	"uu5INqwk5vG92BjxXfcdJ9u1Spv3bXx9raOKXohaj8HqJzs92arp3VXJuzdR7bPbPwXL3WfDSGNKjIhg",
	"dl8dJmhyOeJEa185jHWbRPCqOkLh1vffIWuXo2jyMfr3vBQpYu31INSLh9Q9DCe4R7fRfd0tfoLrbt2O",
	"LTXdohrV0SegUfmonyfmnH3KOZq/BwbdooWRl/4DNUMJezSHbgjiJ+DYfXLd3jfr3KNHdlwVfARX7Ihq",
	"FffFjlH1R/PJ9vD25Jv9HA+RHTzAe7PKPat5uzmQIzVEtpmznjzI9+JBDrht+B5uj6kZ0rR3E7LpRSwb",
	"vOzt4uUdH82dfL1btBoXf3zoe3EeuMYH/e79D0PxaOIdawZq0hK1sBkMiBXTB8jBuwtzxFuWPuS1fkuT",
	"1AjxuS+GWPhIJtm/Pm7Qw3aD7MUIggKecDi8s9t1gklcNgAudVJlUi287pPGeuP1D6c7GdExRcPfg+7l",
	"IjwG5fabyU2RbG+Ff1KD0tiG34FA71nzoDpbj5mY7pFgo/kzD6SOTObqzI/U+eis82Qm2tdM9ABst/u5",
	"4BJp1Q7ngv/kDueB77iWDCREr2p4k11IbGafTxs25bZFrYjfvCRNGH7xWw2m3rbLk7BfmVrbnhEG8VsD",
	"C25TFK5ZqRZkCSiD4rMYfbozicv9TJ5/ddQ0eE6ef3l01KtH1y8v9+vDc/mg290ElzfU8cTdcw9Uc33v",
	"s8oncpLuIRcOa9fzbYaAMAFd7vU+CrYIi2eqaT/eDb8dxPs1+6OFC3wLSrzFxpgQQ71+do+gnY510Ivw",
	"4NsRTP5JldQxwvr8WMsl9x/Y5P6PZrUwFSYPSpFPGTByYx5yNSH6UQ/DxsYTNoxYu8tHYLjJLpsTJ99I",
	"T80nm0bXphFH06NosD4e50AGBQ4ekIH+UdCVitSxEbIJDbI10Rw8hKmmy2O0novSWPjSBj+bY8vHqS/e",
	"8zfr7imGg2WUZ2DaI7CyhJzZSleU54TyDRG1VpryPBCN9sB0LbQh79bfInSpQRJKVtKUAgfJRFPxEK4Q",
	"V6RkCh2/uD66MaGqdIXrq4Q0UJ64dZvqLAUY8aI2PFtLwUWtmjpcRdEFyTaHNqAr0LqAfPGeR3JmDB7D",
	"XfITDgXHVyMebVvDwdUBIv/3f/+fSDEfV39UQinQcdXAPIpSB/SnrxX//ZO587r192Mjmu3cOw5whqQI",
	"q45v02I9sfoPYtZ6G8ktfPPOJStcsbqLjauQlPoKEz6/Y7tn+bRTGn3yVvwPM2EHymbmkRtq87A9PHfr",
	"ZzAPBgiLYYyA4ste7HAjj0+2bFpmjMwU9Nu4h+kKOj1bQfea7AyozNb9ySwihZyaUJkvd5vtlOdw43Nd",
	"LAIlKKxSpYWrKkP+cnRwQVEBFMulAlu/qm0q/8UUsuM2kNDocRSrqb+91L8FUrVQjkBR0ps4DNb08niG",
	"mF7wUlcC7VxyvBUOW0M3wql2ieAICfApiGPmcWeQBuN2oC0HyceN2o1quWdg9MlOmyMji0y2tM+b/rdg",
	"vL+YOQEep2FDncfJXBp2sp4f9NGXnQ1KTH3bPzpvfAT10fFTVIOMUOYIJe4Xa7ubInn4e/ufLXlO8Yym",
	"YBm2TPqcoNoe/2yLNW1f/ySiTT8fgb4lh6nbPG3/DKb7SA0K6Gh+YtAUHT1M7kGowQyVkA6hPqUK3ZcO",
	"gnZzj0+xjFPNx9NB0q2fnQYidgdD+7iYxk0Ant+TqXC/BYxpXq8NaOjbHjRL89U7lhLU2radtL9rFjMt",
	"2JHu59yQ8KfQdR7w2PD7eodjY76GUrbd89zhMm11arvX3eNtNwBi55uuBWjrLddPMbfmxV5e/KbBxfIT",
	"urjNJ4LD32tTcbSnnPZlBRq9IzswR07YV73hfLZcuPM9Yw/rM0LYNvqzUUT3mYz+KMeJrSB7B0o49DXI",
	"PwK4I3nCr01lbxc9YuF9ppqGFAjvghz3m6kW19TmGpn6TqabG3UhIMd5ySK2iNHq7w9kiNhabX7f/EEc",
	"Y+egywHHPVkcnMhAAhuzN+h5Vf4npMbQ4c24BslpcS8u8LJpA3xQNJ2CZwRpldH2wePRWW2FZPelrUbf",
	"qtlfbL1xDnoaP9K9czBvrA7fKDo658PnE7sxq3LEgAg+baUG2XCCvkXhfPOVhByWDFvNke9M577x5r7Y",
	"4FARuKGZtlU+t7tpzUT3qy43K9tZWUZgtqrKdvhdXEG2J40pjWc//uNe3Iz4H70A6LZFdIuSXe3Ne50B",
	"j8xcSolR1kJMqFgzKDZsyOy788JEZ2kohwodIlcRxt9z36nPNGyONrsOOv9eCL0OY5xwcQvyIuyuYoVC",
	"rysl/mQaqbznTV/KAUwmFAqjs3zLwaZdXF2RDWiXepAr8tXRkbXQQFnpjak4oAx8Xx99TUqgXBGcGhfn",
	"mq8vgeraBEKRmtMrykzLo1gQVO8YtR2dH+XkxKkiQuLs7CXJBF+yVS3bCLiPdVh+YkHKES4Z4OsPIS0O",
	"g6byDxq1jKLDNF/udDFFJracayXT9v7XTC/IsZVEtp0aigJkbSBavOeilgqKK1DP8TfD5azTX56ucLk6",
	"7P1bc80KEjb6tmZSyC33m8lsD1P3BQem1yh16HIJGcomvhEcnqmmUSkXkigtKnxkm6J2m077IZm20Tu4",
	"qAYnkQ/WVL3ntEAC2YTLMYtbmjBvI7m+Pvp76punU74JEcoUqeqLgql1PEzTbFG8f/0D+fhHJ3zAsg47",
	"d22Pyc6TTtf+tLH0X3U6vD9FEjxoCLsRAX2BgmeYPVs/3m0+EKuHv9s/JuMKTqSREw0VGbJKiemWh/Yw",
	"k+zRU5tQLgV9m5me0Zj8PX8digqKwoJcr1kBYXdm07XORFKLmue+f2ijrDGegYPLya+a5yA5UG2VvWuc",
	"8j3HptCdcbm4EPmGZJTbgiXfOHNzpxOfF4anOZSVQI6OSaphPEVXVG0zvTn2ddjNnzhurvHd4ItQL/iQ",
	"RHt0+QCM9zEM9A097adNNWx/aNCzeTRL/QDuMX3sByEuFV6AkPuyNS0K4Csgb35+46OYyL9ChYgZASWK",
	"IjXXKIqZIiXl+XNCm+wSo/LQAtwIVjephNSQv+fY7tfTynNs363gA0ouam5dkrruwZQTatVEJFKjflHf",
	"ZtOKDi03TmihblNJUdEV1aAcwBvGV++50xsHKSJOkVSh+mdC+52uWAoJpht906M+W1NEzFpcOyWvuePG",
	"JJMFYaZkOnp8xeWFc8cobepbLjt4MHlEJoUQUXHy09mTYJypiiDO+vcXW57QS8oHk467qSWNheeh73u+",
	"X42K9vk1yEFe6p0ei6bRLOF4/bLXOyOi2rbAhmEr5m6MhVgZc5OwF8bvzefknZCXqqKZJ+5vXCtc39J7",
	"SYvigmaXdpf4htgrVwMfTpEzlQnst2mC8XxFcmV8zmgCculv6OX8cLi4hqI4MJ3rD0UFnOUHHWPBB5tS",
	"6FitrJUm/jZ30aIhdRdiizuTsefkEBq4ciYh014MGa1PYYuJ53bppmy67SevADcO0wqjFz0J492cHy2e",
	"O9JB+uNe9xoMxOIaBxTc3sGfLnoPrXZaTI9LEvoIWuiecvbwd//nccGout1euVl1LkTp4KKnmqsuZjga",
	"IebuaN72ZHO4m55Szf0vkEDvudIYedHgDeUO6lcXQFbsClorlAdkrztZR6hsDVaM8FgQj/T5Jtv7oKUI",
	"+f5xrkuvQjLfJVQo3vs/6FlvD24JB1MHMmnP485Jy/R7rkDiZQAHvF6DoWrmjsulkBlYP1JGpTSckEmh",
	"0J1jNf/ccKAU2rW36/b8b+8Jv9UMtPEN1ZL7kU1JBbFcxhhm2ATh4U/hyTk/Us26O53CT0Xr9i1aF5NG",
	"XRb8dA/Rw4C9HtO0souM+w5VcZQYCtC1DCaCxSXUE8H7os+JKy0I0ylB46ntLylUE+VFuHDXlGu6QfsD",
	"cebc9zyw51pnVnCtZ+0pvyAnTDmw7P3K2T2MjMNvcGRRa9sL18Rmigqilo6zgT/bY+e7YHMeRoz1Jg4n",
	"/JyElzW4OAMcX8HThWB+CRImIVSLNTYNi7KTd4v4eBSmH1Cu3TZDD5rQdduX+Xa5qU+PM3/H+pT12+i2",
	"JRK6wN+mW6YsKacrHM72qcwyUXPtjClSLFkBwdgY8b3LmL5tRNgc165R8NT3A+62X2snawrJb52vYPxy",
	"uAQttnT/DhYW9kaOVdWwW93r0+ZqZDXbHozny2Ld/nr7/wYA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
