package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	outputFile        = "scopes.gen.go"
	securitySchemeKey = "xata"
)

var echoParamRe = regexp.MustCompile(`\{([^}]+)\}`)

type OpenAPISpec struct {
	Paths map[string]PathItem `yaml:"paths"`
}

type PathItem struct {
	Get    *Operation `yaml:"get,omitempty"`
	Post   *Operation `yaml:"post,omitempty"`
	Put    *Operation `yaml:"put,omitempty"`
	Patch  *Operation `yaml:"patch,omitempty"`
	Delete *Operation `yaml:"delete,omitempty"`
}

type Operation struct {
	Security []map[string][]string `yaml:"security,omitempty"`
}

type scopeEntry struct {
	Method string
	Path   string
	Scopes []string
}

func main() {
	if len(os.Args) < 2 {
		log.Fatal("Usage: go run gen-scopes.go <openapi.yaml>")
	}

	data, err := os.ReadFile(os.Args[1]) //nolint:gosec
	if err != nil {
		log.Fatalf("failed to read OpenAPI file: %v", err)
	}

	var spec OpenAPISpec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		log.Fatalf("failed to parse OpenAPI YAML: %v", err)
	}

	entries, scopeSet := collectScopes(spec)
	validateScopeSuffixes(scopeSet)
	generateCode(entries, scopeSet)
}

func validateScopeSuffixes(scopeSet map[string]struct{}) {
	var invalid []string
	for s := range scopeSet {
		if !strings.HasSuffix(s, ":read") && !strings.HasSuffix(s, ":write") {
			invalid = append(invalid, s)
		}
	}
	if len(invalid) > 0 {
		sort.Strings(invalid)
		log.Fatalf("invalid scope suffix (only :read and :write are allowed): %s", strings.Join(invalid, ", "))
	}
}

func collectScopes(spec OpenAPISpec) ([]scopeEntry, map[string]struct{}) {
	var entries []scopeEntry
	scopeSet := make(map[string]struct{})

	for rawPath, item := range spec.Paths {
		echoPath := echoParamRe.ReplaceAllString(rawPath, `:$1`)
		methods := map[string]*Operation{
			"GET":    item.Get,
			"POST":   item.Post,
			"PUT":    item.Put,
			"PATCH":  item.Patch,
			"DELETE": item.Delete,
		}

		for method, op := range methods {
			if op == nil {
				continue
			}
			scopes := extractScopes(op)
			if len(scopes) == 0 {
				continue
			}
			entries = append(entries, scopeEntry{Method: method, Path: echoPath, Scopes: scopes})
			for _, s := range scopes {
				scopeSet[s] = struct{}{}
			}
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Method != entries[j].Method {
			return entries[i].Method < entries[j].Method
		}
		return entries[i].Path < entries[j].Path
	})

	return entries, scopeSet
}

func extractScopes(op *Operation) []string {
	for _, sec := range op.Security {
		if scopes, ok := sec[securitySchemeKey]; ok && len(scopes) > 0 {
			return scopes
		}
	}
	return nil
}

func generateCode(entries []scopeEntry, scopeSet map[string]struct{}) {
	var sb strings.Builder
	sb.WriteString("// Code generated by gen-scopes.go. DO NOT EDIT.\n\n")
	sb.WriteString("package spec\n\n")
	sb.WriteString("import \"strings\"\n\n")

	writeGetScopes(&sb, entries)
	writeAllScopes(&sb, scopeSet)

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0o600); err != nil {
		log.Fatalf("write error: %v", err)
	}
}

func writeGetScopes(sb *strings.Builder, entries []scopeEntry) {
	sb.WriteString("// GetScopes returns required scopes for a given route and method\n")
	sb.WriteString("func GetScopes(method, path string) []string {\n")
	sb.WriteString("\tswitch strings.ToUpper(method) {\n")

	grouped := groupByMethod(entries)
	for _, method := range sortedMethodKeys(grouped) {
		fmt.Fprintf(sb, "\tcase %q:\n\t\tswitch path {\n", method)
		for _, e := range grouped[method] {
			fmt.Fprintf(sb, "\t\tcase %q:\n\t\t\treturn []string{%s}\n", e.Path, joinQuoted(e.Scopes))
		}
		sb.WriteString("\t\t}\n")
	}
	sb.WriteString("\t}\n\treturn nil\n}\n\n")
}

func writeAllScopes(sb *strings.Builder, scopeSet map[string]struct{}) {
	sb.WriteString("// GetAllScopes returns all unique scopes defined in the OpenAPI spec\n")
	sb.WriteString("func GetAllScopes() []string {\n\treturn []string{\n")
	for _, s := range sortedScopeKeys(scopeSet) {
		fmt.Fprintf(sb, "\t\t%q,\n", s)
	}
	sb.WriteString("\t}\n}\n")
}

func groupByMethod(entries []scopeEntry) map[string][]scopeEntry {
	grouped := make(map[string][]scopeEntry)
	for _, e := range entries {
		grouped[e.Method] = append(grouped[e.Method], e)
	}
	return grouped
}

func sortedMethodKeys(m map[string][]scopeEntry) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedScopeKeys(m map[string]struct{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func joinQuoted(strs []string) string {
	quoted := make([]string, len(strs))
	for i, s := range strs {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
