apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dev-services
    releaseName: dev-services
    namespace: xata
    valuesFile: values.yaml

helmGlobals:
  chartHome: ../../../../dev-charts
