apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: branch-operator
subjects:
  - kind: ServiceAccount
    name: branch-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: branch-operator
  apiGroup: rbac.authorization.k8s.io
