apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: branch-operator
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: branch-operator
  template:
    metadata:
      labels:
        app: branch-operator
    spec:
      serviceAccountName: branch-operator
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: branch-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: OTEL_SERVICE_NAME
              value: "branch-operator"
          envFrom:
            - configMapRef:
                name: otel-config
            - configMapRef:
                name: branch-operator-config
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
