apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and .Values.service.type (ne .Values.service.type "ClusterIP") }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
