// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package orgsmock

import (
	context "context"
	orgs "xata/services/auth/orgs"

	mock "github.com/stretchr/testify/mock"

	spec "xata/services/auth/api/spec"
)

// Organizations is an autogenerated mock type for the Organizations type
type Organizations struct {
	mock.Mock
}

type Organizations_Expecter struct {
	mock *mock.Mock
}

func (_m *Organizations) EXPECT() *Organizations_Expecter {
	return &Organizations_Expecter{mock: &_m.Mock}
}

// UpdateOrganization provides a mock function with given fields: ctx, organizationID, request
func (_m *Organizations) UpdateOrganization(ctx context.Context, organizationID string, request orgs.UpdateOrganizationOptions) (*spec.Organization, error) {
	ret := _m.Called(ctx, organizationID, request)

	var r0 *spec.Organization
	if rf, ok := ret.Get(0).(func(context.Context, string, orgs.UpdateOrganizationOptions) *spec.Organization); ok {
		r0 = rf(ctx, organizationID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spec.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, orgs.UpdateOrganizationOptions) error); ok {
		r1 = rf(ctx, organizationID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Organizations_UpdateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganization'
type Organizations_UpdateOrganization_Call struct {
	*mock.Call
}

// UpdateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - request orgs.UpdateOrganizationOptions
func (_e *Organizations_Expecter) UpdateOrganization(ctx interface{}, organizationID interface{}, request interface{}) *Organizations_UpdateOrganization_Call {
	return &Organizations_UpdateOrganization_Call{Call: _e.mock.On("UpdateOrganization", ctx, organizationID, request)}
}

func (_c *Organizations_UpdateOrganization_Call) Run(run func(ctx context.Context, organizationID string, request orgs.UpdateOrganizationOptions)) *Organizations_UpdateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(orgs.UpdateOrganizationOptions))
	})
	return _c
}

func (_c *Organizations_UpdateOrganization_Call) Return(_a0 *spec.Organization, _a1 error) *Organizations_UpdateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewOrganizations interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrganizations creates a new instance of Organizations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrganizations(t mockConstructorTestingTNewOrganizations) *Organizations {
	mock := &Organizations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
