apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xata

helmCharts:
  - name: api-gateway
    releaseName: api-gateway
    namespace: xata

helmGlobals:
  chartHome: ../../../../charts
