apiVersion: v1
kind: Secret
metadata:
  name: projects-secret
  namespace: xata
  labels:
    app: projects
stringData:
  SIGNOZ_API_URL: http://signoz-local.signoz:8080
  # SIGNOZ_API_KEY will be set by the signoz-projects-setup job
