apiVersion: v1
kind: ServiceAccount
metadata:
  name: signoz-projects-setup
  namespace: xata
  labels:
    app.kubernetes.io/name: signoz-projects-setup
    app.kubernetes.io/component: initialization
