// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PgBackRestGCSSpecApplyConfiguration represents a declarative configuration of the PgBackRestGCSSpec type for use
// with apply.
//
// PgBackRestGCSSpec configures a Google Cloud Storage pgbackrest backend.
// Authentication is Workload Identity only: the operator renders the cnpg GCS
// repository with keyType=auto and stamps ServiceAccountEmail as the
// iam.gke.io/gcp-service-account annotation on the cluster's
// serviceAccountTemplate.
type PgBackRestGCSSpecApplyConfiguration struct {
	// Bucket is the GCS bucket for backups and WAL archives.
	Bucket *string `json:"bucket,omitempty"`
	// ServiceAccountEmail is the GCP service account the cluster's pods
	// impersonate via Workload Identity to access the bucket.
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty"`
}

// PgBackRestGCSSpecApplyConfiguration constructs a declarative configuration of the PgBackRestGCSSpec type for use with
// apply.
func PgBackRestGCSSpec() *PgBackRestGCSSpecApplyConfiguration {
	return &PgBackRestGCSSpecApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PgBackRestGCSSpecApplyConfiguration) WithBucket(value string) *PgBackRestGCSSpecApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithServiceAccountEmail sets the ServiceAccountEmail field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountEmail field is set to the value of the last call.
func (b *PgBackRestGCSSpecApplyConfiguration) WithServiceAccountEmail(value string) *PgBackRestGCSSpecApplyConfiguration {
	b.ServiceAccountEmail = &value
	return b
}
