// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PgBackRestAzureSpecApplyConfiguration represents a declarative configuration of the PgBackRestAzureSpec type for use
// with apply.
//
// PgBackRestAzureSpec configures an Azure Blob Storage pgbackrest backend.
// Authentication is managed identity only: the operator renders the cnpg
// Azure repository with keyType=auto, an IMDS token request that resolves to
// the node's kubelet identity on AKS.
type PgBackRestAzureSpecApplyConfiguration struct {
	// Account is the Azure storage account for backups and WAL archives.
	Account *string `json:"account,omitempty"`
	// Container is the Azure Blob Storage container within Account.
	Container *string `json:"container,omitempty"`
}

// PgBackRestAzureSpecApplyConfiguration constructs a declarative configuration of the PgBackRestAzureSpec type for use with
// apply.
func PgBackRestAzureSpec() *PgBackRestAzureSpecApplyConfiguration {
	return &PgBackRestAzureSpecApplyConfiguration{}
}

// WithAccount sets the Account field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Account field is set to the value of the last call.
func (b *PgBackRestAzureSpecApplyConfiguration) WithAccount(value string) *PgBackRestAzureSpecApplyConfiguration {
	b.Account = &value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *PgBackRestAzureSpecApplyConfiguration) WithContainer(value string) *PgBackRestAzureSpecApplyConfiguration {
	b.Container = &value
	return b
}
