// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PgBackRestS3SpecApplyConfiguration represents a declarative configuration of the PgBackRestS3Spec type for use
// with apply.
//
// PgBackRestS3Spec configures an S3-compatible pgbackrest backend. Mirrors the
// cnpg PgBackRestS3 fields maki uses; credentials come from the pod IAM role or,
// when Endpoint is set, the operator-configured credentials Secret.
type PgBackRestS3SpecApplyConfiguration struct {
	// Bucket is the S3 bucket for backups and WAL archives.
	Bucket *string `json:"bucket,omitempty"`
	// Region is the S3 region.
	Region *string `json:"region,omitempty"`
	// Endpoint overrides S3 endpoint discovery. Required for non-AWS
	// S3-compatible storage (e.g. Cloudflare R2, or RustFS for local dev). When
	// set, static credentials from the operator-configured credentials Secret
	// are used instead of an IAM role.
	Endpoint *string `json:"endpoint,omitempty"`
	// CredentialsSecretName is the Secret (in the clusters namespace) holding
	// the static credentials for this backend. When empty, the
	// operator-configured credentials Secret is used. Stamped at branch
	// creation so existing branches keep their store's credentials when the
	// cell-wide default changes.
	CredentialsSecretName *string `json:"credentialsSecretName,omitempty"`
	// KeyType is the cnpg s3.keyType of the repository. The operator ignores
	// it when Endpoint is set. The default is "auto".
	KeyType *string `json:"keyType,omitempty"`
}

// PgBackRestS3SpecApplyConfiguration constructs a declarative configuration of the PgBackRestS3Spec type for use with
// apply.
func PgBackRestS3Spec() *PgBackRestS3SpecApplyConfiguration {
	return &PgBackRestS3SpecApplyConfiguration{}
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *PgBackRestS3SpecApplyConfiguration) WithBucket(value string) *PgBackRestS3SpecApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *PgBackRestS3SpecApplyConfiguration) WithRegion(value string) *PgBackRestS3SpecApplyConfiguration {
	b.Region = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PgBackRestS3SpecApplyConfiguration) WithEndpoint(value string) *PgBackRestS3SpecApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithCredentialsSecretName sets the CredentialsSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecretName field is set to the value of the last call.
func (b *PgBackRestS3SpecApplyConfiguration) WithCredentialsSecretName(value string) *PgBackRestS3SpecApplyConfiguration {
	b.CredentialsSecretName = &value
	return b
}

// WithKeyType sets the KeyType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyType field is set to the value of the last call.
func (b *PgBackRestS3SpecApplyConfiguration) WithKeyType(value string) *PgBackRestS3SpecApplyConfiguration {
	b.KeyType = &value
	return b
}
