// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ScheduledBackupSpecApplyConfiguration represents a declarative configuration of the ScheduledBackupSpec type for use
// with apply.
type ScheduledBackupSpecApplyConfiguration struct {
	Schedule *string `json:"schedule,omitempty"`
}

// ScheduledBackupSpecApplyConfiguration constructs a declarative configuration of the ScheduledBackupSpec type for use with
// apply.
func ScheduledBackupSpec() *ScheduledBackupSpecApplyConfiguration {
	return &ScheduledBackupSpecApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *ScheduledBackupSpecApplyConfiguration) WithSchedule(value string) *ScheduledBackupSpecApplyConfiguration {
	b.Schedule = &value
	return b
}
