// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// StorageSpecApplyConfiguration represents a declarative configuration of the StorageSpec type for use
// with apply.
type StorageSpecApplyConfiguration struct {
	Size                *string `json:"size,omitempty"`
	StorageClass        *string `json:"storageClass,omitempty"`
	VolumeSnapshotClass *string `json:"volumeSnapshotClass,omitempty"`
	MountPropagation    *string `json:"mountPropagation,omitempty"`
}

// StorageSpecApplyConfiguration constructs a declarative configuration of the StorageSpec type for use with
// apply.
func StorageSpec() *StorageSpecApplyConfiguration {
	return &StorageSpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *StorageSpecApplyConfiguration) WithSize(value string) *StorageSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *StorageSpecApplyConfiguration) WithStorageClass(value string) *StorageSpecApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithVolumeSnapshotClass sets the VolumeSnapshotClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSnapshotClass field is set to the value of the last call.
func (b *StorageSpecApplyConfiguration) WithVolumeSnapshotClass(value string) *StorageSpecApplyConfiguration {
	b.VolumeSnapshotClass = &value
	return b
}

// WithMountPropagation sets the MountPropagation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPropagation field is set to the value of the last call.
func (b *StorageSpecApplyConfiguration) WithMountPropagation(value string) *StorageSpecApplyConfiguration {
	b.MountPropagation = &value
	return b
}
