// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

type Connector_Expecter struct {
	mock *mock.Mock
}

func (_m *Connector) EXPECT() *Connector_Expecter {
	return &Connector_Expecter{mock: &_m.Mock}
}

// AvailableSpaceBytes provides a mock function with given fields: ctx
func (_m *Connector) AvailableSpaceBytes(ctx context.Context) (*uint64, error) {
	ret := _m.Called(ctx)

	var r0 *uint64
	if rf, ok := ret.Get(0).(func(context.Context) *uint64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Connector_AvailableSpaceBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableSpaceBytes'
type Connector_AvailableSpaceBytes_Call struct {
	*mock.Call
}

// AvailableSpaceBytes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Connector_Expecter) AvailableSpaceBytes(ctx interface{}) *Connector_AvailableSpaceBytes_Call {
	return &Connector_AvailableSpaceBytes_Call{Call: _e.mock.On("AvailableSpaceBytes", ctx)}
}

func (_c *Connector_AvailableSpaceBytes_Call) Run(run func(ctx context.Context)) *Connector_AvailableSpaceBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Connector_AvailableSpaceBytes_Call) Return(_a0 *uint64, _a1 error) *Connector_AvailableSpaceBytes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewConnector interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnector(t mockConstructorTestingTNewConnector) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
