// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute SQL query
	// (POST /sql)
	Query(ctx echo.Context, params QueryParams) error
	// WebSocket wire protocol proxy
	// (GET /v2)
	Websocket(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Query converts echo context to params.
func (w *ServerInterfaceWrapper) Query(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Connection-String" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Connection-String")]; found {
		var ConnectionString string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Connection-String, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Connection-String", valueList[0], &ConnectionString, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Connection-String: %s", err))
		}

		params.ConnectionString = &ConnectionString
	}
	// ------------- Optional header parameter "Array-Mode" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Array-Mode")]; found {
		var ArrayMode QueryParamsArrayMode
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Array-Mode, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Array-Mode", valueList[0], &ArrayMode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Array-Mode: %s", err))
		}

		params.ArrayMode = &ArrayMode
	}
	// ------------- Optional header parameter "Raw-Text-Output" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Raw-Text-Output")]; found {
		var RawTextOutput QueryParamsRawTextOutput
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Raw-Text-Output, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Raw-Text-Output", valueList[0], &RawTextOutput, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Raw-Text-Output: %s", err))
		}

		params.RawTextOutput = &RawTextOutput
	}
	// ------------- Optional header parameter "Batch-Isolation-Level" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Isolation-Level")]; found {
		var BatchIsolationLevel QueryParamsBatchIsolationLevel
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Isolation-Level, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Isolation-Level", valueList[0], &BatchIsolationLevel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Isolation-Level: %s", err))
		}

		params.BatchIsolationLevel = &BatchIsolationLevel
	}
	// ------------- Optional header parameter "Batch-Read-Only" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Read-Only")]; found {
		var BatchReadOnly QueryParamsBatchReadOnly
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Read-Only, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Read-Only", valueList[0], &BatchReadOnly, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Read-Only: %s", err))
		}

		params.BatchReadOnly = &BatchReadOnly
	}
	// ------------- Optional header parameter "Batch-Deferrable" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Deferrable")]; found {
		var BatchDeferrable QueryParamsBatchDeferrable
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Deferrable, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Deferrable", valueList[0], &BatchDeferrable, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Deferrable: %s", err))
		}

		params.BatchDeferrable = &BatchDeferrable
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Query(ctx, params)
	return err
}

// Websocket converts echo context to params.
func (w *ServerInterfaceWrapper) Websocket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Websocket(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/sql", wrapper.Query)
	router.GET(baseURL+"/v2", wrapper.Websocket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7bOBZ+FULbCzvwT5JOdwFfTZp4OlmkTRq72wUmAUxLxxanEqmSlB23MLAPsU+4",
	"T7I4h5Qs27LjtJ3etDetLJKHH8/vd6h8DkKVZkqCtCbofQ5MGEPK6fElt2F8CyZT0gC+iMCEWmRWKBn0",
	"gmKETZRmnI1xNvuYg14weIAwx2mdoBVkWmWgrQASqsHkidtqSxwOkDTgpSghmY3BSW/hL6Uj0ChXWEhJ",
	"zjMNk6AX/K27OknXH6P7FoU40cGyFdhFBkEv4FrzRbBctgINH3OhIQp6f5TQ7st5avwnhLSwr7XSu3VB",
	"w0wXGpkLG7MbZexUw+DtFQManghIIrOtklBFNSK3luM01hi8vRoMz4b9JkOtZ1kiQo4rKpNwB38AY7WQ",
	"UzxAqJI8ldvbnNN7JnkKTEPCLUTMKtI5SdwhTBqruZC2TmAx9kShEbd8SC83RV5wyxnOf6pEsFwk2/Ku",
	"6YEnzE1gKRjDp/V6m4ikBtFA5ToEhoNsHoOGFRI254ZpyJRGjA0Dega6bUQEzdoN4lotlhBxmGJCg1HJ",
	"TMjpI4cW0oKWPLlRRjhhNZ5FIxhNHP91C5JFewoSNOmWgm+vfIqsbeFDeLBMTQjkEyUnQu5WNQ5+raq9",
	"nbf3+D1PuWxr4BEfJ4XwfV6R7VTuecw1Dy1ollXUjJBdPts8ggrDXGuIarfRKrf7lOLHv1YvLlnW7ELv",
	"nxh0BmaghV0ckNGKqawBnWmHjfq3t9e3oxYb/XY2PLsa1YO1aKIavyPLPQ0qqa02g1n0YiHZPBZhfJi1",
	"NopJ4Wt1xeQ3LAQXMBFyd4QWmnJ5m6VgOSZINtEqJUBazVllVdVdN8sLSri82N7mzFotxrkFJvN0DLqI",
	"W78nVjHvu6R0FD1ROuU26GEaeH660gKG+hR00Aoe2lPV9m9zIe3J36vJvQ7G9eXFxs5RkfC/bMvnp9Ut",
	"X6tITAToGp9ZZNA2GYRiIkKW+nneGzMNoTBCya4JeeJYjsxT0CIkaKZ5CLgKjoH4tLe2GfEJWEPClFsx",
	"c/vNuBao+XYCcmrjJ+y7rpTSDMWyWhRukDVG6P0j5BejsZBcL3ZEIgbbXkKxO34fcQPj0htNZY1jJiZM",
	"Ksu4f+O8pPnlzrERq3SQFbLWKmTWHHfDlDUeVuKpi3oqmJcW0ppAZEbIaVLWCBd4BadGqGDsdmQTjX1d",
	"yx6vZ6C1iIDRHPRt51E2FoYJGYmZiHKebFXjsVIJcEk1jmuemt30gSeMpoAFbbxwWAks6PkW624FH+up",
	"A6Y7pwCrfAsBjydaJ2ynwj3339FuoMPxQvmr/ff0L6FKUy6jR3I2zWGWT4vSNuhf9c+HWNsu3wz6t/T0",
	"7ubibNjHp4v+VX/Y3xFmrm3YGWiryuAt4NoYZsAe3CVtFqQam2k1PzNn9GsLyfsYbAwaS5JhXCMEm2sJ",
	"EePGOaDBrKJzGFHb4kyE7yY8MbB27ooDajU/V3kdO35Tliu35WQCIVb88cJXEdI/SpV5kjjCgNvXpWeU",
	"sNM9cLDD+tiOYr0VBgmzg88aLku0iXN8gIVxLZn0IdeYxyCr4ScMA4lYoua++FjPWFxu96neIVqlL1ZU",
	"5c+zZq+62Bi8vbp1aWVfHBaZh91oNcNsAoIMPaLhke/813KX8qMCzKh6M/Dtspfbp7G2K81QMlk0v3ku",
	"Y43RsxMM0menoxbrdDrNA7KbP+JGlqfDqAnzM2gfl+LLhLPK/f58VnNpeFgko8MvPajSfF3yrVFysz4h",
	"b/jXkvrEiXIJU1oekps5whCYPMPW5NcHbnlHKNepr/GyGNi/MaW94hbmfMEy536GpXliRUYUQEoIrZhh",
	"+6BoodNnJQ1jVhxzA6Z3J+9kmx0d/T4c3mCaPzpijdHN9WDIuuZjMmqy//3nv8y1SQmYwsVARpkq2m+v",
	"CUzrzmTUxhRmc+Lfw3igwg9gSf6r/pB1Z6deegXXXGjAI1kVqgQfHhZMzUCzcr0Xh/Nu/LyjIxIjHTlc",
	"KzZOE6gAJRlqlr345fnpnURLCYu5LygUeXZzGbSCGWjjNH3SOUb1qwwkz0TQC553jjvHGKrcxuRnqCD8",
	"P1N1qaLvHaWmhlYuBSsuz6dcSINUrnKEseYyjDtopaOjQcXlekdHhe3LnNNAE6jiemTkInvUZNy6TkVl",
	"LIEZJF4cXWJuyaHsxM0qW3uIi6I2tRj1p1jEqaRSHmRjFS3uJK5j/xxcv3FrO+xlefWJRyyCZ18kk3Ew",
	"GdLd3WUU9BxbCXyqojwU9P7YSzIKuzMXiKwxytyw6XW7uQHdy7gxv8bK2G40HjU7DAMLf1LJAhkqjCnX",
	"3+kpWG8IcvLS+Ys2TOD+MfCIeK4P5fMSRHvgskH1NqEk57kWdWmjhkdI5nhCy3MIX+BLGoHOAzxCe3lL",
	"7cRG6bZNBaYKCmSeYhXFbZCwIwOplMinoeNJwmY8yYEwurWGLK9ypzq0k4+3nUhv+bw9hAfbvs5tlttv",
	"A3e4cjcmjErcLTGFRqXweKfdCY1cu31ZrG9f4fpagLfAo3OVpsJaQEqCv9/JcO1NBpyaLBwLWsEAtOCJ",
	"+EQE7ckmKOKs/DxQjTAmJNPAozaSAqpcjxwRIbWvZbL4C5zlUaQRTEBr6m0PgHpRzv4irPeOTYKxL1W0",
	"KEo0OJ5d+aLQ/dO4u6nVFvtIR4VRLtcZKwKiF+7rCJWV0+PjJ+2sJFxPKCEe/rVn/9z1r1vLewK9bsS3",
	"lWYQImbyMARjJnmSEJP65Yln2Idm/ftSDZZLOeOJiMpSpDQrL1IdmJPvB+a1MFjUEITwuLbKEYJ68X01",
	"5L42eCK3Us2L4398PxTlV1GrFEuwrBJBdpjqSjqyYHZze30RtIJcJxj11mZYwj+7crzsfNYwFUouO8SY",
	"LYQxkjh/N0jh5GY6fjbhdOERpIu2f03BNy1vmosJuWkDN7Z9QueoxTUYnr26fPPqAGjG8qmQ007KP4hO",
	"qNQHRwa+C8qL/r8OQBjB7C9Gd98KTJ6mHPurkhqXjJhuGKfoAgUdD+5/esYP4hnLVtCdneKMKdT0Ue+y",
	"qeYRJg3GV21gNanamFvqFYWn7Lsays6dRJofJgKkpRbGEKHXEIKYgakuLJtQ//HIuD7U3fpXcEywJTHU",
	"UZ3lNgZpi786EIbFXEYJRGwm+CYwY7m2eVaIr35RWsPcupO5KT5tG2xOVidv++6m7FuIUEvX8HKni6Kv",
	"L7uWugbrPYwNHSfY4CInrnRu3IfMhQ1j3LjowA014LXGAYO0VpgYogoxWBf4kq+KNwrK6S4QLZ57468E",
	"/iwZP2TJWPlWzRXRz/LxI5ePZWn9A66E6FIU03GRF1tsr2u1qED4q8X1YrLqPQunW94v/x8AAP//rkBE",
	"ljQoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
