// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute SQL query
	// (POST /sql)
	Query(ctx echo.Context, params QueryParams) error
	// WebSocket wire protocol proxy
	// (GET /v2)
	Websocket(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Query converts echo context to params.
func (w *ServerInterfaceWrapper) Query(ctx echo.Context) error {
	var err error

	ctx.Set(string(BranchConnectionStringScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Array-Mode" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Array-Mode")]; found {
		var ArrayMode QueryParamsArrayMode
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Array-Mode, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Array-Mode", valueList[0], &ArrayMode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Array-Mode: %s", err))
		}

		params.ArrayMode = &ArrayMode
	}
	// ------------- Optional header parameter "Raw-Text-Output" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Raw-Text-Output")]; found {
		var RawTextOutput QueryParamsRawTextOutput
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Raw-Text-Output, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Raw-Text-Output", valueList[0], &RawTextOutput, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Raw-Text-Output: %s", err))
		}

		params.RawTextOutput = &RawTextOutput
	}
	// ------------- Optional header parameter "Batch-Isolation-Level" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Isolation-Level")]; found {
		var BatchIsolationLevel QueryParamsBatchIsolationLevel
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Isolation-Level, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Isolation-Level", valueList[0], &BatchIsolationLevel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Isolation-Level: %s", err))
		}

		params.BatchIsolationLevel = &BatchIsolationLevel
	}
	// ------------- Optional header parameter "Batch-Read-Only" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Read-Only")]; found {
		var BatchReadOnly QueryParamsBatchReadOnly
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Read-Only, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Read-Only", valueList[0], &BatchReadOnly, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Read-Only: %s", err))
		}

		params.BatchReadOnly = &BatchReadOnly
	}
	// ------------- Optional header parameter "Batch-Deferrable" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Deferrable")]; found {
		var BatchDeferrable QueryParamsBatchDeferrable
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Deferrable, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Deferrable", valueList[0], &BatchDeferrable, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Deferrable: %s", err))
		}

		params.BatchDeferrable = &BatchDeferrable
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Query(ctx, params)
	return err
}

// Websocket converts echo context to params.
func (w *ServerInterfaceWrapper) Websocket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Websocket(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/sql", wrapper.Query, options.OperationMiddlewares["query"]...)
	router.GET(options.BaseURL+"/v2", wrapper.Websocket, options.OperationMiddlewares["websocket"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp9b9s40v8qAz0FHjuQnZdmF8/jwwGbNu5u7tImjd3rAUkA0dLY5lYiVZJy4hYB7kPcJ7xPchiSenEs",
	"u067V+wB+1cciZwZzvv8qM9BLLNcChRGB4PPgY7nmDH78wUz8fwKdS6FRnqQoI4Vzw2XIhgE5RuYSgUM",
	"JrQaPhaoloD3GBe0rB+EQa5kjspwtEQV6iI1upUcvbDUkFWkuAAzR0c9pP+kSlARXW4ws3SeKZwGg+B/",
	"9uuT7Ptj7L8lIo508BAGZpljMAiYUmwZPDyEgcKPBVeYBIPrSrTbap2c/Iqx3ThUSqrNurCvQZUaueNm",
	"DpdSm5nC0dtzQPt6yjFN9LpKYpm0kFzbTsugM3p7PhqfjIddIK3necpjRjsai/pBdQBtFBczOkAs0yIT",
	"62xe2ucgWIagMGUGEzDS6txS3EBMaKMYF6aNYPnuiUQTZtjYPnxM8pQZBrT+qRTRMJ6u07uwP1gKbgFk",
	"qDWbtettytMWiUayUDECvYS7OSqsJYE7pkFhLhXJ2NGoFqh6mifYbWUwb9ViJSK9tjGhUMt0wcXsC4fm",
	"wqASLL2UmjtiLZ5l31A0MQHlhnTZm6FAZXVrg28rfRtZ68THeG9ATq2QT6SccrFZ1fTyW1Xt7bzO45ci",
	"Y6KnkCVskpbEt3lFvlG5L+dMsdiggryhZhLZ5bPHR5BxXCiFSSsbJQuzTSn+/bfqxSXLFi72+RODTuMC",
	"FTfLHTJauRQ62J/1IRpeXV1cRSFEr07GJ+dRu7CGTNTid/T4iaJatbVmMENezAXczXk8381aj4pJ6Wtt",
	"xeQVFYJTnHKxOUJLTbm8DRkaRgkSpkpmViAl76Cxq+muj8sLUTg7XWdzYozik8IgiCKboCrj1vOkKuZ9",
	"1yqdSE+lypgJBgEX5vlRrQUK9RmqIAzuezPZ808LLszhj83k3ibGxdnpI85JmfC/juXzoybL1zLhU46q",
	"xWeWOfZ0jjGf8hgyv857Y64w5ppLsa9jlrouRxQZKh5b0XR3F+Eacoz4p621TfNPCB2BM2b4wvFbMMVJ",
	"870UxczMn8B3VSmVGcptrVK4l9CJyPsjkAqiCRdMLTdEIgXb1oZic/x+wQ20S292KXQOgE9BSAPMP3Fe",
	"0v1653gUq/YgtWRhHTIrjvvIlC0eVsnTFvW2YJ4ZzFoCETQXs7SqES7wyp6aREVt1iPbtrGvW7vHiwUq",
	"xRMEu4Z823mUmXMNXCR8wZOCpWvVeCJlikzYGscUy/Tm9oGlYJegQaU9cawJlu35WtcdBh/bWwdKd/YV",
	"GOlHCPxyonXENirc9/4bxg1yOFYqv+a/ZX6JZZYxkXwhZ9s1YNisLG2j4fnw5Zhq29mb0fDK/np3eXoy",
	"HtKv0+H5cDzcEGZubNgYaHVl8BZwYwxoNDtPSY8LUovNlLw70Sf2vzVJ3s/RzFFRSdLAFIlgCiUwAaad",
	"A2rKKqrAyI4tzkT0bMpSjVG33QGVvHspi7bu+E1VrhzL6RRjqviTpa8iVv9EVRRp6hoGYt+WnonCRveg",
	"l30Y0jhK9ZZrYMKLDx2XJXq25/iAS23PxoQPuc7dHEUz/LgGFCRL0t0WH6sZi4n1OdU7RFj5YkNV/jwr",
	"9mqLjdHb8yuXVrbFYZl54FLJBWUT5NbQkX0d+cl/JXdJ/5ajjprIwG+XvRyfzgpXu0KKdNn9zXMZdKJn",
	"hxSkz46iEPr9fneH7MaxhZm1BjmtX2H5uBRfJZw69/vzGcWEZnGZjHYHPWyl+bbk26LkbntCfuRfdgyI",
	"C+rt7QzhtDFRTMTzl1IItOcZuf1roryw62AloZZ7wDGFTpS713qwv19oVIOcaf3TZ8fjof9Z4YxL8dC/",
	"Z4b1Dcbz/WQSdQlBitMiqcbobIJJggnQ7jupkj6M5whzqY0Na42pzVSuB1YzNOA4hOAYhECJHkWSSy6M",
	"a+Q6tDrqqbtoP+opGYEuplN+H4JGhGjo11LjEHXd/qzQBjLrCS6D27CzYvThYmIYF8BN3fv/nRkGCdPz",
	"iWQqAe+usRRGybSXp0wgnFye0WGo3Dv5KTwgVpigMJyl9tmMGbxjS2BxjLnRf2qnQ9kNOi+QKVRg5AcU",
	"XSKq8FeXdmmM6sMrL8Z7nIxk/AFNrZZO9PNwDPuLo6hrl2jS7bpRuaaHC1xiAgvO7NKGF2jDlCnyctIB",
	"LrRBlrimkWuYIyuhQREMAvdvUPapQe14Pe95dXDk/K9IidbiG1PpCr0wLLbp0RPQRZ5LZX6yLsWlQ5hW",
	"5onSND97teYubWrIitTwPK0PvaCxV9qNLg80zknVfMI06sGNuBE92Nv7ZTy+pPZkbw860eXFaAz7+mMa",
	"deFf//gnuPE+RV2mxkrtRNdHMHmZSzXEoUo3jnxlsb29FVMR9YZcd1whHcnIWKb0434JcoGqtrgnR+su",
	"/bq9PUtGuKGmNaY1SAGkWfjh+PnRjSC7cEM1OygVeXJ5FoTBApV2mj7sH5D6ZY6C5TwYBM/7B/0DKjHM",
	"zG2yIQXRX0oTLXitT3AtvV8DzG6kajZj5G7AmkdwqaBPVtrbOynMnCLLwbGDvT3QKBIHXtt1/6u3pzQ3",
	"at+IaM1Ro9K1bXLaMTxJJiHJpC64MSE1N4Pephcn/JUFkmYk9ZNSHVO0+AOKKjfdiCp5VsnVnWz9yKHH",
	"V7alvxsxQgdttemlrDJgSx9WlZu2+nnWn3DUqGR0TB+aVSvTocPJEnWNXMMQdYEZpxGZQ4oLTD05ezey",
	"Rsc2PUzXTaD3oGXZ8oYgVe0X5UEnMlneCNoHfxldvHF7+/CiulEhDyxr8rYGwcaOzFFZHzxLgoEbgoIw",
	"qNubYHDd0sALcA166Jt331lX/Xsj2fqzbEy0ts/p2c6uiS2iKDJqX4kNTcrU+jd607qb2EU6lqawYGmB",
	"Vka3V1vdyML7pi0lNmFslPSK3fUIsO5dFCYvzG8j7rg2CHAtU2sL5zyNjs+bdaNo1vi9s3J/75z2twp4",
	"hSx5KbOMG4M0C9D/70S88iRHZtENeheEwQgVZyn/RI+eboLSE6t7uaYPUrArZEnPthuZv47ackQSqXch",
	"0uV/wFm+KGmCU1SK1LCLqKfV6q+S9daNcajNC5ksyx4D3YDbuMrb/1U7UBjvWZanvnkmCeiHLrKMqWUp",
	"VLNIcQFSrGQEKpoUJbSxmkuuP1fz0HUwxzSVJK2fCwKHT8DZm/EFpHKmoeP7rS787eT83XAEnWeH3YA0",
	"X25x4AbENIF29rrw6uritd0bPNzaWcBmqlXhfT6u0hL/VN4NNWWu5Dw+ug0f8+NJ6AB/y4+GAA3vfxle",
	"DYEn8Gd4dugautpQ22amxkD8sDpwk1ntA3e5a61xdHDw7farIajaP9lELjC0ZkRh1BJyVOtqqS7RrxuA",
	"lLdcUCNG17eruI31zCaucljCH9e3D2GTlNNwk1TzHuFgFc8/OmgD23uHj6Hv/2vAtQQx1+EVe+yiwoYP",
	"HnYX/bPfPggOyd82etyqulcmW6v1poK/VhPPd9PE8UZN8GRVDeE2bj/sxq13uJHdI+T7iXrnSTA4Pqrr",
	"fsJswK/EnBR4MbWrd/9MY/va1c9SPMPVIvC2geJiArqIY9R6WqSphUCOd4re3fLG6ochLbKciQVLeVI2",
	"eyFU95/hY7QZDM9QFiZ0Q4gHclNqxqmtZa6NPjx4/aL+1CTlGTfuUIff71CvuaYAIjm5P99ad++Eev79",
	"hHqZchQGzi6Ba3dflKbyroaF3ThD76c8NQ79PT44/n4CemCLRJvKQiQhcJp7ljBnC4QJIjUkKRpMnGj/",
	"/91FIxSFT1AJZjChZpvaiAUzSJJOcCoVgiqEINuX/QSJevgdzXzVmJpI4GZ8/Hj8+gUJ9MP3jXD3mYtH",
	"YlxwOym+o3ONeUYjfmGqSBSz8hOIElFaQWZtUt6EyV7fUiVwB2qbGJsw1yPMFEUsCfNaAxIsfuCwBGq0",
	"C5UGg2BuTE4Y7hbk1hZmdxHewJEdqDNl9nYvyJY9/3iDZ5+d9uGdxmYiiHgShfDmYgzcaJivfgNERwls",
	"2zerPtEomRW6h0yb3uEmZv6QVi9RtToCT8LeI0GeshjnMk1QORCYLW1qmKAHB4gGtStLWajKhH2y/W3Y",
	"6GtKLKuCsGxBn5HVSvyM+vv7XgUM9D5w29skqI0qKMIxePjD2r9baz+Ewf7iiKSaYQuY+S6fKZYgBTtr",
	"oO+NgmzmzFjAlntLbUJ1+zeCThG7SkpAlfZ2jJEvcAXBLPeUeLx2YLD7ZKQhx5QmPL0RJa3uA7yd1oHR",
	"xp0F0w5jLAHxGo7kmibAJIRJYahYcQ2E16d8613CjWhcJhCMR8tWNAKKmXlZXpgAy7kBx96IXa9LbEfi",
	"odg2pO49TrTVWPBo2Dw8OFw3+uiOm3hO6imRdm2B9lb7o6YOn+t52VkctNy6sapHtYQKe1dNTlV4/6oJ",
	"Bg9/pIv/juJQu0PL7c3OhYIO/keF+D1XiIfKlFu/S2pcPlJSLNNoCFv9xN38+Cu81XpRQwmlBz3cPvx7",
	"AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
