// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute SQL query
	// (POST /sql)
	Query(ctx echo.Context, params QueryParams) error
	// WebSocket wire protocol proxy
	// (GET /v2)
	Websocket(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Query converts echo context to params.
func (w *ServerInterfaceWrapper) Query(ctx echo.Context) error {
	var err error

	ctx.Set(string(BranchConnectionStringScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Array-Mode" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Array-Mode")]; found {
		var ArrayMode QueryParamsArrayMode
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Array-Mode, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Array-Mode", valueList[0], &ArrayMode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Array-Mode: %s", err))
		}

		params.ArrayMode = &ArrayMode
	}
	// ------------- Optional header parameter "Raw-Text-Output" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Raw-Text-Output")]; found {
		var RawTextOutput QueryParamsRawTextOutput
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Raw-Text-Output, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Raw-Text-Output", valueList[0], &RawTextOutput, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Raw-Text-Output: %s", err))
		}

		params.RawTextOutput = &RawTextOutput
	}
	// ------------- Optional header parameter "Batch-Isolation-Level" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Isolation-Level")]; found {
		var BatchIsolationLevel QueryParamsBatchIsolationLevel
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Isolation-Level, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Isolation-Level", valueList[0], &BatchIsolationLevel, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Isolation-Level: %s", err))
		}

		params.BatchIsolationLevel = &BatchIsolationLevel
	}
	// ------------- Optional header parameter "Batch-Read-Only" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Read-Only")]; found {
		var BatchReadOnly QueryParamsBatchReadOnly
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Read-Only, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Read-Only", valueList[0], &BatchReadOnly, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Read-Only: %s", err))
		}

		params.BatchReadOnly = &BatchReadOnly
	}
	// ------------- Optional header parameter "Batch-Deferrable" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Batch-Deferrable")]; found {
		var BatchDeferrable QueryParamsBatchDeferrable
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Batch-Deferrable, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Batch-Deferrable", valueList[0], &BatchDeferrable, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Batch-Deferrable: %s", err))
		}

		params.BatchDeferrable = &BatchDeferrable
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Query(ctx, params)
	return err
}

// Websocket converts echo context to params.
func (w *ServerInterfaceWrapper) Websocket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Websocket(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/sql", wrapper.Query, options.OperationMiddlewares["query"]...)
	router.GET(options.BaseURL+"/v2", wrapper.Websocket, options.OperationMiddlewares["websocket"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr9btu4ln+VA22BtQPZ+Wimc8eLBW7aeO5kN23S2N1ZIAkgWjq2OZVIDUk5cYsA+xD7hPski0NSH7Zl",
	"17ntLeYC81cciTw83x8/6nMQyyyXAoXRweBzoOM5Zsz+fM1MPL9BnUuhkR4kqGPFc8OlCAZB+QamUgGD",
	"Ca2G3wtUS8BHjAta1g/CIFcyR2U4WqIKdZEa3UqOXlhqyCpSXICZo6Me0n9SJaiILjeYWTovFE6DQfAv",
	"h7Ukh16Mw/dExJEOnsLALHMMBgFTii2Dp6cwUPh7wRUmweC2Yu2+Wicnv2FsNw6Vkmq7LuxrUKVGHriZ",
	"w7XUZqZw9P4S0L6eckwTvamSWCYtJDe20zLojN5fjsZn42EXSOt5nvKY0Y7Gon5QCaCN4mJGAsQyLTKx",
	"ecwb+xwEyxAUpsxgAkZanVuKW4gJbRTjwrQRLN89k2jCDBvbh+skz5lhQOufSxEN4+kmvSv7g6XgFkCG",
	"WrNZu96mPG3haCQLFSPQS3iYo8KaE3hgGhTmUhGPHY1qgaqneYLd1gPmrVqsWKTXNiYUapkuuJh9QWgu",
	"DCrB0mupuSPW4ln2DUUTE1BuSJe9GQpUVrc2+HbSt5G1SXyMjwbk1DL5TMopF9tVTS+/VtXezptn/FJk",
	"TPQUsoRN0pL4Lq/Ityr3zZwpFhtUkDfUTCy7fLYugozjQilMWo9RsjC7lOLff61eXLJsOcU+f2bQaVyg",
	"4ma5R0Yrl0IH+7M+RMObm6ubKITo57Px2WXUzqwhE7X4HT1+JqtWba0ZzJAXcwEPcx7P97PWWjEpfa2t",
	"mPxMheAcp1xsj9BSUy5vQ4aGUYKEqZKZZUjJB2jsarrrenkhChfnm8ecGaP4pDAIosgmqMq49WdSFfO+",
	"a5UOnSPgUxDSAPNP3MoQBM6Y4QvXC+ilNpj5d9pacSpVxkwwCLgwL0+CMMjYI8+KLBi8PPnx1Y9hkHHh",
	"/u/Rg79USqMUMkMVhMFjbyZ79dPjV82a0Sbd1cX5mkBJWUfWWXp12mTp9OSn059e/Xjy0w8Nvo6+wFLh",
	"JGvw9FYmfMpRtfjqMseezjHmUx5D5tf5KMgVxlxzKQ51zFKnUVFkqHhsed+i0DXmGnyM+KedNVXzTwid",
	"FQsumOJk316KYmbmu879RoYs6bay6V5CJ6KwjEAqiCZcMLXckiIoC+zsdLYnli84knZ5d3c4dP+B7rWW",
	"ZaykNethHewrsbHmDC0+WjHclq9sqb8wmLWkENBczNKqurmUUU4DxCpqs5mTbAP+trXvvVqgUjxBsGso",
	"OpxPmjnXwEXCFzwpWLrRR0ykTJEJW52ZYpne3viwFOwSNKi0J441wXKw2JgXwuD39qaHErV9BUb64Qe/",
	"XCIcsa0K91PLlkGJPJKVyq/P3zF5xTLLmEi+UG3sGjBsVhbl0fBy+GZMVfni3Wh4Y399uD4/Gw/p1/nw",
	"cjgebolDN/BsjcS6pnkLuAEMNJq957v1UtpiMyUfzvSZ/W+Dk1/naOaoqJhqYIpYMIUSmADTzgE1pR1V",
	"YGQHLmciejZlqcao2+6ASj68kUVbX/+uKrTuyOkUY+pVJktfqKz+iaoo0tS1OnR8W4InClvdg172YUiD",
	"NHUKXAMTnn3ouCzRs93SR1xqKxsTPuQ6D3MUzfDjGlAQL0l3V3ysZiwmNids7xBh5YsNVXl5VuzVFhuj",
	"95c3Lq3sisMy88C1kgvKJsitoSP7OvKYxUrukv4tRx01MY1vl73cOZ2VU+0KKdJl95vnMuhEL44pSF+c",
	"RCH0+/3uHtmNY8th1hrktH6FPcel+Crh1Lnfy2cUE5rFZTLaH66xlebrkm+LkrvtCXnNv+wAExc0ldjp",
	"x2ljopiI52+kEGjlGbn9G6y8tutgJaGWe8AdCp0od6/14PCw0KgGOdP6r5/dGU/9zwpnXIqn/iMzrG8w",
	"nh8mk6hL2FecFkkFAGQTTBJMgHY/SJX0YTxHmEttbFhrTG2mct27mqEBd0II7oAQKNGjSHLJhXGtYIdW",
	"Rz31EB1GPSUj0MV0yh9D0IgQDf1aahyirtufFdpAZj3BZXAbdpaNPlxNDOMCuKmnlv9mhkHC9HwimUrA",
	"u2sshVEy7eUpEwhn1xckDJV7xz+FB8QKExSGs9Q+mzGDD2wJLI4xN/rf2ulQdoPOa2QKFRj5EUWXiCr8",
	"zaVdGgD78LNn41ecjGT8EU2tlk70t+EYDhcnUdcu0aTbTaNyTQ8XuMQEFpzZpQ0v0IYpU+TljAZcaIMs",
	"cV0l1zBHVoKaIhgE7t+gbGSD2vF63vPq4Mj5fyIlWovMTKUr9MKw2KZHT0AXeS6V+at1KS4dNrYykZSm",
	"+ZtXa+7SpoasSA3P01roBQ3s0m50eaAhJ1XzCdOoB3fiTvTg4OCX8fia2pODA+hE11ejMRzq39OoC//3",
	"P/8LDphIUZepsVI70fURTF7mUg2dUKUbR76y2MHBiqmIeoOvB66QRDIylin9eFyCXKCqLe7J0bprv+7g",
	"wJIRbixqjWkNUgBpFn44fXlyJ8gu3FDNDkpFnl1fBGGwQKWdpo/7R6R+maNgOQ8Gwcv+Uf+ISgwzc5ts",
	"SEH0l9JEC9LsE1xL79eA4Rupms0YuRuwpgguFfTJSgcHZ4WZU2Q5IHlwcAAaReJgd7vuX/XulOZAgjsR",
	"bThqVLq2TU57hifxJCSZ1AU3JqTmZtDb9OKYv7EQ2Iy4flaqY4oWf0RR5aY7USXPKrk6yTZFDj0ytCv9",
	"3YkROlCuTS9llQFb+rCq3LTVD7xewlGjkpGYPjSrVqZDwskSL45cwxB1gRmnEZlDigtMPTl7q7NBxzY9",
	"TNdNoPegZdnyhiBV7ReloBOZLO8E7YP/GF29c3v78Lq6CyIPLGvyrgbBxo7MUVkfvEiCgRuCgjCo25tg",
	"cNvSwAtwDXrom3ffWVf9eyPZelm2Jlrb5/RsZ9dERVHQiH4b0DE0KVPr3+hN625iH+5YmsKCpQVaHt1e",
	"bXUjC++btpTYhLGV0xv20COovXdVmLww34bdcW0Q4Fqm1hbOeRodnzfrVtas8XsX5f7eJe1vZfAGWfJG",
	"Zhk3BmkWoP8/iHjlSY7Mohv0LgiDESrOUv6JHj3fBKUnVjeKTR+kYFfIkp5tNzJ/kbZDRGKpdyXS5T/A",
	"Wb7IaYJTVIrUsA+r59Xqv4vXezfGoTavZbIsewx0A27jEvLwN+3gbHxkWZ765pk4oB+6yDKmliVTzSLF",
	"BUixkhGoaFKU0MZqLrn9XM1Dt8Ec01QSt34uCBw+ARfvxleQypmGju+3uvBfZ5cfhiPovDjuBqT5cosD",
	"NyCmCbRz0IWfb67e2r3B072dBWymWmXe5+MqLfFP5a1Wk+eKz9OT+3D9PJ6E7qrCnkdDgIZffxneDIEn",
	"8O/w4tg1dLWhds1MjYH4aXXgJrPaB+5a2lrj5Ojo6+1XQ1C1f7KJXGBozYjCqCXkqDbVUl3/3zYAKW+5",
	"oEaMbu9XcRvrmU1c5biEP27vn8ImKafhJqnmDcjR6pXByVEbXN87XgfP/9LAcwmDrsMr9thFBR4fPe3P",
	"+me/fRAck79t9bhVda9MtlbrTQX/vZp4uZ8mTrdqgieragh3nfbDfqf1jrcet4Z8P1PvPCEcvq77CbMB",
	"vxJzUuDV1K7e/wOT3WtXP6jxB64WgfcNFBcT0EUco9bTIk0tBHK6V/TulzdWP2lp4eVCLFjKk7LZC6G6",
	"uQ3X0WYwPENZmNANIR7ITakZp7aWuTb6+Ojt6/ojmZRn3Dihjr+fUG+5pgAiPrmXb6O7d0y9/H5MvUk5",
	"CgMX18C1u1BKU/lQw8JunKH3U54ah/6eHp1+PwY9sEWsTWUhkhA4zT1LmLMFwgSRGpIUDSaOtZ++O2uE",
	"ovAJKsEMJtRsUxuxYAaJ0wlOpUJQhRBk+7KfIFaPv6OZbxpTEzHcjI9Xp29fE0M/fN8Idx/oeCTGBbfj",
	"4js615hnNOIXpopEMSs/3igRpRVk1iblbZjs7T1VAidQ28TYhLnWMFMUsSTMawNIsPiBwxKo0S5UGgyC",
	"uTE5Ybg7kFtbmN1VegNHdqDOlNnbvSBb9vzjLZ59cd6HDxqbiSDiSRTCu6sxcKNhvvr1EokS2LZvVn1c",
	"Uh5W6B4ybXrH2w7zQlq9RNXqCDwJe48EecpinMs0QeVAYLa0qWGCHhwgGtSuLGWhKhP2yfb3YaOvKbGs",
	"CsKyBX1GVivxM+rvH3sVMND7yG1vk6A2qqAIx+DpT2v/Ya39FAaHixPiaoYtYOaHfKZYghTsrIG+Nwqy",
	"mTNjAVvuLbUN1e3fCZIidpWUgCrt7RgjX+AKglnuKfF47cBg901Jg48pTXh6K0pa3Qd4O20Co407C6Yd",
	"xlgC4jUcyTVNgEkIk8JQseIaCK9P+c67hDvRuEwgGI+WrWgEFDPzsrwwAfbkBhx7J/a9LrEdiYdi25C6",
	"X3GircaCtWHz+Oh40+ijB27iOamnRNq1Bdpb7Y+aOnyu52VncdRy68aqHtUSKuxdNTlV4f2rJhg8/Zku",
	"/jmKQ+0OLbc3excKEvzPCvFHrhBPlSl3fpfUuHykpFim0RB2+om7+fFXeKv1ooYSSg96un/6/wEA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
