// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package spec

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	BranchConnectionStringScopes branchConnectionStringContextKey = "branchConnectionString.Scopes"
)

// Defines values for QueryParamsArrayMode.
const (
	QueryParamsArrayModeFalse QueryParamsArrayMode = "false"
	QueryParamsArrayModeTrue  QueryParamsArrayMode = "true"
)

// Valid indicates whether the value is a known member of the QueryParamsArrayMode enum.
func (e QueryParamsArrayMode) Valid() bool {
	switch e {
	case QueryParamsArrayModeFalse:
		return true
	case QueryParamsArrayModeTrue:
		return true
	default:
		return false
	}
}

// Defines values for QueryParamsRawTextOutput.
const (
	QueryParamsRawTextOutputFalse QueryParamsRawTextOutput = "false"
	QueryParamsRawTextOutputTrue  QueryParamsRawTextOutput = "true"
)

// Valid indicates whether the value is a known member of the QueryParamsRawTextOutput enum.
func (e QueryParamsRawTextOutput) Valid() bool {
	switch e {
	case QueryParamsRawTextOutputFalse:
		return true
	case QueryParamsRawTextOutputTrue:
		return true
	default:
		return false
	}
}

// Defines values for QueryParamsBatchIsolationLevel.
const (
	ReadCommitted   QueryParamsBatchIsolationLevel = "ReadCommitted"
	ReadUncommitted QueryParamsBatchIsolationLevel = "ReadUncommitted"
	RepeatableRead  QueryParamsBatchIsolationLevel = "RepeatableRead"
	Serializable    QueryParamsBatchIsolationLevel = "Serializable"
)

// Valid indicates whether the value is a known member of the QueryParamsBatchIsolationLevel enum.
func (e QueryParamsBatchIsolationLevel) Valid() bool {
	switch e {
	case ReadCommitted:
		return true
	case ReadUncommitted:
		return true
	case RepeatableRead:
		return true
	case Serializable:
		return true
	default:
		return false
	}
}

// Defines values for QueryParamsBatchReadOnly.
const (
	QueryParamsBatchReadOnlyFalse QueryParamsBatchReadOnly = "false"
	QueryParamsBatchReadOnlyTrue  QueryParamsBatchReadOnly = "true"
)

// Valid indicates whether the value is a known member of the QueryParamsBatchReadOnly enum.
func (e QueryParamsBatchReadOnly) Valid() bool {
	switch e {
	case QueryParamsBatchReadOnlyFalse:
		return true
	case QueryParamsBatchReadOnlyTrue:
		return true
	default:
		return false
	}
}

// Defines values for QueryParamsBatchDeferrable.
const (
	QueryParamsBatchDeferrableFalse QueryParamsBatchDeferrable = "false"
	QueryParamsBatchDeferrableTrue  QueryParamsBatchDeferrable = "true"
)

// Valid indicates whether the value is a known member of the QueryParamsBatchDeferrable enum.
func (e QueryParamsBatchDeferrable) Valid() bool {
	switch e {
	case QueryParamsBatchDeferrableFalse:
		return true
	case QueryParamsBatchDeferrableTrue:
		return true
	default:
		return false
	}
}

// BatchResponse Response for a batch query execution.
type BatchResponse struct {
	// Results Results for each query in the batch, in order.
	Results []QueryResult `json:"results"`
}

// ErrorResponse Error response with PostgreSQL error fields.
type ErrorResponse struct {
	// Code PostgreSQL error code (SQLSTATE) or application error code.
	Code *string `json:"code,omitempty"`

	// Column Column name related to the error.
	Column *string `json:"column,omitempty"`

	// Constraint Constraint name related to the error.
	Constraint *string `json:"constraint,omitempty"`

	// DataType Data type name related to the error.
	DataType *string `json:"dataType,omitempty"`

	// Detail Optional detail message.
	Detail *string `json:"detail,omitempty"`

	// File Source file where the error was reported (server-side).
	File *string `json:"file,omitempty"`

	// Hint Optional hint for resolving the error.
	Hint *string `json:"hint,omitempty"`

	// InternalPosition Position in an internally-generated query.
	InternalPosition *string `json:"internalPosition,omitempty"`

	// InternalQuery Text of the internally-generated query.
	InternalQuery *string `json:"internalQuery,omitempty"`

	// Line Source line where the error was reported (server-side).
	Line *string `json:"line,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// Position Character position in the query where the error occurred.
	Position *string `json:"position,omitempty"`

	// Routine Source routine where the error was reported (server-side).
	Routine *string `json:"routine,omitempty"`

	// Schema Schema name related to the error.
	Schema *string `json:"schema,omitempty"`

	// Severity PostgreSQL error severity (e.g. `ERROR`, `FATAL`).
	Severity *string `json:"severity,omitempty"`

	// Table Table name related to the error.
	Table *string `json:"table,omitempty"`

	// Where Context in which the error occurred.
	Where *string `json:"where,omitempty"`
}

// FieldDefinition PostgreSQL column metadata from the row description message.
type FieldDefinition struct {
	// ColumnID Attribute number of the column within the table.
	ColumnID uint16 `json:"columnID"`

	// DataTypeID OID of the column data type.
	DataTypeID uint32 `json:"dataTypeID"`

	// DataTypeModifier Type-specific modifier (e.g. precision/scale for numeric types).
	DataTypeModifier int32 `json:"dataTypeModifier"`

	// DataTypeSize Data type size (negative for variable-length types).
	DataTypeSize int16 `json:"dataTypeSize"`

	// Format Data format (`text` or `binary`).
	Format string `json:"format"`

	// Name Column name.
	Name string `json:"name"`

	// TableID OID of the source table (0 if not a table column).
	TableID uint32 `json:"tableID"`
}

// QueryItem A single query within a batch request.
type QueryItem struct {
	// ArrayMode Override array mode for this individual query.
	ArrayMode *bool `json:"arrayMode,omitempty"`

	// Params Positional parameters for the query.
	Params *[]interface{} `json:"params,omitempty"`

	// Query SQL query to execute.
	Query string `json:"query"`
}

// QueryResult Result of a single SQL query execution.
type QueryResult struct {
	// Command PostgreSQL command tag (e.g. `SELECT`, `INSERT`, `UPDATE`, `DELETE`).
	Command string `json:"command"`

	// Fields Column metadata for the result set.
	Fields []FieldDefinition `json:"fields"`

	// RowAsArray Whether rows are returned as arrays (`true`) or objects (`false`).
	RowAsArray bool `json:"rowAsArray"`

	// RowCount Number of rows affected by the command.
	RowCount *int `json:"rowCount"`

	// Rows Result rows. Each row is an object (column-name keys) or an array (when array mode is enabled).
	Rows any `json:"rows"`
}

// SQLRequest SQL query request. Provide either `query` for a single query or `queries` for a batch.
type SQLRequest struct {
	// ArrayMode Override array mode for this query (single query mode only).
	ArrayMode *bool `json:"arrayMode,omitempty"`

	// Params Positional parameters for the query (`$1`, `$2`, ...).
	Params *[]interface{} `json:"params,omitempty"`

	// Queries Array of queries for batch execution within a single transaction.
	Queries *[]QueryItem `json:"queries,omitempty"`

	// Query SQL query to execute (single query mode).
	Query *string `json:"query,omitempty"`
}

// branchConnectionStringContextKey is the context key for branchConnectionString security scheme
type branchConnectionStringContextKey string

// QueryParams defines parameters for Query.
type QueryParams struct {
	// ArrayMode When `true`, return rows as arrays instead of objects.
	ArrayMode *QueryParamsArrayMode `json:"Array-Mode,omitempty"`

	// RawTextOutput When `true`, return all values as strings without type conversion.
	RawTextOutput *QueryParamsRawTextOutput `json:"Raw-Text-Output,omitempty"`

	// BatchIsolationLevel Transaction isolation level for batch queries.
	BatchIsolationLevel *QueryParamsBatchIsolationLevel `json:"Batch-Isolation-Level,omitempty"`

	// BatchReadOnly When `true`, execute the batch transaction in read-only mode.
	BatchReadOnly *QueryParamsBatchReadOnly `json:"Batch-Read-Only,omitempty"`

	// BatchDeferrable When `true`, execute the batch transaction in deferrable mode.
	BatchDeferrable *QueryParamsBatchDeferrable `json:"Batch-Deferrable,omitempty"`
}

// QueryParamsArrayMode defines parameters for Query.
type QueryParamsArrayMode string

// QueryParamsRawTextOutput defines parameters for Query.
type QueryParamsRawTextOutput string

// QueryParamsBatchIsolationLevel defines parameters for Query.
type QueryParamsBatchIsolationLevel string

// QueryParamsBatchReadOnly defines parameters for Query.
type QueryParamsBatchReadOnly string

// QueryParamsBatchDeferrable defines parameters for Query.
type QueryParamsBatchDeferrable string

// Query200JSONResponseBody defines parameters for Query.
type Query200JSONResponseBody struct {
	union json.RawMessage
}

// QueryJSONRequestBody defines body for Query for application/json ContentType.
type QueryJSONRequestBody = SQLRequest

// AsQueryResult returns the union data inside the Query200JSONResponseBody as a QueryResult
func (t Query200JSONResponseBody) AsQueryResult() (QueryResult, error) {
	var body QueryResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryResult overwrites any union data inside the Query200JSONResponseBody as the provided QueryResult
func (t *Query200JSONResponseBody) FromQueryResult(v QueryResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryResult performs a merge with any union data inside the Query200JSONResponseBody, using the provided QueryResult
func (t *Query200JSONResponseBody) MergeQueryResult(v QueryResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBatchResponse returns the union data inside the Query200JSONResponseBody as a BatchResponse
func (t Query200JSONResponseBody) AsBatchResponse() (BatchResponse, error) {
	var body BatchResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBatchResponse overwrites any union data inside the Query200JSONResponseBody as the provided BatchResponse
func (t *Query200JSONResponseBody) FromBatchResponse(v BatchResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBatchResponse performs a merge with any union data inside the Query200JSONResponseBody, using the provided BatchResponse
func (t *Query200JSONResponseBody) MergeBatchResponse(v BatchResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Query200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Query200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
