{{- if and .Values.postgres.enabled .Values.postgres.metastoreReader.create }}
apiVersion: v1
kind: Secret
metadata:
  name: metastore-reader-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
type: Opaque
stringData:
  metastore_reader_user: metastore_reader
  metastore_reader_password: {{ .Values.postgres.metastoreReader.password | quote }}
{{- end }}
