// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	extensions "xata/internal/extensions"

	mock "github.com/stretchr/testify/mock"
)

// ExtensionsProvider is an autogenerated mock type for the ExtensionsProvider type
type ExtensionsProvider struct {
	mock.Mock
}

type ExtensionsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ExtensionsProvider) EXPECT() *ExtensionsProvider_Expecter {
	return &ExtensionsProvider_Expecter{mock: &_m.Mock}
}

// GetAllOfferings provides a mock function with given fields:
func (_m *ExtensionsProvider) GetAllOfferings() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ExtensionsProvider_GetAllOfferings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOfferings'
type ExtensionsProvider_GetAllOfferings_Call struct {
	*mock.Call
}

// GetAllOfferings is a helper method to define mock.On call
func (_e *ExtensionsProvider_Expecter) GetAllOfferings() *ExtensionsProvider_GetAllOfferings_Call {
	return &ExtensionsProvider_GetAllOfferings_Call{Call: _e.mock.On("GetAllOfferings")}
}

func (_c *ExtensionsProvider_GetAllOfferings_Call) Run(run func()) *ExtensionsProvider_GetAllOfferings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExtensionsProvider_GetAllOfferings_Call) Return(_a0 []string) *ExtensionsProvider_GetAllOfferings_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetExtension provides a mock function with given fields: image, extensionName
func (_m *ExtensionsProvider) GetExtension(image string, extensionName string) *extensions.ExtensionSpec {
	ret := _m.Called(image, extensionName)

	var r0 *extensions.ExtensionSpec
	if rf, ok := ret.Get(0).(func(string, string) *extensions.ExtensionSpec); ok {
		r0 = rf(image, extensionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*extensions.ExtensionSpec)
		}
	}

	return r0
}

// ExtensionsProvider_GetExtension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtension'
type ExtensionsProvider_GetExtension_Call struct {
	*mock.Call
}

// GetExtension is a helper method to define mock.On call
//   - image string
//   - extensionName string
func (_e *ExtensionsProvider_Expecter) GetExtension(image interface{}, extensionName interface{}) *ExtensionsProvider_GetExtension_Call {
	return &ExtensionsProvider_GetExtension_Call{Call: _e.mock.On("GetExtension", image, extensionName)}
}

func (_c *ExtensionsProvider_GetExtension_Call) Run(run func(image string, extensionName string)) *ExtensionsProvider_GetExtension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ExtensionsProvider_GetExtension_Call) Return(_a0 *extensions.ExtensionSpec) *ExtensionsProvider_GetExtension_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetExtensions provides a mock function with given fields: image
func (_m *ExtensionsProvider) GetExtensions(image string) []extensions.ExtensionSpec {
	ret := _m.Called(image)

	var r0 []extensions.ExtensionSpec
	if rf, ok := ret.Get(0).(func(string) []extensions.ExtensionSpec); ok {
		r0 = rf(image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]extensions.ExtensionSpec)
		}
	}

	return r0
}

// ExtensionsProvider_GetExtensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtensions'
type ExtensionsProvider_GetExtensions_Call struct {
	*mock.Call
}

// GetExtensions is a helper method to define mock.On call
//   - image string
func (_e *ExtensionsProvider_Expecter) GetExtensions(image interface{}) *ExtensionsProvider_GetExtensions_Call {
	return &ExtensionsProvider_GetExtensions_Call{Call: _e.mock.On("GetExtensions", image)}
}

func (_c *ExtensionsProvider_GetExtensions_Call) Run(run func(image string)) *ExtensionsProvider_GetExtensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExtensionsProvider_GetExtensions_Call) Return(_a0 []extensions.ExtensionSpec) *ExtensionsProvider_GetExtensions_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetPreloadRequiredExtensions provides a mock function with given fields: image
func (_m *ExtensionsProvider) GetPreloadRequiredExtensions(image string) []extensions.ExtensionSpec {
	ret := _m.Called(image)

	var r0 []extensions.ExtensionSpec
	if rf, ok := ret.Get(0).(func(string) []extensions.ExtensionSpec); ok {
		r0 = rf(image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]extensions.ExtensionSpec)
		}
	}

	return r0
}

// ExtensionsProvider_GetPreloadRequiredExtensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreloadRequiredExtensions'
type ExtensionsProvider_GetPreloadRequiredExtensions_Call struct {
	*mock.Call
}

// GetPreloadRequiredExtensions is a helper method to define mock.On call
//   - image string
func (_e *ExtensionsProvider_Expecter) GetPreloadRequiredExtensions(image interface{}) *ExtensionsProvider_GetPreloadRequiredExtensions_Call {
	return &ExtensionsProvider_GetPreloadRequiredExtensions_Call{Call: _e.mock.On("GetPreloadRequiredExtensions", image)}
}

func (_c *ExtensionsProvider_GetPreloadRequiredExtensions_Call) Run(run func(image string)) *ExtensionsProvider_GetPreloadRequiredExtensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExtensionsProvider_GetPreloadRequiredExtensions_Call) Return(_a0 []extensions.ExtensionSpec) *ExtensionsProvider_GetPreloadRequiredExtensions_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetVersionsForOffering provides a mock function with given fields: offering
func (_m *ExtensionsProvider) GetVersionsForOffering(offering string) []string {
	ret := _m.Called(offering)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(offering)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ExtensionsProvider_GetVersionsForOffering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionsForOffering'
type ExtensionsProvider_GetVersionsForOffering_Call struct {
	*mock.Call
}

// GetVersionsForOffering is a helper method to define mock.On call
//   - offering string
func (_e *ExtensionsProvider_Expecter) GetVersionsForOffering(offering interface{}) *ExtensionsProvider_GetVersionsForOffering_Call {
	return &ExtensionsProvider_GetVersionsForOffering_Call{Call: _e.mock.On("GetVersionsForOffering", offering)}
}

func (_c *ExtensionsProvider_GetVersionsForOffering_Call) Run(run func(offering string)) *ExtensionsProvider_GetVersionsForOffering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ExtensionsProvider_GetVersionsForOffering_Call) Return(_a0 []string) *ExtensionsProvider_GetVersionsForOffering_Call {
	_c.Call.Return(_a0)
	return _c
}

// IsExtensionAvailable provides a mock function with given fields: image, extensionName
func (_m *ExtensionsProvider) IsExtensionAvailable(image string, extensionName string) bool {
	ret := _m.Called(image, extensionName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(image, extensionName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExtensionsProvider_IsExtensionAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExtensionAvailable'
type ExtensionsProvider_IsExtensionAvailable_Call struct {
	*mock.Call
}

// IsExtensionAvailable is a helper method to define mock.On call
//   - image string
//   - extensionName string
func (_e *ExtensionsProvider_Expecter) IsExtensionAvailable(image interface{}, extensionName interface{}) *ExtensionsProvider_IsExtensionAvailable_Call {
	return &ExtensionsProvider_IsExtensionAvailable_Call{Call: _e.mock.On("IsExtensionAvailable", image, extensionName)}
}

func (_c *ExtensionsProvider_IsExtensionAvailable_Call) Run(run func(image string, extensionName string)) *ExtensionsProvider_IsExtensionAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ExtensionsProvider_IsExtensionAvailable_Call) Return(_a0 bool) *ExtensionsProvider_IsExtensionAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewExtensionsProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewExtensionsProvider creates a new instance of ExtensionsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExtensionsProvider(t mockConstructorTestingTNewExtensionsProvider) *ExtensionsProvider {
	mock := &ExtensionsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
