name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  auth:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "auth"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  projects:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "projects"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  clusters:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "clusters"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  gateway:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "gateway"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  branch-operator:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "branch-operator"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  scale-to-zero-sidecar:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "scale-to-zero-sidecar"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  keycloak:
    uses: ./.github/workflows/build-image.yml
    with:
      target: "keycloak"
      git_ref: ${{ github.sha }}
      latest: true
    secrets: inherit

  build-charts:
    needs:
      - auth
      - projects
      - clusters
      - gateway
      - branch-operator
      - scale-to-zero-sidecar
      - keycloak
    uses: ./.github/workflows/build-charts.yaml
    secrets: inherit
    with:
      ref: ${{ github.sha }}
      image_specs: |
        IMAGE=${{ needs.auth.outputs.image }} DIGEST=${{ needs.auth.outputs.digest }}
        IMAGE=${{ needs.projects.outputs.image }} DIGEST=${{ needs.projects.outputs.digest }}
        IMAGE=${{ needs.clusters.outputs.image }} DIGEST=${{ needs.clusters.outputs.digest }}
        IMAGE=${{ needs.gateway.outputs.image }} DIGEST=${{ needs.gateway.outputs.digest }}
        IMAGE=${{ needs.branch-operator.outputs.image }} DIGEST=${{ needs.branch-operator.outputs.digest }}
        IMAGE=${{ needs.keycloak.outputs.image }} DIGEST=${{ needs.keycloak.outputs.digest }}
