// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package cellsmock

import (
	context "context"
	cells "xata/services/projects/cells"

	mock "github.com/stretchr/testify/mock"
)

// Cells is an autogenerated mock type for the Cells type
type Cells struct {
	mock.Mock
}

type Cells_Expecter struct {
	mock *mock.Mock
}

func (_m *Cells) EXPECT() *Cells_Expecter {
	return &Cells_Expecter{mock: &_m.Mock}
}

// GetCellConnection provides a mock function with given fields: ctx, organizationID, cellID
func (_m *Cells) GetCellConnection(ctx context.Context, organizationID string, cellID string) (cells.CellClient, error) {
	ret := _m.Called(ctx, organizationID, cellID)

	var r0 cells.CellClient
	if rf, ok := ret.Get(0).(func(context.Context, string, string) cells.CellClient); ok {
		r0 = rf(ctx, organizationID, cellID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cells.CellClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, cellID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cells_GetCellConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellConnection'
type Cells_GetCellConnection_Call struct {
	*mock.Call
}

// GetCellConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - cellID string
func (_e *Cells_Expecter) GetCellConnection(ctx interface{}, organizationID interface{}, cellID interface{}) *Cells_GetCellConnection_Call {
	return &Cells_GetCellConnection_Call{Call: _e.mock.On("GetCellConnection", ctx, organizationID, cellID)}
}

func (_c *Cells_GetCellConnection_Call) Run(run func(ctx context.Context, organizationID string, cellID string)) *Cells_GetCellConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Cells_GetCellConnection_Call) Return(_a0 cells.CellClient, _a1 error) *Cells_GetCellConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewCells interface {
	mock.TestingT
	Cleanup(func())
}

// NewCells creates a new instance of Cells. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCells(t mockConstructorTestingTNewCells) *Cells {
	mock := &Cells{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
