image:
  repository: xatatech/clusters
  tag: latest

config:
  clusters:
    storageClass: "csi-hostpath-sc"
    useOperatorForNewBranches: "true"
    volumeSnapshotClass: "csi-hostpath-snapclass"
    pgbackrest:
      bucket: "backups"
      region: "us-east-1"
      endpoint: "http://rustfs-eu.xata-clusters:9000"
